/**
 * Contenido enciclopedico extendido por herramienta (slug → datos ricos)
 * Complementa los datos basicos de seed-data.ts
 */
import type { PricingTier } from './types'

export interface ToolContent {
  features_es: string[]
  features_en: string[]
  pros_es: string[]
  pros_en: string[]
  cons_es: string[]
  cons_en: string[]
  best_for_es: string
  best_for_en: string
  not_ideal_for_es: string
  not_ideal_for_en: string
  founded_year: number | null
  integrations: string[]
  pricing_tiers: PricingTier[]
  screenshots: string[]
}

type ContentMap = Record<string, ToolContent>

export const toolContent: ContentMap = {
  notion: {
    features_es: ['Documentos colaborativos en tiempo real','Bases de datos relacionales personalizables','Wiki de equipo con páginas anidadas','Vistas Kanban, calendario, timeline y galería','10,000+ templates de la comunidad','API pública y automatizaciones','Integración con Slack, GitHub, Figma','Notion AI asistente de escritura'],
    features_en: ['Real-time collaborative docs','Customizable relational databases','Team wiki with nested pages','Kanban, calendar, timeline and gallery views','10,000+ community templates','Public API and automations','Slack, GitHub, Figma integrations','Notion AI writing assistant'],
    pros_es: ['Extremadamente flexible y personalizable','Excelente para documentación de equipo','Base de datos potente sin código','Plan gratuito muy generoso'],
    pros_en: ['Extremely flexible and customizable','Excellent for team documentation','Powerful no-code database','Very generous free plan'],
    cons_es: ['Curva de aprendizaje alta para nuevos usuarios','Rendimiento lento con bases de datos grandes','Acceso offline limitado','Precio por usuario se acumula rápido'],
    cons_en: ['Steep learning curve for new users','Slow with large databases','Limited offline access','Per-user pricing adds up fast'],
    best_for_es: 'Equipos que necesitan docs + bases de datos + wiki en una sola herramienta y startups que quieren documentar todo su conocimiento.',
    best_for_en: 'Teams needing docs + databases + wiki in one tool and startups wanting to document all their knowledge.',
    not_ideal_for_es: 'No recomendado si necesitas acceso offline real, gestión de proyectos avanzada con dependencias, o buscas una herramienta simple de solo notas.',
    not_ideal_for_en: 'Not if you need real offline access, advanced project management with dependencies, or a simple note-only tool.',
    founded_year: 2016,
    integrations: ['Slack','GitHub','Figma','Google Drive','Zapier','Typeform','Jira','Trello'],
    screenshots: [],
    pricing_tiers: [
      { name: 'Gratis', price_monthly: 0, features: ['Bloques ilimitados','10 invitados','Historial 7 días'], limits: 'Equipos hasta 10' },
      { name: 'Plus', price_monthly: 10, features: ['Bloques ilimitados','100 invitados','Historial 30 días','Carga ilimitada'], limits: '' },
      { name: 'Business', price_monthly: 15, features: ['SAML SSO','Exportación masiva PDF','Teams privados'], limits: '' },
    ],
  },
  slack: {
    features_es: ['Canales públicos y privados','Mensajería directa y grupal','Llamadas de voz y vídeo (Huddles)','Compartir pantalla y archivos','2,600+ integraciones con apps','Workflow Builder sin código','Búsqueda de mensajes históricos','Slack Connect para colaborar con externos'],
    features_en: ['Public and private channels','Direct and group messaging','Voice and video calls (Huddles)','Screen and file sharing','2,600+ app integrations','No-code Workflow Builder','Historical message search','Slack Connect for external collaboration'],
    pros_es: ['Ecosistema de integraciones enorme','Interfaz intuitiva y pulida','Muy buena búsqueda de mensajes','Slack Connect útil entre empresas'],
    pros_en: ['Massive integration ecosystem','Intuitive, polished interface','Great message search','Slack Connect useful between companies'],
    cons_es: ['Caro por usuario en equipos grandes','Notificaciones abrumadoras sin configurar','Plan gratuito limita historial a 90 días','Llamadas de vídeo básicas vs Zoom'],
    cons_en: ['Expensive per user on large teams','Overwhelming notifications without setup','Free plan limits history to 90 days','Basic video calls vs Zoom'],
    best_for_es: 'Equipos de tecnología y empresas que necesitan comunicación asíncrona con muchas integraciones.',
    best_for_en: 'Tech teams and companies needing structured async communication with many integrations.',
    not_ideal_for_es: 'No ideal si buscas algo simple y gratis sin límite de historial, o si necesitas videollamadas avanzadas.',
    not_ideal_for_en: 'Not ideal if you want something simple, free with no history limit, or need advanced video calls.',
    founded_year: 2013,
    integrations: ['Google Drive','Trello','GitHub','Jira','Zoom','Salesforce','Asana','Monday'],
    screenshots: [],
    pricing_tiers: [
      { name: 'Gratis', price_monthly: 0, features: ['Historial 90 días','10 integraciones','1:1 llamadas'], limits: '10k mensajes' },
      { name: 'Pro', price_monthly: 7.25, features: ['Historial ilimitado','Integraciones ilimitadas','Llamadas grupales','Huddles'], limits: '' },
      { name: 'Business+', price_monthly: 12.50, features: ['SAML SSO','Exportación datos','Slack Connect','SLA 99.99%'], limits: '' },
    ],
  },
  figma: {
    features_es: ['Diseño vectorial en navegador','Prototipado interactivo avanzado','Componentes y auto-layout','Librerías de design system','Colaboración multijugador en tiempo real','Figma Slides para presentaciones','Dev Mode para handoff a desarrollo','Plugins y widgets'],
    features_en: ['Browser vector design','Advanced interactive prototyping','Components and auto-layout','Design system libraries','Real-time multiplayer collaboration','Figma Slides for presentations','Dev Mode for handoff','Plugins and widgets'],
    pros_es: ['Colaboración en tiempo real excelente','Basado en navegador, sin instalar nada','Auto-layout ahorra horas de trabajo','Dev Mode mejora el handoff a desarrollo'],
    pros_en: ['Excellent real-time collaboration','Browser-based, no installation','Auto-layout saves hours of work','Dev Mode improves developer handoff'],
    cons_es: ['Plan gratuito limitado a 3 archivos','Rendimiento lento en archivos muy grandes','Precio subiendo desde adquisición Adobe','Requiere internet para colaborar'],
    cons_en: ['Free plan limited to 3 files','Slow on very large files','Prices rising since Adobe acquisition','Requires internet for collaboration'],
    best_for_es: 'Equipos de diseño y producto que necesitan colaboración en tiempo real, design systems y prototipado profesional.',
    best_for_en: 'Design and product teams needing real-time collaboration, shared design systems and professional prototyping.',
    not_ideal_for_es: 'No ideal si trabajas offline, haces ilustración compleja o motion graphics, o buscas open source gratuito.',
    not_ideal_for_en: 'Not if you work offline, do complex illustration or motion graphics, or want free open source.',
    founded_year: 2012,
    integrations: ['Slack','Jira','GitHub','Storybook','Zeplin','Notion','Maze','UserTesting'],
    screenshots: [],
    pricing_tiers: [
      { name: 'Starter', price_monthly: 0, features: ['3 archivos Figma Design','Colaboración ilimitada'], limits: '3 archivos' },
      { name: 'Professional', price_monthly: 12, features: ['Archivos ilimitados','Librerías equipo','Dev Mode','Historial 30 días'], limits: '' },
      { name: 'Organization', price_monthly: 45, features: ['Design systems','Analíticas','Branching','SSO'], limits: '' },
    ],
  },
  trello: {
    features_es: ['Tableros Kanban drag & drop','Listas, tarjetas y checklists','Automatizaciones con Butler','Power-Ups para extender funcionalidad','Plantillas de tablero','Vistas timeline, calendario, dashboard','App móvil completa','Integraciones con apps clave'],
    features_en: ['Drag & drop Kanban boards','Lists, cards and checklists','Butler automations','Power-Ups to extend functionality','Board templates','Timeline, calendar, dashboard views','Full mobile app','Key app integrations'],
    pros_es: ['Increíblemente fácil de usar','Gratuito con muchas funcionalidades','Interfaz visual clara y atractiva','Butler automatiza tareas repetitivas'],
    pros_en: ['Incredibly easy to use','Free tier has lots of functionality','Clean, attractive visual interface','Butler automates repetitive tasks'],
    cons_es: ['No escala bien para proyectos complejos','Sin vista Gantt nativa robusta','Power-Ups limitados en plan gratuito','Difícil seguir deadlines en muchos tableros'],
    cons_en: ["Doesn't scale for complex projects",'No robust native Gantt view','Free plan Power-Up limits','Hard to track deadlines across many boards'],
    best_for_es: 'Equipos pequeños e individuos que quieren simplicidad visual para organizar tareas sin complejidad.',
    best_for_en: 'Small teams and individuals wanting visual simplicity to organize tasks without complexity.',
    not_ideal_for_es: 'No recomendado para gestión empresarial, proyectos con dependencias complejas o reporting avanzado.',
    not_ideal_for_en: 'Not for enterprise portfolio management, complex dependency projects, or advanced reporting.',
    founded_year: 2011,
    integrations: ['Slack','Google Drive','Jira','Evernote','GitHub','Dropbox','Zapier'],
    screenshots: [],
    pricing_tiers: [
      { name: 'Gratis', price_monthly: 0, features: ['10 tableros','Power-Ups ilimitados','Automatización Butler'], limits: '10 tableros' },
      { name: 'Standard', price_monthly: 5, features: ['Tableros ilimitados','Adjuntos 250MB','Vistas avanzadas','Campos personalizados'], limits: '' },
      { name: 'Premium', price_monthly: 10, features: ['Vistas timeline, dashboard','Exportación datos','Admin controls'], limits: '' },
    ],
  },
  asana: {
    features_es: ['Vistas lista, tablero, calendario, timeline/Gantt','Portafolios y objetivos SMART','Workflows automatizados','Formularios y aprobaciones','Dependencias entre tareas','Reporting y dashboards','Gestión de carga de trabajo','200+ integraciones'],
    features_en: ['List, board, calendar, timeline/Gantt views','Portfolios and SMART goals','Automated workflows','Forms and approvals','Task dependencies','Reporting and dashboards','Workload management','200+ integrations'],
    pros_es: ['Muy completo para gestión profesional','Vistas múltiples potentes (Gantt, calendario)','Buenas herramientas de reporting','Workflows y reglas automatizadas'],
    pros_en: ['Very complete for professional PM','Powerful multiple views','Good reporting tools','Automated workflows and rules'],
    cons_es: ['Precio elevado para equipos pequeños','Interfaz puede resultar abrumadora','Plan gratuito muy limitado','Curva de aprendizaje media-alta'],
    cons_en: ['High price for small teams','Interface can be overwhelming','Very limited free plan','Medium-high learning curve'],
    best_for_es: 'Equipos medianos-grandes que necesitan gestión estructurada con jerarquías, dependencias y reporting.',
    best_for_en: 'Mid-to-large teams needing structured management with hierarchies, dependencies and reporting.',
    not_ideal_for_es: 'No para freelancers solitarios o equipos pequeños que solo necesitan un tablero kanban.',
    not_ideal_for_en: 'Not for solo freelancers or very small teams just needing a kanban board.',
    founded_year: 2008,
    integrations: ['Slack','Google Drive','Microsoft Teams','Outlook','Adobe CC','Zoom','Jira','Salesforce'],
    screenshots: [],
    pricing_tiers: [
      { name: 'Personal', price_monthly: 0, features: ['Tareas básicas','Lista y tablero'], limits: '10 personas' },
      { name: 'Starter', price_monthly: 10.99, features: ['Timeline','Workflows','Formularios','Dashboards'], limits: '' },
      { name: 'Advanced', price_monthly: 24.99, features: ['Portafolios','Objetivos','Aprobaciones','Reporting avanzado'], limits: '' },
    ],
  },
  clickup: {
    features_es: ['15+ vistas: lista, tablero, Gantt, calendario, mapa mental','Documentos colaborativos','Chat nativo del equipo','Objetivos y OKRs','Pizarras digitales','Automatizaciones sin código','Control de tiempo nativo','Formularios y dashboards'],
    features_en: ['15+ views: list, board, Gantt, calendar, mind map','Collaborative docs','Native team chat','Goals and OKRs','Digital whiteboards','No-code automations','Native time tracking','Forms and dashboards'],
    pros_es: ['Más funcionalidades que cualquier competidor','Excelente relación calidad-precio','Plan gratuito muy completo','Actualizaciones frecuentes'],
    pros_en: ['More features than any competitor','Great value for money','Very complete free plan','Frequent updates'],
    cons_es: ['Interfaz cargada, difícil al principio','Rendimiento irregular a veces','Muchas funcionalidades = abrumador','App móvil no está a la altura'],
    cons_en: ['Cluttered interface, difficult at first','Inconsistent performance','Feature overload = overwhelming','Mobile app not up to par'],
    best_for_es: 'Equipos que quieren consolidar múltiples herramientas en una sola plataforma con máximo control.',
    best_for_en: 'Teams wanting to consolidate multiple tools into one platform with maximum control.',
    not_ideal_for_es: 'No ideal si buscas simplicidad extrema o tu equipo se abruma con muchas opciones.',
    not_ideal_for_en: 'Not if you seek extreme simplicity or your team gets overwhelmed with options.',
    founded_year: 2017,
    integrations: ['Slack','GitHub','GitLab','Google Drive','Outlook','Calendar','Toggl','Zapier'],
    screenshots: [],
    pricing_tiers: [
      { name: 'Free', price_monthly: 0, features: ['100MB','Tareas ilimitadas','60 automatizaciones/mes'], limits: '5 espacios' },
      { name: 'Unlimited', price_monthly: 7, features: ['Almacenamiento ilimitado','Automatizaciones ilimitadas','Dashboards','Invitados'], limits: '' },
      { name: 'Business', price_monthly: 12, features: ['Objetivos','Pizarras','Time tracking','SAML SSO'], limits: '' },
    ],
  },
  monday: {
    features_es: ['Tableros visuales con columnas personalizables','Vistas Gantt, Kanban, calendario, timeline','Automatizaciones visuales sin código','Dashboards con widgets','200+ plantillas por industria','Formularios de captura de datos','Control de tiempo y presupuesto','Workdocs colaborativos'],
    features_en: ['Visual boards with customizable columns','Gantt, Kanban, calendar, timeline views','Visual no-code automations','Widget dashboards','200+ industry templates','Data capture forms','Time and budget tracking','Collaborative Workdocs'],
    pros_es: ['Interfaz visual muy atractiva y colorida','Fácil de aprender y usar','Muchas plantillas pre-hechas','Buen soporte de automatizaciones'],
    pros_en: ['Very attractive, colorful interface','Easy to learn and use','Many ready-made templates','Good automation support'],
    cons_es: ['Mínimo 3 usuarios (27eur/mes mínimo)','Caro comparado con alternativas','Almacenamiento limitado en planes bajos','Menos potente para desarrollo software'],
    cons_en: ['Minimum 3 users (27eur/month min)','Expensive vs alternatives','Limited storage on lower plans','Less powerful for software dev'],
    best_for_es: 'Empresas que valoran interfaz visual premium y necesitan cubrir múltiples departamentos.',
    best_for_en: 'Companies valuing premium visual interface and needing to cover multiple departments.',
    not_ideal_for_es: 'No para freelancers solitarios, equipos con presupuesto ajustado o desarrollo software puro.',
    not_ideal_for_en: 'Not for solo freelancers, budget-constrained teams or pure software dev.',
    founded_year: 2012,
    integrations: ['Slack','Google Drive','Outlook','Jira','Salesforce','Zoom','HubSpot','Zapier'],
    screenshots: [],
    pricing_tiers: [
      { name: 'Basic', price_monthly: 9, features: ['Tableros ilimitados','200+ plantillas'], limits: 'Min 3 usuarios (27eur/mes)' },
      { name: 'Standard', price_monthly: 12, features: ['Gantt y calendario','Invitados','Automatizaciones'], limits: '' },
      { name: 'Pro', price_monthly: 19, features: ['Dashboards','Time tracking','Formularios','Dependencias'], limits: '' },
    ],
  },
  hubspot: {
    features_es: ['CRM gratuito con contactos ilimitados','Pipeline de ventas drag & drop','Email marketing y automatización','Chat en vivo y chatbots','Landing pages y formularios','Informes y dashboards','CMS para web corporativa','API pública extensa'],
    features_en: ['Free CRM with unlimited contacts','Drag & drop sales pipeline','Email marketing and automation','Live chat and chatbots','Landing pages and forms','Reports and dashboards','Corporate website CMS','Extensive public API'],
    pros_es: ['CRM realmente gratuito y muy completo','Todo en uno: marketing, ventas y servicio','Gran ecosistema de partners y apps','Academia gratuita de formación'],
    pros_en: ['Truly free and very complete CRM','All-in-one: marketing, sales and service','Great partner and app ecosystem','Free training academy'],
    cons_es: ['Se vuelve caro al contratar módulos avanzados','Personalización limitada en reporting','Curva de aprendizaje usando todas las herramientas','Difícil migrar datos a otro CRM'],
    cons_en: ['Gets expensive with advanced modules','Limited reporting customization','Steep learning curve using all tools','Hard to migrate data to another CRM'],
    best_for_es: 'PYMES que empiezan con CRM y quieren escalar a marketing automation sin cambiar de plataforma.',
    best_for_en: 'SMBs starting with CRM wanting to scale to marketing automation without changing platforms.',
    not_ideal_for_es: 'No si solo necesitas tracking de ventas puro o tienes +1000 empleados con necesidades muy específicas.',
    not_ideal_for_en: 'Not if you need pure sales tracking or have 1000+ employees with very specific needs.',
    founded_year: 2006,
    integrations: ['Slack','Gmail','Outlook','Shopify','WordPress','Stripe','Zoom','LinkedIn'],
    screenshots: [],
    pricing_tiers: [
      { name: 'Gratis', price_monthly: 0, features: ['CRM completo','Contactos ilimitados','Pipeline ventas','Chat en vivo'], limits: '' },
      { name: 'Starter', price_monthly: 15, features: ['Email marketing','Automatización simple','Landing pages'], limits: '1,000 contactos' },
      { name: 'Professional', price_monthly: 800, features: ['Marketing automation','Blog SEO','Reporting avanzado'], limits: '2,000 contactos' },
    ],
  },
  pipedrive: {
    features_es: ['Pipeline visual drag & drop','Seguimiento de emails y llamadas','Automatización de tareas repetitivas','Campos personalizables','Informes y pronósticos de ventas','App móvil completa','Web forms para capturar leads','API abierta'],
    features_en: ['Visual drag & drop pipeline','Email and call tracking','Repetitive task automation','Customizable fields','Sales reports and forecasts','Full mobile app','Web forms for lead capture','Open API'],
    pros_es: ['Enfoque láser en pipeline de ventas','Interfaz muy intuitiva','Buenas automatizaciones','Excelente app móvil'],
    pros_en: ['Laser focus on sales pipeline','Very intuitive interface','Good automations','Excellent mobile app'],
    cons_es: ['Solo CRM de ventas, sin marketing','Precio por usuario se acumula','Reporting avanzado solo en planes altos','Sin plan gratuito real (solo trial)'],
    cons_en: ['Sales-only CRM, no marketing','Per-user pricing adds up','Advanced reporting on higher plans only','No real free plan (trial only)'],
    best_for_es: 'Equipos de ventas B2B que quieren un CRM simple y visual enfocado en pipeline.',
    best_for_en: 'B2B sales teams wanting a simple, visual CRM focused exclusively on pipeline.',
    not_ideal_for_es: 'No si necesitas marketing automation, servicio al cliente o CMS integrado.',
    not_ideal_for_en: 'Not if you need marketing automation, customer service or integrated CMS.',
    founded_year: 2010,
    integrations: ['Google Workspace','Microsoft 365','Slack','Zapier','Trello','Asana','QuickBooks'],
    screenshots: [],
    pricing_tiers: [
      { name: 'Essential', price_monthly: 14, features: ['Pipeline gestión','Contactos','Email tracking'], limits: '3,000 leads' },
      { name: 'Advanced', price_monthly: 34, features: ['Email sync','Automatizaciones','Templates email'], limits: '' },
      { name: 'Professional', price_monthly: 49, features: ['Reporting avanzado','Forecast','Contratos','Soporte 24/7'], limits: '' },
    ],
  },
  semrush: {
    features_es: ['Investigación de keywords avanzada','Auditoría técnica SEO del sitio','Análisis de backlinks','Espionaje de competidores','Content Marketing Toolkit','Plan de PPC y display','Social Media Toolkit','Monitor de marca y posición'],
    features_en: ['Advanced keyword research','Technical site SEO audit','Backlink analysis','Competitor intelligence','Content Marketing Toolkit','PPC and display planning','Social Media Toolkit','Brand and position monitoring'],
    pros_es: ['Suite SEO más completa del mercado','Excelente para espionaje competitivo','Herramientas de contenido muy útiles','Base de datos de keywords enorme'],
    pros_en: ['Most complete SEO suite','Excellent competitive intelligence','Very useful content tools','Massive keyword database'],
    cons_es: ['Muy caro para freelancers (130eur/mes)','Muchas funcionalidades = abrumador','Datos de tráfico no siempre precisos','Curva de aprendizaje larga'],
    cons_en: ['Very expensive for freelancers','Too many features = overwhelming','Traffic data not always accurate','Long learning curve'],
    best_for_es: 'Agencias de marketing y SEOs profesionales que necesitan la suite más completa con datos competitivos.',
    best_for_en: 'Marketing agencies and professional SEOs needing the most complete suite with competitive data.',
    not_ideal_for_es: 'No para bloggers o pequeños negocios con presupuesto limitado.',
    not_ideal_for_en: 'Not for bloggers or small businesses on a tight budget.',
    founded_year: 2008,
    integrations: ['Google Analytics','Google Search Console','Google Ads','Trello','Zapier','Slack'],
    screenshots: [],
    pricing_tiers: [
      { name: 'Pro', price_monthly: 129.95, features: ['5 proyectos','500 keywords','10k resultados/informe'], limits: '' },
      { name: 'Guru', price_monthly: 249.95, features: ['15 proyectos','Content Marketing','Histórico datos'], limits: '' },
      { name: 'Business', price_monthly: 499.95, features: ['40 proyectos','API acceso','White label'], limits: '' },
    ],
  },
  ahrefs: {
    features_es: ['Mayor base de datos de backlinks del mundo','Site Explorer para auditar webs','Keywords Explorer con 11 motores','Site Audit técnico avanzado','Rank Tracker diario','Content Explorer para ideas','Ahrefs Webmaster Tools gratis','Alertas de menciones y backlinks'],
    features_en: ['Largest backlink database','Site Explorer for website auditing','Keywords Explorer with 11 engines','Advanced technical Site Audit','Daily Rank Tracker','Content Explorer for ideas','Free Webmaster Tools','Mention and backlink alerts'],
    pros_es: ['Mejor base de datos de backlinks','UI moderna y rápida','Webmaster Tools gratis','Content Explorer muy útil'],
    pros_en: ['Best backlink database','Modern, fast UI','Free Webmaster Tools','Content Explorer very useful'],
    cons_es: ['Caro (99$/mes mínimo)','Sin herramientas de PPC o social media','Plan Lite muy limitado'],
    cons_en: ['Expensive ($99/month min)','No PPC or social media tools','Lite plan very limited'],
    best_for_es: 'SEOs profesionales que priorizan backlinks y auditoría técnica con la base de datos más completa.',
    best_for_en: 'SEO pros prioritizing backlink analysis and technical audit with the most complete database.',
    not_ideal_for_es: 'No si necesitas PPC, social media o suite todo en uno de marketing digital.',
    not_ideal_for_en: 'Not for those needing PPC, social media tools, or all-in-one digital marketing suite.',
    founded_year: 2011,
    integrations: ['Google Search Console','Google Analytics','Slack','Data Studio'],
    screenshots: [],
    pricing_tiers: [
      { name: 'Lite', price_monthly: 99, features: ['Site Explorer','Keywords Explorer','Site Audit','Rank Tracker'], limits: '5 proyectos' },
      { name: 'Standard', price_monthly: 199, features: ['Content Explorer','Domain Comparison','6 meses histórico'], limits: '' },
      { name: 'Advanced', price_monthly: 399, features: ['API','Looker Studio','2 años histórico'], limits: '' },
    ],
  },
  canva: {
    features_es: ['Editor drag-and-drop','200,000+ plantillas profesionales','Brand Kit para identidad de marca','Colaboración en tiempo real','Edición de fotos y vídeos','Planificador de redes sociales','Canva Docs y Canva Sites','Canva IA (Magic Studio)'],
    features_en: ['Drag-and-drop editor','200,000+ professional templates','Brand Kit for brand identity','Real-time collaboration','Photo and video editing','Social media scheduler','Canva Docs and Canva Sites','Canva AI (Magic Studio)'],
    pros_es: ['Increíblemente fácil de usar','Plan gratuito muy generoso','Miles de plantillas y assets','Colaboración en tiempo real'],
    pros_en: ['Incredibly easy to use','Very generous free plan','Thousands of templates and assets','Real-time collaboration'],
    cons_es: ['Limitado para diseño profesional avanzado','Muchas funcionalidades premium de pago','Rendimiento lento con archivos grandes','Sin verdadero modo offline'],
    cons_en: ['Limited for advanced professional design','Many premium features behind paywall','Slow with large files','No true offline mode'],
    best_for_es: 'No diseñadores, equipos de marketing, creadores de contenido y pequeñas empresas que necesitan diseño rápido y profesional.',
    best_for_en: 'Non-designers, marketing teams, content creators and small businesses needing quick professional design.',
    not_ideal_for_es: 'No para diseñadores profesionales que necesitan ilustración vectorial avanzada, motion graphics o control tipográfico preciso.',
    not_ideal_for_en: 'Not for professional designers needing advanced vector illustration, motion graphics or precise typography control.',
    founded_year: 2013,
    integrations: ['Google Drive','Dropbox','Slack','HubSpot','Instagram','Facebook','TikTok','YouTube'],
    screenshots: [],
    pricing_tiers: [
      { name: 'Gratis', price_monthly: 0, features: ['250,000 plantillas','5GB almacenamiento','Colaboración básica'], limits: '' },
      { name: 'Pro', price_monthly: 12.99, features: ['100M+ assets premium','Brand Kit','Planificador contenido','1TB almacenamiento'], limits: '' },
      { name: 'Equipos', price_monthly: 25.99, features: ['Todo Pro','Colaboración avanzada','Control de equipos','Informes'], limits: '3 personas' },
    ],
  },
  obsidian: {
    features_es: ['Notas en archivos Markdown locales','Enlaces bidireccionales y grafos de conocimiento','1,500+ plugins comunitarios','Canvas (lienzo visual infinito)','Pestañas y paneles personalizables','Sincronización cifrada (de pago)','Templates y snippets','Modo lectura/edición unificado'],
    features_en: ['Local Markdown note files','Bidirectional links and knowledge graphs','1,500+ community plugins','Canvas (infinite visual canvas)','Customizable tabs and panes','Encrypted sync (paid)','Templates and snippets','Unified reading/editing mode'],
    pros_es: ['Tus datos son tuyos: archivos locales','Extensible con 1,500+ plugins','Rapidísimo y ligero','Completamente offline'],
    pros_en: ['Your data is yours: local files','Extensible with 1,500+ plugins','Blazing fast and lightweight','Fully offline'],
    cons_es: ['Curva de aprendizaje con plugins','Sincronización móvil de pago','Diseño menos pulido vs Notion','Sin colaboración en tiempo real'],
    cons_en: ['Learning curve with plugins','Mobile sync is paid','Less polished UI vs Notion','No real-time collaboration'],
    best_for_es: 'Investigadores, desarrolladores, escritores y cualquiera que valore tener sus notas en archivos locales con control total.',
    best_for_en: 'Researchers, developers, writers and anyone who values keeping notes in local files with full control.',
    not_ideal_for_es: 'No para equipos que necesitan colaboración en tiempo real o personas que prefieren una interfaz visual sin configuración.',
    not_ideal_for_en: 'Not for teams needing real-time collaboration or people who prefer a visual interface without configuration.',
    founded_year: 2020,
    integrations: ['Git','Zotero','Anki','Readwise','Todoist','Google Calendar'],
    screenshots: [],
    pricing_tiers: [
      { name: 'Personal', price_monthly: 0, features: ['Notas ilimitadas','Plugins','Uso local'], limits: '' },
      { name: 'Sync', price_monthly: 5, features: ['Sync entre dispositivos','Historial 1 año'], limits: '' },
      { name: 'Commercial', price_monthly: 50, features: ['Uso comercial','Soporte prioritario'], limits: 'Por usuario/año' },
    ],
  },
  anytype: {
    features_es: ['Editor basado en bloques como Notion','Cifrado local de extremo a extremo','Sincronización P2P privada','Bases de datos y relaciones','Modo offline completo','Aplicaciones nativas de escritorio y móvil','Código abierto con comunidad activa','Tipos personalizables de objetos'],
    features_en: ['Block-based editor like Notion','Local end-to-end encryption','Private P2P synchronization','Databases and relations','Full offline mode','Native desktop and mobile apps','Open source with active community','Customizable object types'],
    pros_es: ['Privacidad total con cifrado local','Muy similar a Notion en experiencia','Open source y gratuito','Funciona offline sin problema'],
    pros_en: ['Full privacy with local encryption','Very Notion-like experience','Open source and free','Works perfectly offline'],
    cons_es: ['Aún en desarrollo activo (cambios frecuentes)','Menos integraciones que Notion','Comunidad más pequeña','Sincronización puede ser lenta'],
    cons_en: ['Still in active development (frequent changes)','Fewer integrations than Notion','Smaller community','Sync can be slow at times'],
    best_for_es: 'Usuarios que quieren la experiencia Notion con privacidad real, cifrado y control total de sus datos.',
    best_for_en: 'Users wanting the Notion experience with real privacy, encryption and full data control.',
    not_ideal_for_es: 'No si necesitas colaboración avanzada en tiempo real o integraciones con muchas herramientas externas.',
    not_ideal_for_en: 'Not if you need advanced real-time collaboration or many external tool integrations.',
    founded_year: 2020,
    integrations: ['IPFS','P2P sync'],
    screenshots: [],
    pricing_tiers: [
      { name: 'Free', price_monthly: 0, features: ['1GB almacenamiento','Sincronización P2P','Cifrado local'], limits: '' },
      { name: 'Pro', price_monthly: 3, features: ['10GB almacenamiento','Multi-espacio','Soporte prioritario'], limits: '' },
    ],
  },
  linear: {
    features_es: ['Issues y proyectos ultrarrápidos','Vistas Kanban, timeline y roadmap','Atajos de teclado para todo','Sprints y ciclos automáticos','Estimaciones y planning','Integraciones con GitHub/GitLab/Slack','App de escritorio nativa','Workflows automatizados'],
    features_en: ['Lightning-fast issues and projects','Kanban, timeline and roadmap views','Keyboard shortcuts for everything','Automatic sprints and cycles','Estimations and planning','GitHub/GitLab/Slack integrations','Native desktop app','Automated workflows'],
    pros_es: ['La herramienta más rápida del mercado','Atajos de teclado increíbles','UI moderna y minimalista','Excelente para equipos de software'],
    pros_en: ['Fastest tool on the market','Incredible keyboard shortcuts','Modern minimalist UI','Excellent for software teams'],
    cons_es: ['Solo para gestión de software','Pocas vistas comparado con Asana/ClickUp','Plan gratuito limitado','Sin app móvil completa'],
    cons_en: ['Only for software management','Fewer views compared to Asana/ClickUp','Limited free plan','No full mobile app'],
    best_for_es: 'Startups y equipos de desarrollo que priorizan velocidad y simplicidad por encima de funcionalidades masivas.',
    best_for_en: 'Startups and dev teams prioritizing speed and simplicity over massive feature sets.',
    not_ideal_for_es: 'No para equipos de marketing, RRHH o gestión empresarial general que necesita vistas Gantt y portfolios.',
    not_ideal_for_en: 'Not for marketing, HR or general enterprise teams needing Gantt views and portfolios.',
    founded_year: 2019,
    integrations: ['GitHub','GitLab','Slack','Figma','Sentry','Zendesk','Discord','Notion'],
    screenshots: [],
    pricing_tiers: [
      { name: 'Gratis', price_monthly: 0, features: ['Issues ilimitados','Vistas básicas','250 issues'], limits: '' },
      { name: 'Basic', price_monthly: 8, features: ['Issues ilimitados','Sprints','Roadmaps','Integraciones'], limits: '' },
      { name: 'Business', price_monthly: 14, features: ['SSO SAML','Equipos ilimitados','Exportación datos'], limits: '' },
    ],
  },
  jira: {
    features_es: ['Gestión de proyectos Scrum y Kanban','Seguimiento avanzado de bugs e issues','Roadmaps y planes de equipo','Workflows personalizables','Informes ágiles (burndown, velocity)','Backlog y planificación de sprints','Integración con todo el ecosistema Atlassian','Automatización con Jira Automation'],
    features_en: ['Scrum and Kanban project management','Advanced bug and issue tracking','Team roadmaps and plans','Customizable workflows','Agile reports (burndown, velocity)','Backlog and sprint planning','Full Atlassian ecosystem integration','Jira Automation'],
    pros_es: ['Estándar en la industria de software','Workflows increíblemente personalizables','Reportes ágiles muy completos','Gran ecosistema de apps y plugins'],
    pros_en: ['Industry standard for software','Incredibly customizable workflows','Very comprehensive agile reports','Large app and plugin ecosystem'],
    cons_es: ['Complejo y difícil de configurar','Interfaz lenta y pesada','Caro para equipos grandes','La personalización puede ser abrumadora'],
    cons_en: ['Complex and difficult to configure','Slow and heavy interface','Expensive for large teams','Customization can be overwhelming'],
    best_for_es: 'Empresas grandes y equipos de software con procesos ágiles complejos que necesitan máxima personalización.',
    best_for_en: 'Large enterprises and software teams with complex agile processes needing maximum customization.',
    not_ideal_for_es: 'No para startups que buscan simplicidad, equipos pequeños o proyectos no técnicos.',
    not_ideal_for_en: 'Not for startups seeking simplicity, small teams or non-technical projects.',
    founded_year: 2002,
    integrations: ['Confluence','Bitbucket','GitHub','Slack','Figma','Zendesk','CircleCI','Jenkins'],
    screenshots: [],
    pricing_tiers: [
      { name: 'Gratis', price_monthly: 0, features: ['10 usuarios','Scrum/Kanban','Backlog','2GB'], limits: '10 usuarios' },
      { name: 'Standard', price_monthly: 8.15, features: ['35,000 usuarios','Roles','Automatización','250GB'], limits: 'Por usuario' },
      { name: 'Premium', price_monthly: 16, features: ['Planes avanzados','SLA 99.9%','Sandbox','IA'], limits: 'Por usuario' },
    ],
  },
  discord: {
    features_es: ['Servidores con canales de texto y voz','Videollamadas grupales HD','Compartir pantalla y streaming','Bots personalizables con API','Roles y permisos avanzados','Integraciones con juegos y apps','Stage Channels para eventos','Discord Nitro con mejoras premium'],
    features_en: ['Servers with text and voice channels','HD group video calls','Screen sharing and streaming','Customizable bots via API','Advanced roles and permissions','Game and app integrations','Stage Channels for events','Discord Nitro with premium perks'],
    pros_es: ['Completamente gratis y sin límites reales','Excelente calidad de audio','Comunidades vibrantes y activas','Gran ecosistema de bots'],
    pros_en: ['Completely free with no real limits','Excellent audio quality','Vibrant active communities','Great bot ecosystem'],
    cons_es: ['Marca gaming puede no ser profesional','Sin cifrado de extremo a extremo','Muchas distracciones (juegos, stickers)','Historial de mensajes sin búsqueda avanzada'],
    cons_en: ['Gaming branding may feel unprofessional','No end-to-end encryption','Many distractions (games, stickers)','Message history lacks advanced search'],
    best_for_es: 'Comunidades online, equipos de desarrollo, gaming y grupos que necesitan comunicación por voz gratis y de calidad.',
    best_for_en: 'Online communities, dev teams, gaming and groups needing free quality voice communication.',
    not_ideal_for_es: 'No para empresas que necesitan compliance, cifrado avanzado o integraciones empresariales profundas.',
    not_ideal_for_en: 'Not for enterprises needing compliance, advanced encryption or deep enterprise integrations.',
    founded_year: 2015,
    integrations: ['Spotify','Twitch','YouTube','GitHub','Trello','Notion','Xbox','PlayStation'],
    screenshots: [],
    pricing_tiers: [
      { name: 'Gratis', price_monthly: 0, features: ['Canales ilimitados','7 días historial archivos','Llamadas de voz básicas'], limits: '' },
      { name: 'Nitro Basic', price_monthly: 2.99, features: ['Emojis personalizados','Archivos 50MB','Insignia'], limits: '' },
      { name: 'Nitro', price_monthly: 9.99, features: ['Emojis en todos lados','Streaming HD','Archivos 500MB','Impulsos servidor'], limits: '' },
    ],
  },
  mattermost: {
    features_es: ['Mensajería de equipo auto-hospedada','Canales públicos y privados','Compartir archivos, voz y vídeo','Integraciones y webhooks','Playbooks para flujos de trabajo','Búsqueda avanzada de mensajes','Notificaciones personalizables','Aplicaciones de escritorio y móvil'],
    features_en: ['Self-hosted team messaging','Public and private channels','File sharing, voice and video','Integrations and webhooks','Playbooks for workflows','Advanced message search','Customizable notifications','Desktop and mobile apps'],
    pros_es: ['100% open source y auto-hospedada','Control total de tus datos','Altamente personalizable','Compatible con clientes y bots de Slack'],
    pros_en: ['100% open source and self-hosted','Full data control','Highly customizable','Compatible with Slack clients and bots'],
    cons_es: ['Requiere mantenimiento de servidor','Menos integraciones nativas que Slack','Comunidad más pequeña','Interfaz menos moderna que Discord'],
    cons_en: ['Requires server maintenance','Fewer native integrations than Slack','Smaller community','Less modern UI than Discord'],
    best_for_es: 'Empresas que necesitan mensajería privada, compliance y control de datos con capacidades similares a Slack.',
    best_for_en: 'Companies needing private messaging with compliance and data control, with Slack-like capabilities.',
    not_ideal_for_es: 'No para equipos pequeños que no pueden gestionar servidores o necesitan la máxima cantidad de integraciones.',
    not_ideal_for_en: 'Not for small teams that cannot manage servers or need the maximum number of integrations.',
    founded_year: 2015,
    integrations: ['GitHub','Jenkins','Jira','GitLab','Zapier','PagerDuty','Zoom','Webex'],
    screenshots: [],
    pricing_tiers: [
      { name: 'Free', price_monthly: 0, features: ['Canales ilimitados','Auto-hospedado','Plugins','Playbooks'], limits: '' },
      { name: 'Professional', price_monthly: 10, features: ['SSO SAML','LDAP','Soporte','Cumplimiento'], limits: 'Por usuario/mes' },
      { name: 'Enterprise', price_monthly: 30, features: ['Cifrado avanzado','Auditoría','Roles personalizados'], limits: 'Por usuario/mes' },
    ],
  },
  penpot: {
    features_es: ['Diseño vectorial y prototipado en navegador','Componentes y auto-layout','Librerías de design system','Colaboración multijugador en tiempo real','Flex layout basado en CSS','Inspección de código para desarrollo','Totalmente open source (sin límites)','Auto-hospedable o cloud'],
    features_en: ['Browser-based vector design and prototyping','Components and auto-layout','Design system libraries','Multiplayer real-time collaboration','CSS-based flex layout','Code inspection for development','Fully open source (no limits)','Self-hostable or cloud'],
    pros_es: ['Completamente gratuito y open source','Flex layout real basado en CSS','Sin límites artificiales','Exporta a SVG/PDF/PNG limpio'],
    pros_en: ['Completely free and open source','Real CSS-based flex layout','No artificial limits','Clean SVG/PDF/PNG export'],
    cons_es: ['Menos plugins que Figma','Comunidad más pequeña','Algunas funcionalidades en beta','Rendimiento inferior a Figma en archivos grandes'],
    cons_en: ['Fewer plugins than Figma','Smaller community','Some features still in beta','Lower performance on large files vs Figma'],
    best_for_es: 'Diseñadores y equipos que buscan la alternativa open source a Figma sin límites de precio ni funcionalidades.',
    best_for_en: 'Designers and teams seeking the open source Figma alternative with no price or feature limits.',
    not_ideal_for_es: 'No si necesitas plugins muy específicos de Figma, motion design avanzado o la máxima fluidez en archivos enormes.',
    not_ideal_for_en: 'Not if you need very specific Figma plugins, advanced motion design or maximum smoothness in huge files.',
    founded_year: 2020,
    integrations: ['GitHub','GitLab','Storybook'],
    screenshots: [],
    pricing_tiers: [
      { name: 'Gratis', price_monthly: 0, features: ['Todo ilimitado','Colaboración','Open source','Cloud o self-hosted'], limits: '' },
    ],
  },
  mailchimp: {
    features_es: ['Creador de emails drag-and-drop','Automatizaciones de marketing','Segmentación avanzada de audiencia','Landing pages y formularios','Analíticas de campañas','CRM de marketing integrado','Pruebas A/B','Recomendaciones de IA'],
    features_en: ['Drag-and-drop email builder','Marketing automations','Advanced audience segmentation','Landing pages and forms','Campaign analytics','Integrated marketing CRM','A/B testing','AI recommendations'],
    pros_es: ['Muy fácil de empezar','Plan gratuito para empezar','Gran biblioteca de templates','Buena analítica de campañas'],
    pros_en: ['Very easy to start','Free plan to get going','Great template library','Good campaign analytics'],
    cons_es: ['Se vuelve caro con listas grandes','Automatizaciones limitadas en plan bajo','Soporte lento en plan gratuito','Interfaz ha empeorado con rediseños'],
    cons_en: ['Gets expensive with large lists','Limited automations on lower plans','Slow support on free plan','UI has worsened with redesigns'],
    best_for_es: 'Principiantes en email marketing y pequeñas empresas que quieren empezar fácil y escalar con automatizaciones.',
    best_for_en: 'Email marketing beginners and small businesses wanting to start easy and scale with automations.',
    not_ideal_for_es: 'No para marketers avanzados que necesitan automatizaciones complejas o emails transaccionales robustos.',
    not_ideal_for_en: 'Not for advanced marketers needing complex automations or robust transactional emails.',
    founded_year: 2001,
    integrations: ['Shopify','WooCommerce','Salesforce','Canva','Stripe','WordPress','Zapier','Facebook'],
    screenshots: [],
    pricing_tiers: [
      { name: 'Gratis', price_monthly: 0, features: ['500 contactos','1,000 envíos/mes','Plantillas básicas'], limits: '500 contactos' },
      { name: 'Essentials', price_monthly: 13, features: ['500 contactos','5,000 envíos/mes','3 automatizaciones','A/B testing'], limits: '' },
      { name: 'Standard', price_monthly: 20, features: ['500 contactos','6,000 envíos/mes','10 automatizaciones','Segmentación avanzada'], limits: '' },
    ],
  },
  brevo: {
    features_es: ['Email marketing y newsletters','SMS marketing y WhatsApp','Chat en vivo para web','Automatización de marketing visual','CRM de ventas integrado','Landing pages y formularios','Pruebas A/B y segmentación','API potente y webhooks'],
    features_en: ['Email marketing and newsletters','SMS marketing and WhatsApp','Live web chat','Visual marketing automation','Integrated sales CRM','Landing pages and forms','A/B testing and segmentation','Powerful API and webhooks'],
    pros_es: ['Plan gratuito muy generoso (300 emails/día)','Incluye SMS y CRM sin coste extra','Basado en contactos, no en envíos','Interfaz moderna y rápida'],
    pros_en: ['Very generous free plan (300 emails/day)','Includes SMS and CRM at no extra cost','Contact-based, not email-based pricing','Modern fast interface'],
    cons_es: ['Menos templates que Mailchimp','Automatizaciones menos potentes','Soporte en español mejorable','Menos integraciones nativas'],
    cons_en: ['Fewer templates than Mailchimp','Less powerful automations','Customer support could improve','Fewer native integrations'],
    best_for_es: 'PYMES que quieren email marketing + SMS + CRM en una sola plataforma económica y con buen plan gratuito.',
    best_for_en: 'SMBs wanting email marketing + SMS + CRM in one affordable platform with a good free plan.',
    not_ideal_for_es: 'No para grandes corporaciones con necesidades de automatización muy complejas o multi-idioma avanzado.',
    not_ideal_for_en: 'Not for large corporations with very complex automation or advanced multilingual needs.',
    founded_year: 2012,
    integrations: ['Shopify','WooCommerce','WordPress','PrestaShop','Zapier','Salesforce','Google Analytics','Stripe'],
    screenshots: [],
    pricing_tiers: [
      { name: 'Gratis', price_monthly: 0, features: ['300 emails/día','Contactos ilimitados','Chat en vivo','SMS marketing'], limits: '300 emails/día' },
      { name: 'Starter', price_monthly: 25, features: ['20,000 emails/mes','Sin logo Brevo','Email soporte','Reporting avanzado'], limits: '' },
      { name: 'Business', price_monthly: 65, features: ['Automatización marketing','Pruebas A/B','Multi-usuario','API'], limits: '' },
    ],
  },
  zapier: {
    features_es: ['Conexión entre 7,000+ aplicaciones','Zaps automatizados sin código','Editor visual de flujos','Lógica condicional (Paths)','Formateo de datos y filtros','Multi-step Zaps complejos','App de escritorio y móvil','Transfer de datos masivos'],
    features_en: ['Connection between 7,000+ apps','No-code automated Zaps','Visual flow editor','Conditional logic (Paths)','Data formatting and filters','Complex multi-step Zaps','Desktop and mobile app','Bulk data transfers'],
    pros_es: ['La mayor biblioteca de integraciones','Muy fácil de usar para no técnicos','Plan gratuito funcional','Soporte de gran comunidad'],
    pros_en: ['Largest integration library','Very easy for non-technical users','Functional free plan','Large community support'],
    cons_es: ['Muy caro en planes altos','Cobran por tarea, no por flujo','Límites estrictos en plan gratuito','Sin verdadero entorno de pruebas'],
    cons_en: ['Very expensive on higher plans','Charges per task, not per flow','Strict limits on free plan','No true testing environment'],
    best_for_es: 'Cualquier persona o empresa que necesite conectar apps sin código, ideal para automatizaciones sencillas y medianas.',
    best_for_en: 'Anyone needing to connect apps without code, ideal for simple to medium automations.',
    not_ideal_for_es: 'No para automatizaciones con cientos de miles de tareas/mes (muy caro) o workflows muy complejos.',
    not_ideal_for_en: 'Not for automations with hundreds of thousands of tasks/month (too expensive) or very complex workflows.',
    founded_year: 2011,
    integrations: ['Slack','Gmail','Google Sheets','Trello','Shopify','HubSpot','Notion','Discord'],
    screenshots: [],
    pricing_tiers: [
      { name: 'Gratis', price_monthly: 0, features: ['100 tareas/mes','5 Zaps activos','Ejecución cada 15 min'], limits: '100 tareas/mes' },
      { name: 'Starter', price_monthly: 19.99, features: ['750 tareas/mes','20 Zaps activos','Multi-step Zaps','Paths'], limits: '' },
      { name: 'Professional', price_monthly: 49, features: ['2,000 tareas/mes','Zaps ilimitados','Filtros avanzados','App Transfer'], limits: '' },
    ],
  },
  make: {
    features_es: ['Automatización visual con escenarios','Editor drag-and-drop intuitivo','Ejecuciones en tiempo real o programadas','Ruteo condicional y filtros','Data stores y webhooks','Miles de módulos pre-construidos','Blueprints compartibles','API y funciones personalizadas'],
    features_en: ['Visual automation with scenarios','Intuitive drag-and-drop editor','Real-time or scheduled executions','Conditional routing and filters','Data stores and webhooks','Thousands of pre-built modules','Shareable blueprints','API and custom functions'],
    pros_es: ['Más potente y barato que Zapier','Editor visual excelente','Plan gratuito muy generoso (1,000 ops/mes)','Ruteo avanzado y transformaciones de datos'],
    pros_en: ['More powerful and cheaper than Zapier','Excellent visual editor','Very generous free plan (1,000 ops/month)','Advanced routing and data transformations'],
    cons_es: ['Curva de aprendizaje mayor','Menos integraciones (2,000 vs 7,000)','Documentación podría mejorar','Menos comunidad hispanohablante'],
    cons_en: ['Steeper learning curve','Fewer integrations (2,000 vs 7,000)','Documentation could improve','Smaller Spanish-speaking community'],
    best_for_es: 'Usuarios que necesitan automatizaciones más potentes y complejas que las de Zapier, con mejor relación calidad-precio.',
    best_for_en: 'Users needing more powerful complex automations than Zapier, with better value for money.',
    not_ideal_for_es: 'No si necesitas la máxima cantidad de integraciones pre-hechas o automatizaciones extremadamente simples.',
    not_ideal_for_en: 'Not if you need the maximum number of pre-built integrations or extremely simple automations.',
    founded_year: 2012,
    integrations: ['Google Workspace','Microsoft 365','Shopify','Slack','Discord','Trello','HubSpot','Airtable'],
    screenshots: [],
    pricing_tiers: [
      { name: 'Gratis', price_monthly: 0, features: ['1,000 ops/mes','Escenarios ilimitados','Ejecución cada 15 min','Editor visual'], limits: '1,000 ops/mes' },
      { name: 'Core', price_monthly: 9, features: ['10,000 ops/mes','Ejecución cada 1 min','Webhooks','Data stores'], limits: '' },
      { name: 'Pro', price_monthly: 16, features: ['50,000+ ops/mes','Ejecución instantánea','Blueprints','Funciones custom'], limits: '' },
    ],
  },
  n8n: {
    features_es: ['Automatización open source y auto-hospedada','Editor visual de workflows','350+ integraciones nativas','Ejecución local sin límites','API propia y webhooks','Código JavaScript personalizable','Ramas condicionales y merge','Versionado de workflows'],
    features_en: ['Open source self-hosted automation','Visual workflow editor','350+ native integrations','Unlimited local execution','Own API and webhooks','Customizable JavaScript code','Conditional branches and merge','Workflow versioning'],
    pros_es: ['100% open source y gratis (self-hosted)','Ejecuciones ilimitadas','Control total de tus datos','Editor visual muy intuitivo'],
    pros_en: ['100% open source and free (self-hosted)','Unlimited executions','Full data control','Very intuitive visual editor'],
    cons_es: ['Requiere servidor (o cloud de pago)','350 integraciones vs 7,000 de Zapier','Menos soporte y documentación','Actualizaciones pueden romper workflows'],
    cons_en: ['Requires a server (or paid cloud)','350 integrations vs 7,000 on Zapier','Less support and documentation','Updates can break workflows'],
    best_for_es: 'Equipos técnicos que necesitan automatizaciones potentes con control total, sin límites de precio y con código personalizado.',
    best_for_en: 'Technical teams needing powerful automations with full control, no price limits and custom code.',
    not_ideal_for_es: 'No para usuarios no técnicos que no pueden gestionar servidores o necesitan miles de integraciones pre-hechas.',
    not_ideal_for_en: 'Not for non-technical users who cannot manage servers or need thousands of pre-built integrations.',
    founded_year: 2019,
    integrations: ['GitHub','Slack','Discord','Telegram','Google Sheets','Postgres','MySQL','Stripe'],
    screenshots: [],
    pricing_tiers: [
      { name: 'Self-Hosted', price_monthly: 0, features: ['Ejecuciones ilimitadas','Workflows ilimitados','Todas las integraciones'], limits: 'Requiere servidor propio' },
      { name: 'Cloud Starter', price_monthly: 20, features: ['2,500 ejecuciones/mes','Hosting gestionado','Soporte comunitario'], limits: '2,500 ejecuciones' },
      { name: 'Cloud Pro', price_monthly: 120, features: ['10,000 ejecuciones/mes','Soporte dedicado','Multi-usuario','SSO'], limits: '' },
    ],
  },
  'google-analytics': {
    features_es: ['Analítica web gratuita de Google','Informes de tráfico en tiempo real','Análisis de conversiones y eventos','Segmentación avanzada de audiencia','Informes personalizables','Integración con Google Ads y Search Console','Machine Learning para insights','Exploraciones avanzadas (GA4)'],
    features_en: ['Free web analytics by Google','Real-time traffic reports','Conversion and event analysis','Advanced audience segmentation','Customizable reports','Google Ads and Search Console integration','Machine Learning insights','Advanced explorations (GA4)'],
    pros_es: ['Completamente gratis y potente','Integración total con ecosistema Google','Gran cantidad de datos y métricas','Informes personalizables'],
    pros_en: ['Completely free and powerful','Full Google ecosystem integration','Massive data and metrics','Customizable reports'],
    cons_es: ['Complejo de configurar (especialmente GA4)','Preocupaciones de privacidad','Datos muestreados en cuentas grandes','Curva de aprendizaje muy alta'],
    cons_en: ['Complex to set up (especially GA4)','Privacy concerns','Sampled data on large accounts','Very high learning curve'],
    best_for_es: 'Cualquier web que necesite analítica completa y gratuita, especialmente si ya usan Google Ads o Search Console.',
    best_for_en: 'Any website needing complete free analytics, especially if already using Google Ads or Search Console.',
    not_ideal_for_es: 'No si valoras la privacidad extrema, la simplicidad de uso o necesitas datos 100% precisos sin muestreo.',
    not_ideal_for_en: 'Not if you value extreme privacy, simplicity of use or need 100% accurate unsampled data.',
    founded_year: 2005,
    integrations: ['Google Ads','Google Search Console','Google Data Studio','BigQuery','Salesforce','Shopify','WordPress'],
    screenshots: [],
    pricing_tiers: [
      { name: 'Standard', price_monthly: 0, features: ['10M hits/mes','Informes estándar','Eventos ilimitados'], limits: '10M hits/mes' },
      { name: '360 (Enterprise)', price_monthly: 125000, features: ['Hits ilimitados','SLA','Soporte dedicado','BigQuery gratis'], limits: 'Anual' },
    ],
  },
  plausible: {
    features_es: ['Analítica web ligera y simple','Dashboard minimalista en tiempo real','Sin cookies, 100% GDPR compliant','Script de solo 1KB','Métricas esenciales: páginas, fuentes, países','Propiedad de datos 100% tuya','Informes por email programables','API abierta'],
    features_en: ['Lightweight simple web analytics','Minimalist real-time dashboard','Cookieless, 100% GDPR compliant','Only 1KB script','Essential metrics: pages, sources, countries','100% data ownership','Scheduled email reports','Open API'],
    pros_es: ['Privacidad total, sin cookies','Script ultraligero (1KB)','Dashboard súper simple y rápido','Open source y auto-hospedable'],
    pros_en: ['Total privacy, cookieless','Ultra-light 1KB script','Super simple fast dashboard','Open source and self-hostable'],
    cons_es: ['Solo métricas básicas','Sin mapas de calor ni grabaciones','De pago (9eur/mes mínimo)','Menos granularidad que GA'],
    cons_en: ['Only basic metrics','No heatmaps or recordings','Paid (9eur/month minimum)','Less granularity than GA'],
    best_for_es: 'Webs que priorizan privacidad, blogs, startups y proyectos que no necesitan analítica compleja.',
    best_for_en: 'Websites prioritizing privacy, blogs, startups and projects not needing complex analytics.',
    not_ideal_for_es: 'No si necesitas analítica avanzada (embudos, atribución multi-canal) o integraciones profundas con ads.',
    not_ideal_for_en: 'Not if you need advanced analytics (funnels, multi-channel attribution) or deep ad integrations.',
    founded_year: 2018,
    integrations: ['Google Search Console','Slack','WordPress','Ghost','API'],
    screenshots: [],
    pricing_tiers: [
      { name: 'Starter', price_monthly: 9, features: ['10,000 páginas vistas/mes','50 sitios','Sin límite de tiempo'], limits: '10k PV/mes' },
      { name: 'Growth', price_monthly: 19, features: ['100,000 páginas vistas/mes','50 sitios','Email reports'], limits: '' },
      { name: 'Business', price_monthly: 49, features: ['1M páginas vistas/mes','Soporte prioritario','API acceso'], limits: '' },
    ],
  },
  shopify: {
    features_es: ['Creador de tiendas drag-and-drop','100+ pasarelas de pago','Gestión de inventario avanzada','Temas y diseño responsive','App Store con 8,000+ apps','SEO optimizado para ecommerce','Informes de ventas y analytics','POS para tiendas físicas'],
    features_en: ['Drag-and-drop store builder','100+ payment gateways','Advanced inventory management','Responsive themes and design','App Store with 8,000+ apps','E-commerce optimized SEO','Sales reports and analytics','POS for physical stores'],
    pros_es: ['El más fácil de usar para ecommerce','8,000+ apps en la tienda','Hosting y seguridad incluidos','Excelente soporte 24/7'],
    pros_en: ['Easiest to use for ecommerce','8,000+ app store apps','Hosting and security included','Excellent 24/7 support'],
    cons_es: ['Comisiones por venta (2-3% si no usas Shopify Payments)','Costes mensuales se acumulan con apps','Personalización limitada del checkout','Dependencia total de Shopify'],
    cons_en: ['Transaction fees (2-3% without Shopify Payments)','Monthly costs add up with apps','Limited checkout customization','Full Shopify dependency'],
    best_for_es: 'Emprendedores y PYMES que quieren lanzar su tienda online rápido, sin preocuparse de hosting ni seguridad.',
    best_for_en: 'Entrepreneurs and SMBs wanting to launch their online store fast, without worrying about hosting or security.',
    not_ideal_for_es: 'No para tiendas con necesidades muy específicas de personalización o que quieran evitar comisiones por venta.',
    not_ideal_for_en: 'Not for stores with very specific customization needs or wanting to avoid per-sale transaction fees.',
    founded_year: 2006,
    integrations: ['Facebook','Instagram','TikTok','Google Ads','Mailchimp','Klaviyo','Oberlo','Printful'],
    screenshots: [],
    pricing_tiers: [
      { name: 'Basic', price_monthly: 25, features: ['Tienda online','Productos ilimitados','2 cuentas staff','SSL y hosting'], limits: '' },
      { name: 'Shopify', price_monthly: 69, features: ['5 cuentas staff','Informes profesionales','Tarifas envío con descuento'], limits: '' },
      { name: 'Advanced', price_monthly: 289, features: ['15 cuentas staff','Checkout personalizado','Tarifas mejoradas'], limits: '' },
    ],
  },
  woocommerce: {
    features_es: ['Plugin ecommerce gratuito para WordPress','Productos ilimitados y personalizables','Extensiones para cualquier funcionalidad','Pasarelas de pago: Stripe, PayPal, Redsys','Gestión de inventario y pedidos','SEO heredado de WordPress','Temas compatibles con miles de themes','Comunidad masiva y documentación'],
    features_en: ['Free ecommerce plugin for WordPress','Unlimited customizable products','Extensions for any functionality','Payment gateways: Stripe, PayPal, etc.','Inventory and order management','Inherited WordPress SEO','Thousands of compatible themes','Massive community and documentation'],
    pros_es: ['100% gratuito (plugin base)','Control total sobre tu tienda','Sin comisiones por venta','Infinitamente personalizable con plugins'],
    pros_en: ['100% free (base plugin)','Full control over your store','No per-sale commissions','Infinitely customizable with plugins'],
    cons_es: ['Requiere hosting y mantenimiento','Necesitas conocimientos de WordPress','Extensiones premium pueden ser caras','Rendimiento depende del hosting'],
    cons_en: ['Requires hosting and maintenance','Needs WordPress knowledge','Premium extensions can be expensive','Performance depends on hosting'],
    best_for_es: 'Usuarios de WordPress que quieren ecommerce con control total y sin comisiones, dispuestos a gestionar su hosting.',
    best_for_en: 'WordPress users wanting ecommerce with full control and no commissions, willing to manage their own hosting.',
    not_ideal_for_es: 'No para quien no quiera gestionar hosting o necesite una solución todo en uno sin configuraciones técnicas.',
    not_ideal_for_en: 'Not for those unwilling to manage hosting or needing an all-in-one solution without technical setup.',
    founded_year: 2011,
    integrations: ['Stripe','PayPal','Redsys','SEUR','Mailchimp','Google Analytics','Facebook','Amazon Pay'],
    screenshots: [],
    pricing_tiers: [
      { name: 'Gratis', price_monthly: 0, features: ['Plugin base','Productos ilimitados','Gestión pedidos','Pasarelas básicas'], limits: 'Requiere hosting' },
      { name: 'Extensiones', price_monthly: 79, features: ['Subscripciones','Bookings','Memberships','Envíos avanzados'], limits: 'Pago anual por extensión' },
    ],
  },
  'zoho-crm': {
    features_es: ['CRM completo con IA (Zia)','Gestión de leads y pipeline','Automatización de ventas y marketing','Email integrado y plantillas','Informes y dashboards personalizables','Portal de clientes','App móvil completa','Suite de apps Zoho integrada'],
    features_en: ['Complete CRM with AI (Zia)','Lead and pipeline management','Sales and marketing automation','Integrated email and templates','Customizable reports and dashboards','Customer portal','Full mobile app','Integrated Zoho app suite'],
    pros_es: ['Excelente relación calidad-precio','Plan gratuito funcional','Suite completa de apps (50+ herramientas)','Buena automatización y personalización'],
    pros_en: ['Excellent value for money','Functional free plan','Complete app suite (50+ tools)','Good automation and customization'],
    cons_es: ['Interfaz puede ser abrumadora','Soporte en español limitado','Curva de aprendizaje con tantas apps','Integraciones externas limitadas'],
    cons_en: ['Interface can be overwhelming','Limited Spanish support','Learning curve with so many apps','Limited external integrations'],
    best_for_es: 'PYMES que buscan un CRM económico con muchas funcionalidades y que pueden aprovechar el ecosistema Zoho.',
    best_for_en: 'SMBs seeking an affordable CRM with many features and who can leverage the Zoho ecosystem.',
    not_ideal_for_es: 'No si tu equipo usa muchas herramientas fuera de Zoho y necesitas integraciones profundas con ellas.',
    not_ideal_for_en: 'Not if your team uses many non-Zoho tools and needs deep integrations with them.',
    founded_year: 2005,
    integrations: ['Google Workspace','Microsoft 365','Slack','Mailchimp','QuickBooks','Shopify','WordPress','Zapier'],
    screenshots: [],
    pricing_tiers: [
      { name: 'Gratis', price_monthly: 0, features: ['3 usuarios','Leads y contactos','Flujos básicos'], limits: '3 usuarios' },
      { name: 'Standard', price_monthly: 14, features: ['Automatización','Informes','Email marketing','Reglas scoring'], limits: 'Por usuario/mes' },
      { name: 'Professional', price_monthly: 23, features: ['SalesSignals','Blueprints','Validaciones','Webhooks'], limits: 'Por usuario/mes' },
    ],
  },
  holded: {
    features_es: ['Facturación y contabilidad integradas','Gestión de inventario y almacén','CRM y pipeline de ventas','Gestión de proyectos y tareas','Control horario de empleados','Conciliación bancaria automática','Informes financieros y dashboards','App móvil para gestión'],
    features_en: ['Integrated invoicing and accounting','Inventory and warehouse management','CRM and sales pipeline','Project and task management','Employee time tracking','Automatic bank reconciliation','Financial reports and dashboards','Mobile management app'],
    pros_es: ['ERP completo hecho en España','Interfaz moderna y fácil de usar','Perfecto para facturación fiscal española','Buen soporte en español'],
    pros_en: ['Complete ERP made in Spain','Modern easy-to-use interface','Perfect for Spanish tax invoicing','Good Spanish-language support'],
    cons_es: ['Más caro que alternativas básicas','Sin plan gratuito real (solo demo)','Integraciones limitadas fuera de España','Algunas funcionalidades aún madurando'],
    cons_en: ['More expensive than basic alternatives','No real free plan (demo only)','Limited integrations outside Spain','Some features still maturing'],
    best_for_es: 'PYMES y autónomos españoles que necesitan facturación, contabilidad y gestión en una sola plataforma.',
    best_for_en: 'Spanish SMBs and freelancers needing invoicing, accounting and management in one platform.',
    not_ideal_for_es: 'No para empresas multinacionales con necesidades multi-país complejas o que buscan una solución gratuita.',
    not_ideal_for_en: 'Not for multinationals with complex multi-country needs or those seeking a free solution.',
    founded_year: 2016,
    integrations: ['Amazon','eBay','PrestaShop','Shopify','WooCommerce','PayPal','Stripe','Bizum'],
    screenshots: [],
    pricing_tiers: [
      { name: 'Starter', price_monthly: 15, features: ['Facturación','CRM básico','Proyectos simple','Informes'], limits: '1 usuario' },
      { name: 'Advanced', price_monthly: 30, features: ['Contabilidad','Inventario','Control horario','Múltiples usuarios'], limits: '' },
      { name: 'Enterprise', price_monthly: 60, features: ['API avanzada','Personalización','Soporte dedicado'], limits: '' },
    ],
  },
}

// Helper para obtener contenido extendido de una herramienta, con fallback a defaults
export function getToolContent(slug: string): ToolContent {
  return toolContent[slug] || {
    features_es: [], features_en: [], pros_es: [], pros_en: [],
    cons_es: [], cons_en: [], best_for_es: '', best_for_en: '',
    not_ideal_for_es: '', not_ideal_for_en: '', founded_year: null,
    integrations: [], screenshots: [], pricing_tiers: [],
  }
}

export function getToolContentKeys(): string[] {
  return Object.keys(toolContent)
}
