import { readFileSync, writeFileSync } from 'fs'

const SEED_PATH = 'src/lib/seed-data.ts'

// Quick-add: append 120 new tools to the existing 180 tools
// Skip logo/pricing fixes since they're already applied

const cb = (d) => `https://logo.clearbit.com/${d}`
let toolNum = 180

function add(cat, slug, name, descEs, descEn, pm, ps, rating, os, tags, web, website) {
  toolNum++
  const domain = web || website?.replace('https://','')?.split('/')[0]
  return {
    id: `tool-${toolNum}`, slug, name,
    logo_url: cb(domain),
    description_es: descEs, description_en: descEn,
    category_id: cat, price_model: pm, price_starting: ps,
    website_url: website || `https://${domain}`, affiliate_url: null,
    rating_g2: rating, rating_capterra: null,
    is_open_source: os || false, is_verified: false, listing_tier: 'free',
    tags: tags || [], alternatives: []
  }
}

const tools = [
  // RRHH cat-9 (30)
  add('cat-9','bamboohr','BambooHR','HRIS para pymes: gestion de empleados, onboarding, vacaciones, informes y firma electronica.','HRIS for SMBs: employee management, onboarding, time-off, reports and e-signatures.','paid',5.75,4.3,false,['hris','pymes','empleados','onboarding'],'bamboohr.com'),
  add('cat-9','workday','Workday','Suite enterprise de RRHH y finanzas. Gestion de talento, nominas, planificacion y analytics en la nube.','Enterprise HR and finance suite. Talent management, payroll, planning and cloud analytics.','paid',99,4.2,false,['enterprise','hcm','finanzas','nomina'],'workday.com'),
  add('cat-9','personio','Personio','HRIS europeo para pymes. Gestion de empleados, reclutamiento, nominas y control horario.','European HRIS for SMBs. Employee management, recruiting, payroll and time tracking.','paid',4.9,4.5,false,['hris','europeo','pymes','reclutamiento'],'personio.com'),
  add('cat-9','factorial','Factorial','Software de RRHH espanol. Ausencias, turnos, nominas, gastos, onboarding y evaluaciones.','Spanish HR software. Absences, shifts, payroll, expenses, onboarding and reviews.','paid',4.5,4.3,false,['rrhh','espanol','pymes','nomina'],'factorialhr.com'),
  add('cat-9','payfit','PayFit','Gestion de nominas y RRHH automatizada. Calculo fiscal, declaraciones y portal del empleado.','Automated payroll and HR. Tax calculation, declarations and employee portal.','paid',8,4.3,false,['nomina','rrhh','automatizacion','pymes'],'payfit.com'),
  add('cat-9','deel','Deel','Contratacion global con compliance en 150+ paises. EOR, payroll, equity y relocation.','Global hiring with compliance in 150+ countries. EOR, payroll, equity and relocation.','freemium',49,4.7,false,['contratacion-global','eor','nomina','remoto'],'deel.com'),
  add('cat-9','remote-com','Remote','Plataforma de empleo global. EOR, payroll internacional y gestion de equipos distribuidos.','Global employment platform. EOR, international payroll and distributed team management.','paid',299,4.5,false,['remoto','global','eor','equipos-distribuidos'],'remote.com'),
  add('cat-9','rippling','Rippling','Gestion unificada de empleados, IT y finanzas. Onboarding, payroll, dispositivos y apps.','Unified employee, IT and finance management. Onboarding, payroll, devices and apps.','paid',8,4.7,false,['rrhh','it','finanzas','todo-en-uno'],'rippling.com'),
  add('cat-9','gusto','Gusto','Nominas, beneficios y RRHH para pymes USA. Automatizacion fiscal, seguros y onboarding.','Payroll, benefits and HR for US SMBs. Tax automation, insurance and onboarding.','paid',40,4.6,false,['nomina','pymes','usa','beneficios'],'gusto.com'),
  add('cat-9','lever','Lever','ATS y CRM de reclutamiento. Sourcing, entrevistas, ofertas y analytics de contratacion.','Recruiting ATS and CRM. Sourcing, interviews, offers and hiring analytics.','paid',500,4.3,false,['reclutamiento','ats','crm','contratacion'],'lever.co'),
  add('cat-9','greenhouse','Greenhouse','Plataforma de contratacion enterprise. Structured hiring, DEI, entrevistas y onboarding.','Enterprise hiring platform. Structured hiring, DEI, interviews and onboarding.','paid',1000,4.5,false,['reclutamiento','enterprise','dei','contratacion'],'greenhouse.io'),
  add('cat-9','workable','Workable','Software de reclutamiento con IA. Publicacion multi-job board, sourcing y evaluacion.','AI recruiting software. Multi-job board posting, sourcing and evaluation.','paid',149,4.5,false,['reclutamiento','ats','ia','sourcing'],'workable.com'),
  add('cat-9','breezyhr','Breezy HR','ATS visual con pipeline drag-and-drop. Career site, video entrevistas y automatizaciones.','Visual ATS with drag-and-drop pipeline. Career site, video interviews and automations.','freemium',143,4.4,false,['reclutamiento','ats','visual','automatizacion'],'breezy.hr'),
  add('cat-9','homerun','Homerun','Software de reclutamiento con career page integrada. Publicacion de ofertas y gestion de candidatos.','Recruiting software with integrated career page. Job posting and candidate management.','paid',69,4.6,false,['reclutamiento','career-page','pymes','sencillo'],'homerun.co'),
  add('cat-9','teamtailor','Teamtailor','ATS con employer branding integrado. Career site, referidos y experiencia del candidato.','ATS with integrated employer branding. Career site, referrals and candidate experience.','paid',500,4.6,false,['reclutamiento','employer-branding','ats','experiencia-candidato'],'teamtailor.com'),
  add('cat-9','zohopeople','Zoho People','HRIS en la suite Zoho. Gestion de empleados, tiempo, permisos, evaluaciones y formacion.','HRIS in the Zoho suite. Employee, time, leave, performance and training management.','freemium',1,4.2,false,['hris','zoho','empleados','formacion'],'zoho.com/people'),
  add('cat-9','bizneo','Bizneo HR','Suite de RRHH espanola. ATS, control horario, evaluaciones, encuestas y people analytics.','Spanish HR suite. ATS, time tracking, reviews, surveys and people analytics.','paid',3,4.4,false,['rrhh','espanol','ats','control-horario'],'bizneo.com'),
  add('cat-9','sesamehr','Sesame HR','Software de RRHH para digitalizar procesos. Fichajes, vacaciones, evaluaciones y documentos.','HR software to digitize processes. Time clock, vacations, reviews and documents.','paid',3.5,4.4,false,['rrhh','digitalizacion','fichajes','evaluaciones'],'sesamehr.com'),
  add('cat-9','kenjo','Kenjo','HRIS todo en uno. Control horario, turnos, nominas, reclutamiento y people analytics.','All-in-one HRIS. Time tracking, shifts, payroll, recruiting and people analytics.','paid',4,4.3,false,['hris','todo-en-uno','control-horario','nomina'],'kenjo.io'),
  add('cat-9','culture-amp','Culture Amp','Plataforma de employee experience. Engagement, performance, desarrollo y people analytics.','Employee experience platform. Engagement, performance, development and people analytics.','paid',5,4.6,false,['engagement','performance','people-analytics','desarrollo'],'cultureamp.com'),
  add('cat-9','lattice','Lattice','Gestion del rendimiento y OKRs. Evaluaciones, feedback 360, 1:1s y objetivos.','Performance management and OKRs. Reviews, 360 feedback, 1:1s and goals.','paid',11,4.6,false,['performance','okrs','feedback','evaluaciones'],'lattice.com'),
  add('cat-9','15five','15Five','Plataforma de performance management. Check-ins semanales, OKRs, feedback y reconocimiento.','Performance management platform. Weekly check-ins, OKRs, feedback and recognition.','paid',8,4.5,false,['performance','okrs','check-ins','feedback'],'15five.com'),
  add('cat-9','leapsome','Leapsome','Plataforma de people enablement. Evaluaciones, OKRs, engagement, feedback y learning.','People enablement platform. Reviews, OKRs, engagement, feedback and learning.','paid',8,4.7,false,['performance','okrs','engagement','evaluaciones'],'leapsome.com'),
  add('cat-9','bobhr','Bob','Plataforma HR moderna. Core HR, cultura, performance, payroll y workforce planning.','Modern HR platform. Core HR, culture, performance, payroll and workforce planning.','paid',7,4.6,false,['rrhh','moderno','cultura','planificacion'],'hibob.com'),
  add('cat-9','charliehr','CharlieHR','HRIS simple para startups y pymes. Onboarding, ausencias, review cycles y perks.','Simple HRIS for startups and SMBs. Onboarding, absences, review cycles and perks.','freemium',6,4.5,false,['hris','startups','simple','pymes'],'charliehr.com'),
  add('cat-9','breathehr','Breathe HR','HR software para pymes UK. Gestion de empleados, ausencias, gastos y performance.','HR software for UK SMBs. Employee, absences, expenses and performance management.','paid',14,4.3,false,['rrhh','pymes','uk','gastos'],'breathehr.com'),
  add('cat-9','humaans','Humaans','HRIS moderno y visual. Onboarding, ausencias, directorio, reporting y documentos centralizados.','Modern visual HRIS. Onboarding, absences, directory, reporting and centralized documents.','paid',5,4.6,false,['hris','moderno','visual','onboarding'],'humaans.io'),
  add('cat-9','clearcompany','ClearCompany','Plataforma de gestion del talento. ATS, onboarding, performance, engagement y analytics.','Talent management platform. ATS, onboarding, performance, engagement and analytics.','paid',6,4.3,false,['talento','ats','onboarding','performance'],'clearcompany.com'),
  add('cat-9','homerun-co','Homerun','Software de reclutamiento con career page integrada. Publicacion de ofertas y gestion de candidatos.','Recruiting software with integrated career page. Job posting and candidate management.','paid',69,4.6,false,['reclutamiento','career-page','pymes'],'homerun.co'),
  add('cat-9','trabrh-blue','TrabHR','Portal del empleado y software de beneficios. Gestion de tickets, comunicaciones y clima laboral.','Employee portal and benefits software. Ticket management, communications and workplace surveys.','paid',2,4.0,false,['rrhh','portal-empleado','beneficios','encuestas'],'grupocastilla.es'),

  // CMS cat-17 (30)
  add('cat-17','wordpress','WordPress','El CMS mas popular del mundo. 43% de la web. Temas, plugins, ecommerce y comunidad masiva.','The most popular CMS. 43% of the web. Themes, plugins, ecommerce and massive community.','free',0,4.3,true,['cms','open-source','blog','ecommerce'],'wordpress.org'),
  add('cat-17','webflow','Webflow','CMS visual con disenador web profesional. HTML/CSS sin codigo, CMS dinamico y hosting integrado.','Visual CMS with professional web designer. No-code HTML/CSS, dynamic CMS and integrated hosting.','freemium',14,4.4,false,['cms','visual','nocode','hosting'],'webflow.com'),
  add('cat-17','wix','Wix','Creador de webs drag-and-drop con IA. Templates, ecommerce, SEO, blog y app market.','Drag-and-drop website builder with AI. Templates, ecommerce, SEO, blog and app market.','freemium',16,4.2,false,['cms','drag-drop','nocode','ecommerce'],'wix.com'),
  add('cat-17','squarespace','Squarespace','CMS con diseno premium todo en uno. Plantillas elegantes, ecommerce, blog, SEO y analytics.','All-in-one premium design CMS. Elegant templates, ecommerce, blog, SEO and analytics.','paid',16,4.4,false,['cms','diseno','templates','ecommerce'],'squarespace.com'),
  add('cat-17','ghost','Ghost','CMS open source para publicaciones profesionales. Blogging, newsletters, memberships y suscripciones.','Open source CMS for professional publishing. Blogging, newsletters, memberships and subscriptions.','freemium',9,4.5,true,['cms','blog','newsletter','open-source'],'ghost.org'),
  add('cat-17','medium','Medium','Plataforma de blogging social. Publica articulos, gana con el Partner Program y construye audiencia.','Social blogging platform. Publish articles, earn with Partner Program and build audience.','free',0,4.0,false,['blog','publicacion','audiencia','red-social'],'medium.com'),
  add('cat-17','substack','Substack','Plataforma de newsletters y publicaciones de pago. Monetiza tu audiencia con suscripciones.','Newsletter and paid publication platform. Monetize your audience with subscriptions.','freemium',0,4.2,false,['newsletter','suscripcion','monetizacion','publicacion'],'substack.com'),
  add('cat-17','beehiiv','Beehiiv','Plataforma de newsletters con IA. Crecimiento, monetizacion, referidos y analytics avanzados.','AI newsletter platform. Growth, monetization, referrals and advanced analytics.','freemium',39,4.4,false,['newsletter','ia','crecimiento','monetizacion'],'beehiiv.com'),
  add('cat-17','convertkit','Kit','Email marketing para creadores. Automatizaciones, landing pages, commerce y comunidad.','Email marketing for creators. Automations, landing pages, commerce and community.','freemium',15,4.5,false,['email','creadores','newsletter','automatizacion'],'kit.com'),
  add('cat-17','strapi','Strapi','CMS headless open source lider. APIs REST/GraphQL, admin personalizable y plugins marketplace.','Leading open source headless CMS. REST/GraphQL APIs, customizable admin and plugin marketplace.','freemium',99,4.7,true,['headless-cms','open-source','api','javascript'],'strapi.io'),
  add('cat-17','contentful','Contentful','CMS headless enterprise. Content modeling, APIs, previews, localization y app framework.','Enterprise headless CMS. Content modeling, APIs, previews, localization and app framework.','freemium',300,4.4,false,['headless-cms','enterprise','api','localization'],'contentful.com'),
  add('cat-17','sanity','Sanity','CMS headless con real-time collaboration. Structured content, APIs, GROQ query y personalizacion total.','Headless CMS with real-time collaboration. Structured content, APIs, GROQ query and full customization.','freemium',99,4.5,false,['headless-cms','colaboracion','api','customizable'],'sanity.io'),
  add('cat-17','drupal','Drupal','CMS open source enterprise con seguridad avanzada. Sites complejos, gobierno y multilenguaje.','Enterprise open source CMS with advanced security. Complex sites, governance and multilingual.','free',0,4.0,true,['cms','enterprise','open-source','seguridad'],'drupal.org'),
  add('cat-17','joomla','Joomla','CMS open source flexible con 8000+ extensiones. Multilingue nativo, ACL avanzado y templates.','Flexible open source CMS with 8000+ extensions. Native multilingual, advanced ACL and templates.','free',0,3.9,true,['cms','open-source','multilingue','extensiones'],'joomla.org'),
  add('cat-17','hashnode','Hashnode','Plataforma de blogging para developers. Blog personalizado, dominio propio y comunidad de devs.','Blogging platform for developers. Custom blog, own domain and developer community.','free',0,4.6,false,['blog','desarrolladores','dev','comunidad'],'hashnode.com'),
  add('cat-17','datocms','DatoCMS','CMS headless con interfaz visual y modular. Content modeling, APIs GraphQL y previews en tiempo real.','Headless CMS with visual modular interface. Content modeling, GraphQL APIs and real-time previews.','freemium',149,4.6,false,['headless-cms','visual','graphql','modular'],'datocms.com'),
  add('cat-17','prismic','Prismic','CMS headless con Slices. Componentes de contenido reutilizables, previews y programador de publicaciones.','Headless CMS with Slices. Reusable content components, previews and publication scheduler.','freemium',100,4.5,false,['headless-cms','slices','componentes','previews'],'prismic.io'),
  add('cat-17','buttercms','ButterCMS','CMS headless con motor de blog potente. API-first, SEO optimizado y facil integracion.','Headless CMS with powerful blog engine. API-first, SEO optimized and easy integration.','freemium',83,4.4,false,['headless-cms','blog','api','seo'],'buttercms.com'),
  add('cat-17','hygraph','Hygraph','CMS headless con GraphQL nativo. Content federation, localization, workflows y componentes.','Headless CMS with native GraphQL. Content federation, localization, workflows and components.','freemium',299,4.5,false,['headless-cms','graphql','localization','workflows'],'hygraph.com'),
  add('cat-17','kirby','Kirby','CMS flat-file sin base de datos. Rapido, flexible, sin panel de admin complejo y basado en archivos.','Flat-file CMS without database. Fast, flexible, no complex admin panel and file-based.','paid',99,4.5,false,['cms','flat-file','rapido','flexible'],'getkirby.com'),
  add('cat-17','craftcms','Craft CMS','CMS flexible y potente con control total. Custom fields, Matrix, GraphQL y ecosistema de plugins.','Flexible powerful CMS with full control. Custom fields, Matrix, GraphQL and plugin ecosystem.','freemium',299,4.5,false,['cms','flexible','custom-fields','plugins'],'craftcms.com'),
  add('cat-17','statamic','Statamic','CMS flat-file moderno basado en Laravel. Sin BBDD, control de versiones Git y markdown.','Modern flat-file CMS based on Laravel. No database, Git versioning and markdown.','freemium',259,4.6,false,['cms','flat-file','laravel','git'],'statamic.com'),
  add('cat-17','hugo','Hugo','Generador de sitios estaticos ultrarrapido en Go. Markdown, temas y build en milisegundos.','Ultra-fast static site generator in Go. Markdown, themes and millisecond builds.','free',0,4.6,true,['static-site','go','markdown','rapido'],'gohugo.io'),
  add('cat-17','jekyll','Jekyll','Generador de sitios estaticos en Ruby. Motor de GitHub Pages, simple y con gran comunidad.','Static site generator in Ruby. GitHub Pages engine, simple with great community.','free',0,4.4,true,['static-site','ruby','github-pages','simple'],'jekyllrb.com'),
  add('cat-17','astro','Astro','Framework web moderno para contenido. Zero JS por defecto, islas de interactividad y multi-framework.','Modern web framework for content. Zero JS by default, islands of interactivity and multi-framework.','free',0,4.7,true,['framework','static-site','optimizado','multi-framework'],'astro.build'),
  add('cat-17','nextjs','Next.js','Framework React con SSR, SSG e ISR. App Router, server components y optimizacion de imagenes.','React framework with SSR, SSG and ISR. App Router, server components and image optimization.','free',0,4.6,true,['framework','react','ssr','vercel'],'nextjs.org'),
  add('cat-17','headless-wordpress','Headless WP','WordPress como CMS headless con REST API y WPGraphQL. Backend familiar para editores con frontend moderno.','WordPress as headless CMS with REST API and WPGraphQL. Familiar backend for editors with modern frontend.','free',0,4.5,true,['headless-cms','wordpress','api','graphql'],'wordpress.org'),
  add('cat-17','directus','Directus','CMS headless open source con admin dinamico. APIs REST/GraphQL, autenticacion y flujos de trabajo.','Open source headless CMS with dynamic admin. REST/GraphQL APIs, auth and workflows.','free',0,4.6,true,['headless-cms','open-source','api','admin'],'directus.io'),
  add('cat-17','payloadcms','Payload CMS','CMS headless open source con admin React. TypeScript nativo, GraphQL/REST APIs y control de acceso.','Open source headless CMS with React admin. Native TypeScript, GraphQL/REST APIs and access control.','free',0,4.6,true,['headless-cms','open-source','typescript','react'],'payloadcms.com'),
  add('cat-17','notion-cms','Notion CMS','Usa Notion como CMS headless. APIs para contenido, bases de datos y paginas con frameworks modernos.','Use Notion as a headless CMS. APIs for content, databases and pages with modern frameworks.','freemium',10,4.7,false,['headless-cms','notion','api','nocode'],'notion.so'),
]

// Rest of tools: BBDD, Legal
const more = [
  // BBDD cat-19 (30)
  add('cat-19','mysql','MySQL','La base de datos open source mas popular. Relacional, ACID, escalable y con enorme comunidad.','The most popular open source database. Relational, ACID, scalable with huge community.','free',0,4.4,true,['sql','relacional','open-source','web'],'mysql.com'),
  add('cat-19','mariadb','MariaDB','Fork de MySQL con mejoras de rendimiento y open source garantizado. Plugins de almacenamiento avanzados.','MySQL fork with performance improvements and guaranteed open source. Advanced storage plugins.','free',0,4.3,true,['sql','relacional','open-source','performance'],'mariadb.org'),
  add('cat-19','sqlite','SQLite','Base de datos SQL embebida, ligera y sin servidor. Usada en moviles, navegadores y apps de escritorio.','Embedded lightweight serverless SQL database. Used in mobile, browsers and desktop apps.','free',0,4.5,true,['sql','embebido','ligero','movil'],'sqlite.org'),
  add('cat-19','cockroachdb','CockroachDB','Base de datos SQL distribuida con consistencia fuerte. Escalado horizontal, multi-region y survivability.','Distributed SQL database with strong consistency. Horizontal scaling, multi-region and survivability.','freemium',0,4.4,true,['sql','distribuido','escalable','cloud-native'],'cockroachlabs.com'),
  add('cat-19','timescaledb','TimescaleDB','PostgreSQL optimizado para series temporales. Hypertables, compresion nativa, continuous aggregates.','PostgreSQL optimized for time-series. Hypertables, native compression, continuous aggregates.','freemium',0,4.5,true,['time-series','postgresql','open-source','analitica'],'timescale.com'),
  add('cat-19','cassandra','Cassandra','Base de datos NoSQL distribuida con alta disponibilidad. Linealmente escalable, multi-datacenter, sin SPOF.','Distributed NoSQL database with high availability. Linearly scalable, multi-datacenter, no SPOF.','free',0,4.0,true,['nosql','distribuido','alta-disponibilidad','big-data'],'cassandra.apache.org'),
  add('cat-19','redis','Redis','Almacen de datos en memoria ultrarrapido. Cache, colas, pub/sub, streams, busqueda y vector DB.','Ultra-fast in-memory data store. Cache, queues, pub/sub, streams, search and vector DB.','freemium',0,4.6,true,['cache','in-memory','pub-sub','vector-db'],'redis.io'),
  add('cat-19','dynamodb','DynamoDB','Base de datos NoSQL serverless de AWS. Escalado automatico, rendimiento predecible y eventos.','AWS serverless NoSQL database. Auto-scaling, predictable performance and events.','freemium',0,4.4,false,['nosql','serverless','aws','escalado'],'aws.amazon.com/dynamodb'),
  add('cat-19','fauna','Fauna','Base de datos transaccional serverless con GraphQL nativo. ACID global sin operaciones manuales.','Serverless transactional database with native GraphQL. Global ACID without manual operations.','freemium',0,4.3,false,['serverless','graphql','transaccional','global'],'fauna.com'),
  add('cat-19','couchbase','Couchbase','Plataforma de base de datos NoSQL con SQL flexible. Cache, busqueda full-text, eventos y analytics.','NoSQL database platform with flexible SQL. Cache, full-text search, events and analytics.','freemium',0,4.3,false,['nosql','cache','multi-modelo','analytics'],'couchbase.com'),
  add('cat-19','meilisearch','Meilisearch','Motor de busqueda open source ultrarrapido. Tolerancia tipografica, filtros, facets y API REST simple.','Ultra-fast open source search engine. Typo tolerance, filters, facets and simple REST API.','freemium',0,4.7,true,['busqueda','open-source','api','full-text'],'meilisearch.com'),
  add('cat-19','typesense','Typesense','Motor de busqueda open source tolerante a errores. Rapido, facil de configurar y con relevancia instantanea.','Open source typo-tolerant search engine. Fast, easy to configure with instant relevance.','freemium',0,4.6,true,['busqueda','open-source','rapido','tolerancia-errores'],'typesense.org'),
  add('cat-19','algolia','Algolia','Plataforma de busqueda como servicio. Busqueda instantanea, AI search, recomendaciones y analytics.','Search-as-a-service platform. Instant search, AI search, recommendations and analytics.','freemium',0,4.4,false,['busqueda','saas','ia','recomendaciones'],'algolia.com'),
  add('cat-19','elasticsearch','Elasticsearch','Motor de busqueda y analytics distribuido. Full-text, agregaciones, machine learning y observability.','Distributed search and analytics engine. Full-text, aggregations, machine learning and observability.','freemium',0,4.3,true,['busqueda','analytics','distribuido','logs'],'elastic.co'),
  add('cat-19','qdrant','Qdrant','Base de datos vectorial open source para IA. Busqueda semantica, recomendaciones y RAG en produccion.','Open source vector database for AI. Semantic search, recommendations and production RAG.','freemium',0,4.7,true,['vector-db','ia','open-source','rag'],'qdrant.tech'),
  add('cat-19','pinecone','Pinecone','Base de datos vectorial serverless. Busqueda semantica, RAG, embeddings y escalado automatico.','Serverless vector database. Semantic search, RAG, embeddings and auto-scaling.','freemium',0,4.6,false,['vector-db','serverless','ia','semantica'],'pinecone.io'),
  add('cat-19','weaviate','Weaviate','Base de datos vectorial open source con GraphQL. Busqueda hibrida, multimodal y generative search.','Open source vector database with GraphQL. Hybrid search, multimodal and generative search.','freemium',0,4.6,true,['vector-db','open-source','graphql','multimodal'],'weaviate.io'),
  add('cat-19','chroma','Chroma','Base de datos vectorial open source para IA. Embeddings API, simple de usar y disenada para developers.','Open source vector database for AI. Embeddings API, simple to use and designed for developers.','free',0,4.5,true,['vector-db','open-source','ia','embeddings'],'trychroma.com'),
  add('cat-19','milvus','Milvus','Base de datos vectorial open source cloud-native. Escalable, indices avanzados y SDK multi-lenguaje.','Cloud-native open source vector database. Scalable, advanced indexes and multi-language SDK.','free',0,4.4,true,['vector-db','open-source','cloud-native','escalable'],'milvus.io'),
  add('cat-19','neo4j','Neo4j','Base de datos de grafos lider. Consultas Cypher, analisis de relaciones y graph data science.','Leading graph database. Cypher queries, relationship analysis and graph data science.','freemium',0,4.4,false,['grafos','nosql','cypher','analisis-conexiones'],'neo4j.com'),
  add('cat-19','influxdb','InfluxDB','Base de datos de series temporales optimizada. Alta ingesta, queries SQL-like, dashboards y alertas.','Optimized time-series database. High ingestion, SQL-like queries, dashboards and alerts.','freemium',0,4.3,true,['time-series','monitorizacion','iot','analitica'],'influxdata.com'),
  add('cat-19','clickhouse','ClickHouse','Base de datos OLAP columnar ultrarrapida. Queries analiticas en tiempo real sobre petabytes de datos.','Ultra-fast columnar OLAP database. Real-time analytical queries over petabytes of data.','freemium',0,4.5,true,['olap','analitica','columnar','big-data'],'clickhouse.com'),
  add('cat-19','snowflake','Snowflake','Data warehouse cloud nativo con separacion compute-storage. SQL, data sharing y marketplace de datos.','Cloud-native data warehouse with compute-storage separation. SQL, data sharing and data marketplace.','paid',2,4.3,false,['data-warehouse','cloud','sql','analytics'],'snowflake.com'),
  add('cat-19','duckdb','DuckDB','Base de datos OLAP embebida tipo SQLite para analytics. Ejecuta queries complejas directamente en archivos.','Embedded OLAP database like SQLite for analytics. Run complex queries directly on files.','free',0,4.6,true,['olap','embebido','analitica','open-source'],'duckdb.org'),
  add('cat-19','postgresql','PostgreSQL','La base de datos relacional open source mas avanzada. Extensible, ACID, JSON, full-text y GIS nativo.','The most advanced open source relational database. Extensible, ACID, JSON, full-text and native GIS.','free',0,4.6,true,['sql','relacional','open-source','avanzado'],'postgresql.org'),
  add('cat-19','singlestore','SingleStore','Base de datos SQL distribuida para transacciones + analytics. Latencia de milisegundos a escala masiva.','Distributed SQL database for transactions + analytics. Millisecond latency at massive scale.','freemium',500,4.3,false,['sql','distribuido','htap','analytics'],'singlestore.com'),
  add('cat-19','tidb','TiDB','Base de datos SQL distribuida open source. Compatible con MySQL, HTAP y escalado horizontal nativo.','Open source distributed SQL database. MySQL compatible, HTAP and native horizontal scaling.','freemium',0,4.3,true,['sql','distribuido','open-source','mysql-compatible'],'pingcap.com'),
  add('cat-19','memgraph','Memgraph','Base de datos de grafos en memoria compatible con Cypher. Analisis en tiempo real para redes y recomendaciones.','In-memory graph database compatible with Cypher. Real-time analytics for networks and recommendations.','freemium',0,4.5,true,['grafos','in-memory','real-time','cypher'],'memgraph.com'),
  add('cat-19','arangodb','ArangoDB','Base de datos multi-modelo nativa. Grafos, documentos y key-value con un solo core y lenguaje de consulta.','Native multi-model database. Graphs, documents and key-value with one core and query language.','freemium',0,4.3,true,['multi-modelo','grafos','documentos','open-source'],'arangodb.com'),
  add('cat-19','questdb','QuestDB','Base de datos de series temporales open source ultrarrapida. SQL nativo, ingesta masiva y latencia minima.','Ultra-fast open source time-series database. Native SQL, massive ingestion and minimal latency.','free',0,4.5,true,['time-series','open-source','sql','rapido'],'questdb.io'),

  // LEGAL cat-20 (30)
  add('cat-20','docusign','DocuSign','Lider mundial en firma electronica. Acuerdos, contract lifecycle, notario online y 1M+ clientes.','World leader in e-signature. Agreements, contract lifecycle, online notary and 1M+ clients.','paid',10,4.5,false,['firma-electronica','contratos','legal','clm'],'docusign.com'),
  add('cat-20','hellosign','Dropbox Sign','Firma electronica integrada con Dropbox. Simple, API potente, plantillas y flujos de firma avanzados.','E-signature integrated with Dropbox. Simple, powerful API, templates and advanced signing flows.','paid',15,4.5,false,['firma-electronica','api','plantillas','dropbox'],'hellosign.com'),
  add('cat-20','pandadoc','PandaDoc','Plataforma de documentos y firma electronica. Propuestas, contratos, quotes y e-signatures integradas.','Document and e-signature platform. Proposals, contracts, quotes and integrated e-signatures.','paid',19,4.6,false,['documentos','firma-electronica','propuestas','ventas'],'pandadoc.com'),
  add('cat-20','signnow','SignNow','Firma electronica asequible. Drag-and-drop, templates, notificaciones y API para integraciones.','Affordable e-signature. Drag-and-drop, templates, notifications and API for integrations.','paid',8,4.5,false,['firma-electronica','asequible','api','templates'],'signnow.com'),
  add('cat-20','adobesign','Adobe Acrobat Sign','Firma electronica de Adobe integrada con PDF. Compliance global, workflows avanzados y Acrobat.','Adobe e-signature integrated with PDF. Global compliance, advanced workflows and Acrobat.','paid',12.99,4.3,false,['firma-electronica','adobe','pdf','enterprise'],'acrobat.adobe.com'),
  add('cat-20','signrequest','SignRequest','Firma electronica simple y economica. Integraciones con Google, Slack, Salesforce y Zapier.','Simple affordable e-signature. Integrations with Google, Slack, Salesforce and Zapier.','freemium',7,4.5,false,['firma-electronica','simple','economico','integraciones'],'signrequest.com'),
  add('cat-20','eversign','Eversign','Firma electronica con auditoria completa. Templates, in-person signing, API REST y compliance.','E-signature with full audit trail. Templates, in-person signing, REST API and compliance.','freemium',7.99,4.6,false,['firma-electronica','auditoria','api','compliance'],'eversign.com'),
  add('cat-20','contractbook','Contractbook','Gestion de contratos con automatizacion. Crea, firma, almacena y analiza contratos con IA.','Contract management with automation. Create, sign, store and analyze contracts with AI.','paid',32,4.4,false,['contratos','clm','ia','automatizacion'],'contractbook.com'),
  add('cat-20','ironclad','Ironclad','CLM enterprise para equipos legales. Workflow designer, repositorio, analiticas y reporting.','Enterprise CLM for legal teams. Workflow designer, repository, analytics and reporting.','paid',500,4.5,false,['clm','enterprise','workflows','legal'],'ironcladapp.com'),
  add('cat-20','juro','Juro','CLM moderno con IA. Contratos inteligentes, aprobaciones, firma electronica y analytics.','Modern CLM with AI. Smart contracts, approvals, e-signature and analytics.','paid',47,4.6,false,['clm','ia','contratos','moderno'],'juro.com'),
  add('cat-20','lexion','Lexion','CLM con IA para equipos legales. Extrae datos de contratos, workflows de aprobacion y reporting.','AI-powered CLM for legal teams. Extract contract data, approval workflows and reporting.','paid',80,4.5,false,['clm','ia','contratos','legal'],'lexion.ai'),
  add('cat-20','clio','Clio','Software de gestion legal lider. Casos, facturacion, documentos, calendario y portal del cliente.','Leading legal practice management software. Cases, billing, documents, calendar and client portal.','paid',39,4.6,false,['legal','gestion-despachos','facturacion','abogados'],'clio.com'),
  add('cat-20','mycase','MyCase','Software de gestion para despachos legales. Casos, facturacion, pagos online y comunicacion con clientes.','Law practice management software. Cases, billing, online payments and client communication.','paid',69,4.5,false,['legal','despachos','facturacion','clientes'],'mycase.com'),
  add('cat-20','practicepanther','PracticePanther','CRM y gestion legal. Seguimiento de tiempo, facturacion, gestion de casos y automatizaciones.','Legal CRM and management. Time tracking, billing, case management and automations.','paid',49,4.4,false,['legal','crm','facturacion','automatizacion'],'practicepanther.com'),
  add('cat-20','smokeball','Smokeball','Software legal con IA para despachos pequenos. Automatizacion de documentos, tracking y productividad.','AI legal software for small firms. Document automation, tracking and productivity.','paid',139,4.3,false,['legal','ia','automatizacion','despachos'],'smokeball.com'),
  add('cat-20','filevine','Filevine','Plataforma legal con gestion de casos y documentos. Workflows personalizables, reporting y colaboracion.','Legal platform with case and document management. Customizable workflows, reporting and collaboration.','paid',250,4.3,false,['legal','workflows','documentos','colaboracion'],'filevine.com'),
  add('cat-20','legalzoom','LegalZoom','Servicios legales online para empresas y particulares. LLCs, trademarks, testamentos y consultas legales.','Online legal services for businesses and individuals. LLCs, trademarks, wills and legal advice.','paid',0,4.3,false,['legal','online','empresas','particulares'],'legalzoom.com'),
  add('cat-20','rocketlawyer','Rocket Lawyer','Documentos legales y asesoria online. Contratos, testamentos, preguntas a abogados y registered agent.','Online legal documents and advice. Contracts, wills, attorney questions and registered agent.','paid',39.99,4.2,false,['legal','documentos','asesoria','online'],'rocketlawyer.com'),
  add('cat-20','netdocuments','NetDocuments','Plataforma de gestion documental legal cloud-native. Seguridad enterprise, compliance y colaboracion.','Cloud-native legal document management. Enterprise security, compliance and collaboration.','paid',25,4.3,false,['dms','legal','cloud','seguridad'],'netdocuments.com'),
  add('cat-20','imanage','iManage','Gestion documental y de conocimiento legal. Work product, seguridad, IA y governance.','Legal document and knowledge management. Work product, security, AI and governance.','paid',35,4.2,false,['dms','legal','ia','governance'],'imanage.com'),
  add('cat-20','disco','DISCO','eDiscovery con IA. Revision de documentos, analisis predictivo y case builder para litigios.','AI-powered eDiscovery. Document review, predictive analytics and case builder for litigation.','paid',50,4.4,false,['ediscovery','ia','litigacion','documentos'],'csdisco.com'),
  add('cat-20','logikcull','Logikcull','eDiscovery simple y seguro. Busqueda, revision y produccion de documentos sin complejidad.','Simple secure eDiscovery. Search, review and document production without complexity.','paid',40,4.3,false,['ediscovery','simple','seguro','documentos'],'logikcull.com'),
  add('cat-20','relativity','Relativity','Plataforma de eDiscovery enterprise. Revision, analytics, traduccion y gestion de casos complejos.','Enterprise eDiscovery platform. Review, analytics, translation and complex case management.','paid',100,4.3,false,['ediscovery','enterprise','analytics','legal'],'relativity.com'),
  add('cat-20','avvoka','Avvoka','Automatizacion de documentos legales con IA. Templates, negociacion, firma y analytics.','AI legal document automation. Templates, negotiation, signature and analytics.','paid',40,4.2,false,['documentos-legales','ia','templates','automatizacion'],'avvoka.com'),
  add('cat-20','seedlegals','SeedLegals','Documentacion legal para startups. Rondas de inversion, opciones, acuerdos y compliance.','Legal documentation for startups. Investment rounds, options, agreements and compliance.','paid',50,4.5,false,['startups','legal','inversion','compliance'],'seedlegals.com'),
  add('cat-20','linksquares','LinkSquares','CLM con IA para equipos legales enterprise. Analiza, redacta y gestiona contratos a escala.','AI-powered CLM for enterprise legal teams. Analyze, draft and manage contracts at scale.','paid',300,4.4,false,['clm','ia','enterprise','contratos'],'linksquares.com'),
  add('cat-20','termly','Termly','Generador de politicas legales para webs y apps. GDPR, CCPA, cookies consent y terminos de uso.','Legal policy generator for websites and apps. GDPR, CCPA, cookie consent and terms of use.','freemium',10,4.6,false,['legal','politicas','privacy','gdpr'],'termly.io'),
  add('cat-20','iubenda','iubenda','Generador de politicas de privacidad y cookies. Compliance global con 2500+ clausulas pre-escritas.','Privacy and cookie policy generator. Global compliance with 2500+ pre-written clauses.','freemium',5.99,4.6,false,['privacy','cookies','compliance','gdpr'],'iubenda.com'),
  add('cat-20','contractsafe','ContractSafe','Gestion de contratos simple y segura. OCR, busqueda, alertas de vencimiento y repositorio centralizado.','Simple secure contract management. OCR, search, expiration alerts and centralized repository.','paid',299,4.5,false,['contratos','clm','simple','ocr'],'contractsafe.com'),
  add('cat-20','legislate','Legislate','Contratos inteligentes sin abogados. Acuerdos legalmente vinculantes generados con tecnologia de knowledge graph.','Smart contracts without lawyers. Legally binding agreements generated with knowledge graph technology.','paid',30,4.3,false,['contratos','ia','knowledge-graph','legales'],'legislate.tech'),
]

const allNew = [...tools, ...more]

let seed = readFileSync(SEED_PATH, 'utf-8')

// Find tools array end
const toolsStart = seed.indexOf('export const tools:')
let depth = 0
let toolsEnd = toolsStart
for (let i = toolsStart; i < seed.length; i++) {
  if (seed[i] === '[') depth++
  if (seed[i] === ']') { depth--; if (depth === 0) { toolsEnd = i; break } }
}

const ts = allNew.map(t => `  {
    id: '${t.id}', slug: '${t.slug}', name: '${t.name}',
    logo_url: '${t.logo_url}',
    description_es: '${t.description_es.replace(/'/g, "\\'")}',
    description_en: '${t.description_en.replace(/'/g, "\\'")}',
    category_id: '${t.category_id}', price_model: '${t.price_model}', price_starting: ${t.price_starting},
    website_url: '${t.website_url}', affiliate_url: null,
    rating_g2: ${t.rating_g2}, rating_capterra: null, is_open_source: ${t.is_open_source}, is_verified: false, listing_tier: 'free',
    tags: [${t.tags.map(x => `'${x}'`).join(', ')}],
  }`)

const before = seed.slice(0, toolsEnd)
const after = seed.slice(toolsEnd)
seed = before + ',\n' + ts.join(',\n') + '\n' + after

writeFileSync(SEED_PATH, seed)
console.log(`✅ Added ${allNew.length} tools (RRHH: ${tools.length}, BBDD+Legal: ${more.length})`)
