// FINAL BATCH: Add ~300 tools to reach 30 per category
import { readFileSync, writeFileSync } from 'fs'

const SEED_PATH = 'src/lib/seed-data.ts'
const cb = (d) => `https://logo.clearbit.com/${d}`

let toolNum = 300
function add(cat, slug, name, descEs, descEn, pm, ps, rating, os, tags, domain, website) {
  toolNum++
  const w = website || `https://${domain}`
  return {
    id: `tool-${toolNum}`, slug, name,
    logo_url: cb(domain),
    description_es: descEs.replace(/'/g, "\\'"),
    description_en: descEn.replace(/'/g, "\\'"),
    category_id: cat, price_model: pm, price_starting: ps,
    website_url: w, affiliate_url: null,
    rating_g2: rating, rating_capterra: null,
    is_open_source: os || false, is_verified: false, listing_tier: 'free',
    tags: tags || [], alternatives: []
  }
}

const newTools = [
  // ===== FINANZAS cat-8 (29 tools) =====
  add('cat-8','quickbooks','QuickBooks','Software de contabilidad lider para pymes. Facturacion, gastos, nominas, impuestos y reporting financiero.','Leading accounting software for SMBs. Invoicing, expenses, payroll, taxes and financial reporting.','paid',15,4.3,false,['contabilidad','pymes','facturacion','impuestos'],'quickbooks.intuit.com'),
  add('cat-8','xero','Xero','Contabilidad cloud para pymes. Facturacion, conciliacion bancaria, nominas y 1000+ integraciones.','Cloud accounting for SMBs. Invoicing, bank reconciliation, payroll and 1000+ integrations.','paid',15,4.3,false,['contabilidad','cloud','pymes','conciliacion'],'xero.com'),
  add('cat-8','freshbooks','FreshBooks','Contabilidad y facturacion para freelancers y pequenas empresas. Time tracking, gastos y pagos online.','Accounting and invoicing for freelancers and small businesses. Time tracking, expenses and online payments.','paid',9.5,4.5,false,['contabilidad','freelancers','facturacion','time-tracking'],'freshbooks.com'),
  add('cat-8','sage','Sage','Software de gestion empresarial y contabilidad. ERP, nominas, finanzas y cumplimiento fiscal.','Business management and accounting software. ERP, payroll, finance and tax compliance.','paid',12,3.9,false,['contabilidad','erp','nomina','enterprise'],'sage.com'),
  add('cat-8','zohobooks','Zoho Books','Contabilidad cloud en la suite Zoho. Facturacion, gastos, inventario, proyectos y conciliacion automatica.','Cloud accounting in Zoho suite. Invoicing, expenses, inventory, projects and auto reconciliation.','freemium',10,4.4,false,['contabilidad','zoho','cloud','pymes'],'zoho.com/books'),
  add('cat-8','wave','Wave','Contabilidad y facturacion 100% gratuita. Ideal para freelancers y microempresas con ingresos simples.','100% free accounting and invoicing. Ideal for freelancers and micro-businesses with simple income.','free',0,4.4,false,['contabilidad','gratis','freelancers','facturacion'],'waveapps.com'),
  add('cat-8','stripe','Stripe','Plataforma de pagos online lider. APIs para suscripciones, marketplaces, facturacion y terminal POS.','Leading online payment platform. APIs for subscriptions, marketplaces, billing and POS terminal.','freemium',0,4.6,false,['pagos','api','suscripciones','marketplace'],'stripe.com'),
  add('cat-8','paypal','PayPal','Plataforma global de pagos online. Pagos, checkout, transferencias, business y proteccion al comprador.','Global online payment platform. Payments, checkout, transfers, business and buyer protection.','freemium',0,4.3,false,['pagos','checkout','transferencias','global'],'paypal.com'),
  add('cat-8','square','Square','Soluciones de pago para negocios. TPV, online, facturas, nomina y gestion de restaurantes.','Payment solutions for businesses. POS, online, invoices, payroll and restaurant management.','freemium',0,4.4,false,['pagos','pos','tpv','negocios'],'squareup.com'),
  add('cat-8','adyen','Adyen','Plataforma de pagos enterprise global. Metodos de pago locales, risk management y reporting unificado.','Global enterprise payment platform. Local payment methods, risk management and unified reporting.','paid',0,4.3,false,['pagos','enterprise','global','riesgo'],'adyen.com'),
  add('cat-8','mollie','Mollie','Plataforma de pagos europea simple. APIs faciles, metodos locales y dashboard intuitivo.','Simple European payment platform. Easy APIs, local methods and intuitive dashboard.','freemium',0,4.5,false,['pagos','europeo','api','simple'],'mollie.com'),
  add('cat-8','bizum','Bizum','Plataforma de pagos instantaneos en Espana. Envia y recibe dinero al instante entre bancos espanoles.','Instant payment platform in Spain. Send and receive money instantly between Spanish banks.','free',0,4.5,false,['pagos','espanol','instantaneo','movil'],'bizum.es'),
  add('cat-8','pleo','Pleo','Gestion de gastos de empresa con tarjetas virtuales. Control, categorizacion automatica y contabilidad.','Company expense management with virtual cards. Control, auto-categorization and accounting.','paid',8,4.6,false,['gastos','tarjetas','control','pymes'],'pleo.io'),
  add('cat-8','expensify','Expensify','Gestion de gastos e informes automatizada. Escaneo de recibos, reembolsos y sincronizacion contable.','Automated expense management and reports. Receipt scanning, reimbursements and accounting sync.','freemium',5,4.4,false,['gastos','recibos','reembolsos','automatizacion'],'expensify.com'),
  add('cat-8','spendesk','Spendesk','Plataforma de gestion de gastos empresariales. Tarjetas virtuales, aprobaciones y presupuestos en tiempo real.','Business spend management platform. Virtual cards, approvals and real-time budgets.','paid',9,4.6,false,['gastos','tarjetas','presupuestos','pymes'],'spendesk.com'),
  add('cat-8','payhawk','PayHawk','Gestion de gastos con tarjetas, facturas, reembolsos integrados. Automatizacion contable con ERP.','Expense management with cards, invoices, integrated reimbursements. ERP accounting automation.','paid',10,4.7,false,['gastos','tarjetas','erp','pymes'],'payhawk.com'),
  add('cat-8','quipu','Quipu','Software de facturacion y contabilidad espanol. Factura electronica, IRPF, IVA, bancos y asesoria.','Spanish invoicing and accounting software. E-invoice, IRPF, VAT, banking and advisory.','paid',12,4.2,false,['facturacion','espanol','contabilidad','autonomos'],'getquipu.com'),
  add('cat-8','anfix','Anfix','Software de contabilidad y facturacion espanol. Automatizacion fiscal, asesoria integrada y banco.','Spanish accounting and invoicing software. Tax automation, integrated advisory and banking.','paid',14,4.1,false,['contabilidad','espanol','facturacion','autonomos'],'anfix.com'),
  add('cat-8','dext','Dext','Automatizacion de documentos contables. Captura recibos, facturas y extractos bancarios con OCR e IA.','Accounting document automation. Capture receipts, invoices and bank statements with OCR and AI.','paid',20,4.5,false,['contabilidad','ocr','automatizacion','documentos'],'dext.com'),
  add('cat-8','fintonic','Fintonic','App espanola de finanzas personales y prestamos. Agrega bancos, categoriza gastos y mejora tu salud financiera.','Spanish personal finance and loans app. Aggregates banks, categorizes expenses and improves financial health.','free',0,4.0,false,['finanzas-personales','espanol','banca','prestamos'],'fintonic.com'),
  add('cat-8','mint','Mint','App gratuita de finanzas personales de Intuit. Presupuestos, seguimiento de gastos, credit score y metas.','Free personal finance app by Intuit. Budgets, expense tracking, credit score and goals.','free',0,4.2,false,['finanzas-personales','presupuestos','gratis','credito'],'mint.intuit.com'),
  add('cat-8','ynab','YNAB','App de presupuestos con metodo probado. Asigna cada dolar, reduce deuda y construye ahorro a largo plazo.','Budgeting app with proven method. Assign every dollar, reduce debt and build long-term savings.','paid',14.99,4.6,false,['presupuestos','finanzas-personales','ahorro','metodo'],'ynab.com'),
  add('cat-8','toshl','Toshl','App de finanzas personales con medusas. Seguimiento de gastos divertido, presupuestos y multi-moneda.','Personal finance app with monsters. Fun expense tracking, budgets and multi-currency.','freemium',4.99,4.3,false,['finanzas-personales','divertido','presupuestos','multi-moneda'],'toshl.com'),
  add('cat-8','getbill','Bill.com','Plataforma de cuentas por pagar y cobrar. Automatiza AP/AR, flujos de aprobacion y pagos B2B.','Accounts payable and receivable platform. Automates AP/AR, approval flows and B2B payments.','paid',45,4.3,false,['ap','ar','pagos','b2b'],'bill.com'),
  add('cat-8','brex','Brex','Plataforma financiera para startups. Tarjetas corporativas, gestion de gastos, bill pay y cash management.','Financial platform for startups. Corporate cards, expense management, bill pay and cash management.','free',0,4.5,false,['startups','tarjetas','gastos','fintech'],'brex.com'),
  add('cat-8','ramp','Ramp','Tarjeta corporativa con control de gastos inteligente. Ahorro automatico, reporting en tiempo real y sin comisiones.','Corporate card with smart spend control. Auto savings, real-time reporting and no fees.','free',0,4.7,false,['tarjetas','gastos','ahorro','corporate'],'ramp.com'),
  add('cat-8','mercury','Mercury','Banca online para startups. Cuentas, tarjetas, transferencias, API bancaria y venture debt.','Online banking for startups. Accounts, cards, transfers, banking API and venture debt.','free',0,4.6,false,['banca','startups','api','fintech'],'mercury.com'),
  add('cat-8','wise','Wise','Transferencias internacionales al tipo de cambio real. Cuenta multi-moneda, tarjeta y recibos sin comisiones ocultas.','International transfers at real exchange rate. Multi-currency account, card and receipts with no hidden fees.','freemium',0,4.5,false,['transferencias','multi-moneda','internacional','fintech'],'wise.com'),
  add('cat-8','revolut','Revolut','Superapp financiera global. Cuenta, tarjeta, cambio divisa, cripto, trading y seguros. Todo en una app.','Global financial superapp. Account, card, currency exchange, crypto, trading and insurance in one app.','freemium',0,4.4,false,['banca','superapp','cripto','global'],'revolut.com'),

  // ===== EMAIL MARKETING cat-5 (28 tools) =====
  add('cat-5','mailerlite','MailerLite','Email marketing asequible y potente. Editor drag-drop, automatizaciones, landing pages y sitios web.','Affordable powerful email marketing. Drag-drop editor, automations, landing pages and websites.','freemium',9,4.7,false,['email','asequible','automatizacion','drag-drop'],'mailerlite.com'),
  add('cat-5','activecampaign','ActiveCampaign','Email marketing y CRM con automatizaciones avanzadas. Segmentacion, lead scoring y machine learning.','Email marketing and CRM with advanced automations. Segmentation, lead scoring and machine learning.','paid',15,4.5,false,['email','crm','automatizacion','machine-learning'],'activecampaign.com'),
  add('cat-5','getresponse','GetResponse','Suite de marketing todo en uno. Email, landing pages, webinars, popups y marketing automation.','All-in-one marketing suite. Email, landing pages, webinars, popups and marketing automation.','freemium',15.58,4.2,false,['email','webinars','landing-pages','todo-en-uno'],'getresponse.com'),
  add('cat-5','sendgrid','SendGrid','Plataforma de email transaccional y marketing de Twilio. APIs, deliverability y templates.','Transactional and marketing email platform by Twilio. APIs, deliverability and templates.','freemium',19.95,4.2,false,['email','transaccional','api','twilio'],'sendgrid.com'),
  add('cat-5','mailjet','Mailjet','Email marketing y transaccional colaborativo. Editor drag-drop, APIs, SMTP y estadisticas avanzadas.','Collaborative email marketing and transactional. Drag-drop editor, APIs, SMTP and advanced stats.','freemium',15,4.1,false,['email','transaccional','colaborativo','api'],'mailjet.com'),
  add('cat-5','mailgun','Mailgun','API de email para desarrolladores. Envio transaccional masivo, validacion, analytics y deliverability.','Email API for developers. Massive transactional sending, validation, analytics and deliverability.','freemium',35,4.3,false,['email','api','transaccional','desarrolladores'],'mailgun.com'),
  add('cat-5','postmark','Postmark','Email transaccional ultrarrápido de ActiveCampaign. Envio en segundos, deliverability y tracking.','Ultra-fast transactional email by ActiveCampaign. Delivery in seconds, deliverability and tracking.','paid',15,4.6,false,['email','transaccional','rapido','deliverability'],'postmarkapp.com'),
  add('cat-5','sender','Sender','Email marketing asequible sin limites de contactos. Newsletter, automatizaciones, SMS y popups.','Affordable email marketing with unlimited contacts. Newsletter, automations, SMS and popups.','freemium',8,4.6,false,['email','asequible','newsletter','sms'],'sender.net'),
  add('cat-5','omnisend','Omnisend','Email y SMS marketing para ecommerce. Automatizaciones pre-build, segmentacion y sincronizacion con tiendas.','Email and SMS marketing for ecommerce. Pre-built automations, segmentation and store sync.','freemium',16,4.6,false,['email','sms','ecommerce','automatizacion'],'omnisend.com'),
  add('cat-5','klaviyo','Klaviyo','Email y SMS marketing para ecommerce con IA. Segmentacion avanzada, flows y analisis predictivo.','AI-powered email and SMS marketing for ecommerce. Advanced segmentation, flows and predictive analytics.','freemium',20,4.6,false,['email','sms','ecommerce','ia'],'klaviyo.com'),
  add('cat-5','drip','Drip','Email marketing para ecommerce con CRM integrado. Seguimiento de comportamiento, workflows y segmentacion.','Ecommerce email marketing with integrated CRM. Behavior tracking, workflows and segmentation.','paid',39,4.4,false,['email','ecommerce','crm','comportamiento'],'drip.com'),
  add('cat-5','moosend','Moosend','Email marketing asequible con IA. Editor drag-drop, automatizaciones, landing pages y suscripciones.','Affordable AI email marketing. Drag-drop editor, automations, landing pages and subscriptions.','freemium',9,4.5,false,['email','asequible','ia','automatizacion'],'moosend.com'),
  add('cat-5','aweber','AWeber','Email marketing clasico para pequenos negocios. Newsletter, auto-responders, AMP emails y landing pages.','Classic email marketing for small businesses. Newsletter, auto-responders, AMP emails and landing pages.','freemium',12.5,4.2,false,['email','newsletter','auto-responder','pymes'],'aweber.com'),
  add('cat-5','constantcontact','Constant Contact','Email marketing para pymes y nonprofits. Eventos, redes sociales, anuncios y marketing digital integrado.','Email marketing for SMBs and nonprofits. Events, social media, ads and integrated digital marketing.','paid',12,4.0,false,['email','pymes','eventos','redes-sociales'],'constantcontact.com'),
  add('cat-5','benchmark','Benchmark Email','Email marketing simple con editor drag-drop. Encuestas, landing pages, automatizaciones y pruebas A/B.','Simple email marketing with drag-drop editor. Surveys, landing pages, automations and A/B testing.','freemium',9.99,4.5,false,['email','simple','encuestas','landing-pages'],'benchmarkemail.com'),
  add('cat-5','campaignmonitor','Campaign Monitor','Email marketing profesional con disenos elegantes. Segmentacion, personalizacion y analytics visual.','Professional email marketing with elegant designs. Segmentation, personalization and visual analytics.','paid',9,4.2,false,['email','profesional','diseno','segmentacion'],'campaignmonitor.com'),
  add('cat-5','customerio','Customer.io','Plataforma de automatizacion de mensajeria. Email, SMS, push, in-app con datos de comportamiento.','Messaging automation platform. Email, SMS, push, in-app with behavioral data.','paid',100,4.4,false,['email','sms','push','automatizacion'],'customer.io'),
  add('cat-5','sendinblue','Brevo','Email marketing, SMS, chat y CRM unificados. Automatizaciones visuales y plan gratuito generoso.','Unified email marketing, SMS, chat and CRM. Visual automations and generous free plan.','freemium',9,4.5,false,['email','sms','chat','crm'],'brevo.com'),
  add('cat-5','flodesk','Flodesk','Email marketing con diseno premium. Plantillas elegantes, workflows simples y tarifa plana sin sorpresas.','Email marketing with premium design. Elegant templates, simple workflows and flat pricing with no surprises.','paid',38,4.7,false,['email','diseno','plantillas','tarifa-plana'],'flodesk.com'),
  add('cat-5','mailpoet','MailPoet','Plugin de email marketing para WordPress. Newsletters, automatizaciones y WooCommerce integrado.','Email marketing plugin for WordPress. Newsletters, automations and WooCommerce integration.','freemium',10,4.5,false,['email','wordpress','woocommerce','newsletter'],'mailpoet.com'),
  add('cat-5','sendfox','SendFox','Email marketing economico para creadores. Sin limites de listas, landing pages y automatizaciones simples.','Affordable email marketing for creators. No list limits, landing pages and simple automations.','paid',49,4.6,false,['email','creadores','economico','simple'],'sendfox.com'),
  add('cat-5','loops','Loops','Email marketing moderno para SaaS. Seguimiento de eventos, automatizaciones y diseno minimalista.','Modern email marketing for SaaS. Event tracking, automations and minimalist design.','paid',50,4.7,false,['email','saas','eventos','moderno'],'loops.so'),
  add('cat-5','resend','Resend','API de email para desarrolladores. Diseno con React, envio con API simple y deliverability enterprise.','Email API for developers. React-based design, simple API delivery and enterprise deliverability.','freemium',20,4.6,false,['email','api','react','desarrolladores'],'resend.com'),
  add('cat-5','polymail','Polymail','Email con CRM, tracking y automatizaciones. Secuencias, templates, seguimiento y colaboracion en equipo.','Email with CRM, tracking and automations. Sequences, templates, follow-up and team collaboration.','paid',10,4.5,false,['email','crm','tracking','colaboracion'],'polymail.io'),
  add('cat-5','superhuman','Superhuman','El cliente de email mas rapido del mundo. Atajos de teclado, AI, follow-ups automaticos y split inbox.','The fastest email client in the world. Keyboard shortcuts, AI, auto follow-ups and split inbox.','paid',30,4.6,false,['email','rapido','ai','productividad'],'superhuman.com'),
  add('cat-5','missive','Missive','Email colaborativo con chat interno. Gestiona emails en equipo con asignaciones, comentarios y workflows.','Collaborative email with internal chat. Manage emails as a team with assignments, comments and workflows.','paid',14,4.7,false,['email','colaborativo','chat','equipo'],'missiveapp.com'),
  add('cat-5','sparkmail','Spark','Cliente de email inteligente con AI. Inbox zero automatico, colaboracion en equipo y calendario integrado.','Intelligent email client with AI. Auto inbox zero, team collaboration and integrated calendar.','freemium',7.99,4.5,false,['email','ai','inbox-zero','colaboracion'],'sparkmailapp.com'),
  add('cat-5','outfunnel','Outfunnel','Conexion de email marketing con CRM. Sincroniza datos, puntua leads y automatiza comunicaciones de ventas.','Email marketing to CRM connector. Syncs data, scores leads and automates sales communications.','paid',19,4.6,false,['email','crm','sincronizacion','ventas'],'outfunnel.com'),
]

// Append more categories...
const more = [
  // ===== ANALITICA cat-6 (28 tools) =====
  add('cat-6','matomo','Matomo','Alternativa open source a Google Analytics. 100% propiedad de datos, GDPR compliant, heatmaps y session recordings.','Open source Google Analytics alternative. 100% data ownership, GDPR compliant, heatmaps and session recordings.','freemium',0,4.3,true,['analitica','open-source','privacidad','heatmaps'],'matomo.org'),
  add('cat-6','fathom','Fathom Analytics','Analitica web simple y privada. Dashboard minimalista, sin cookies, script de 2KB y cumplimiento GDPR automatico.','Simple private web analytics. Minimalist dashboard, cookieless, 2KB script and auto GDPR compliance.','paid',14,4.7,false,['analitica','privacidad','simple','gdpr'],'usefathom.com'),
  add('cat-6','mixpanel','Mixpanel','Analitica de producto con analisis de eventos. Funnels, retention, impact, signals y dashboards interactivos.','Product analytics with event analysis. Funnels, retention, impact, signals and interactive dashboards.','freemium',20,4.5,false,['analitica','producto','eventos','funnels'],'mixpanel.com'),
  add('cat-6','amplitude','Amplitude','Plataforma de analitica digital. Behavioral analytics, A/B testing, CDP y predictive analytics.','Digital analytics platform. Behavioral analytics, A/B testing, CDP and predictive analytics.','freemium',0,4.5,false,['analitica','comportamiento','ab-testing','producto'],'amplitude.com'),
  add('cat-6','heap','Heap','Analitica de producto que captura todo automaticamente. Autocapture, session replay, journeys y retroactive analytics.','Product analytics that captures everything automatically. Autocapture, session replay, journeys and retroactive analytics.','freemium',0,4.4,false,['analitica','autocapture','producto','session-replay'],'heap.io'),
  add('cat-6','hotjar','Hotjar','Analitica de experiencia de usuario. Heatmaps, session recordings, feedback widgets y encuestas.','User experience analytics. Heatmaps, session recordings, feedback widgets and surveys.','freemium',32,4.4,false,['analitica','ux','heatmaps','feedback'],'hotjar.com'),
  add('cat-6','posthog','PostHog','Suite de analitica de producto open source. Eventos, session replay, feature flags, A/B tests y surveys.','Open source product analytics suite. Events, session replay, feature flags, A/B tests and surveys.','freemium',0,4.7,true,['analitica','open-source','producto','feature-flags'],'posthog.com'),
  add('cat-6','fullstory','FullStory','Analitica de experiencia digital. Session replay avanzado, frustration signals y behavioral analytics.','Digital experience analytics. Advanced session replay, frustration signals and behavioral analytics.','freemium',0,4.5,false,['analitica','session-replay','ux','digital-experience'],'fullstory.com'),
  add('cat-6','logrocket','LogRocket','Analitica de frontend para developers. Session replay, errores, network y performance monitoring.','Frontend analytics for developers. Session replay, errors, network and performance monitoring.','freemium',69,4.5,false,['analitica','frontend','errores','performance'],'logrocket.com'),
  add('cat-6','tableau','Tableau','Plataforma de visualizacion de datos y BI. Dashboards interactivos, data storytelling y AI-driven analytics.','Data visualization and BI platform. Interactive dashboards, data storytelling and AI-driven analytics.','paid',70,4.3,false,['bi','visualizacion','dashboards','datos'],'tableau.com'),
  add('cat-6','powerbi','Power BI','Herramienta de BI de Microsoft. Dashboards, informes, AI y modelado de datos con integracion Office 365.','Microsoft BI tool. Dashboards, reports, AI and data modeling with Office 365 integration.','freemium',10,4.4,false,['bi','microsoft','dashboards','office365'],'powerbi.microsoft.com'),
  add('cat-6','looker','Looker Studio','BI y analitica de Google. Dashboards, exploraciones y modelado con LookML. Integracion BigQuery nativa.','Google BI and analytics. Dashboards, explorations and modeling with LookML. Native BigQuery integration.','freemium',0,4.3,false,['bi','google','bigquery','dashboards'],'lookerstudio.google.com'),
  add('cat-6','metabase','Metabase','BI open source simple y rapido. Preguntas en lenguaje natural, dashboards y embebido para clientes.','Simple fast open source BI. Natural language questions, dashboards and embedding for customers.','freemium',85,4.5,true,['bi','open-source','simple','lenguaje-natural'],'metabase.com'),
  add('cat-6','preset','Preset','Apache Superset gestionado en la nube. BI open source con dashboards avanzados y exploracion de datos.','Managed Apache Superset in the cloud. Open source BI with advanced dashboards and data exploration.','freemium',0,4.5,false,['bi','superset','open-source','dashboards'],'preset.io'),
  add('cat-6','thoughtspot','ThoughtSpot','BI con busqueda tipo Google y AI. Haz preguntas en lenguaje natural y obten insights al instante.','BI with Google-like search and AI. Ask questions in natural language and get insights instantly.','paid',95,4.3,false,['bi','ai','busqueda','lenguaje-natural'],'thoughtspot.com'),
  add('cat-6','databox','Databox','Dashboards de KPI en tiempo real. Conecta 100+ fuentes, goal tracking, alerts y mobile-first.','Real-time KPI dashboards. Connect 100+ sources, goal tracking, alerts and mobile-first.','freemium',49,4.5,false,['kpi','dashboards','alerts','mobile'],'databox.com'),
  add('cat-6','geckoboard','Geckoboard','Dashboards de KPI para TV. Comparte metricas clave en tiempo real en pantallas de la oficina.','KPI TV dashboards. Share key metrics in real-time on office screens.','paid',35,4.4,false,['kpi','dashboards','tv','tiempo-real'],'geckoboard.com'),
  add('cat-6','klipfolio','Klipfolio','Plataforma de dashboards y metricas de negocio. Conecta datos, construye visualizaciones y comparte KPIs.','Business dashboard and metrics platform. Connect data, build visualizations and share KPIs.','paid',99,4.4,false,['kpi','dashboards','metricas','conexiones'],'klipfolio.com'),
  add('cat-6','chartmogul','ChartMogul','Analitica de ingresos para SaaS. MRR, churn, LTV, cohortes y metricas de suscripcion.','Revenue analytics for SaaS. MRR, churn, LTV, cohorts and subscription metrics.','freemium',100,4.5,false,['saas','metricas','mrr','churn'],'chartmogul.com'),
  add('cat-6','baremetrics','Baremetrics','Metricas y analitica financiera para SaaS. MRR, churn, forecasting, dunning y cancellation insights.','Financial metrics and analytics for SaaS. MRR, churn, forecasting, dunning and cancellation insights.','paid',108,4.4,false,['saas','metricas','financiero','forecasting'],'baremetrics.com'),
  add('cat-6','profitwell','ProfitWell','Analitica de pricing gratuita para SaaS. Audit de revenue, benchmark, retention y pricing recommendations.','Free pricing analytics for SaaS. Revenue audit, benchmark, retention and pricing recommendations.','freemium',0,4.6,false,['saas','pricing','gratis','metricas'],'profitwell.com'),
  add('cat-6','segment','Twilio Segment','CDP lider para recoleccion de datos de clientes. Unifica eventos, identidades y envia a 400+ destinos.','Leading CDP for customer data collection. Unifies events, identities and sends to 400+ destinations.','freemium',0,4.4,false,['cdp','datos','eventos','integraciones'],'segment.com'),
  add('cat-6','mparticle','mParticle','CDP enterprise con AI. Orquestacion de datos de cliente, audience building y conexion con 300+ partners.','Enterprise CDP with AI. Customer data orchestration, audience building and 300+ partner connections.','paid',300,4.3,false,['cdp','enterprise','ai','audiencias'],'mparticle.com'),
  add('cat-6','rudderstack','RudderStack','CDP open source para datos de clientes. Event streaming, reverse ETL, profiles y warehouse-first.','Open source CDP for customer data. Event streaming, reverse ETL, profiles and warehouse-first.','freemium',0,4.5,true,['cdp','open-source','event-streaming','reverse-etl'],'rudderstack.com'),
  add('cat-6','snowplow','Snowplow','Plataforma de datos de comportamiento open source. Colecciona eventos ricos y crea modelos de datos propios.','Open source behavioral data platform. Collects rich events and creates own data models.','freemium',0,4.4,true,['cdp','open-source','eventos','comportamiento'],'snowplow.io'),
  add('cat-6','pendo','Pendo','Plataforma de product experience. In-app guides, analytics, feedback, session replay y NPS.','Product experience platform. In-app guides, analytics, feedback, session replay and NPS.','freemium',0,4.5,false,['analitica','producto','in-app','feedback'],'pendo.io'),
  add('cat-6','userpilot','Userpilot','Onboarding de producto sin codigo. Checklists, tooltips, surveys, analytics y segmentacion.','No-code product onboarding. Checklists, tooltips, surveys, analytics and segmentation.','paid',249,4.6,false,['onboarding','producto','nocode','analytics'],'userpilot.com'),
  add('cat-6','appcues','Appcues','Plataforma de adopcion de producto. Flujos de onboarding, anuncios in-app, encuestas NPS y analytics.','Product adoption platform. Onboarding flows, in-app announcements, NPS surveys and analytics.','paid',249,4.5,false,['onboarding','producto','nps','adopcion'],'appcues.com'),
]

// 2 more batches for remaining categories
const more2 = [
  // ===== E-COMMERCE cat-13 (28 tools) =====
  add('cat-13','prestashop','PrestaShop','CMS de ecommerce open source lider en Espana y Latam. Modulos, temas y comunidad internacional masiva.','Leading open source ecommerce CMS in Spain and Latam. Modules, themes and massive international community.','free',0,4.1,true,['ecommerce','open-source','espanol','modulos'],'prestashop.com'),
  add('cat-13','magento','Adobe Commerce','Plataforma de ecommerce enterprise de Adobe. Catálogos complejos, B2B, multi-tienda y cloud.','Adobe enterprise ecommerce platform. Complex catalogs, B2B, multi-store and cloud.','paid',2000,3.8,false,['ecommerce','enterprise','adobe','b2b'],'business.adobe.com/products/magento'),
  add('cat-13','bigcommerce','BigCommerce','Plataforma de ecommerce enterprise SaaS. Headless, multi-canal, B2B y sin comisiones por venta.','Enterprise SaaS ecommerce platform. Headless, multi-channel, B2B and no per-sale commissions.','paid',29,4.2,false,['ecommerce','enterprise','saas','headless'],'bigcommerce.com'),
  add('cat-13','ecwid','Ecwid','Plugin de tienda online para cualquier web. Añade ecommerce a WordPress, Wix, Facebook e Instagram.','Online store plugin for any website. Add ecommerce to WordPress, Wix, Facebook and Instagram.','freemium',14.08,4.6,false,['ecommerce','plugin','multiplataforma','embed'],'ecwid.com'),
  add('cat-13','tiendanube','Tiendanube','Plataforma de ecommerce lider en Latam. Tienda online, pagos locales, envios y marketing integrado.','Leading ecommerce platform in Latam. Online store, local payments, shipping and integrated marketing.','paid',9,4.5,false,['ecommerce','latam','espanol','pagos-locales'],'tiendanube.com'),
  add('cat-13','vtex','VTEX','Plataforma de ecommerce enterprise composable. OMS, marketplace, checkout y logistica unificada.','Composable enterprise ecommerce platform. OMS, marketplace, checkout and unified logistics.','paid',1000,4.1,false,['ecommerce','enterprise','composable','latam'],'vtex.com'),
  add('cat-13','commercetools','commercetools','Plataforma de ecommerce MACH headless. API-first, cloud-native, microservicios y multi-tenant.','MACH headless ecommerce platform. API-first, cloud-native, microservices and multi-tenant.','paid',5000,4.0,false,['ecommerce','headless','mach','enterprise'],'commercetools.com'),
  add('cat-13','saleor','Saleor','Plataforma de ecommerce headless open source. GraphQL, React storefront, dashboard y multi-canal.','Open source headless ecommerce platform. GraphQL, React storefront, dashboard and multi-channel.','freemium',0,4.5,true,['ecommerce','headless','open-source','graphql'],'saleor.io'),
  add('cat-13','medusajs','Medusa','Plataforma de ecommerce open source para developers. Headless, composable y personalizable al maximo.','Open source ecommerce platform for developers. Headless, composable and maximally customizable.','free',0,4.6,true,['ecommerce','open-source','headless','desarrolladores'],'medusajs.com'),
  add('cat-13','shopware','Shopware','Plataforma de ecommerce open source alemana. Headless, shopping experiences y reglas de precios avanzadas.','German open source ecommerce platform. Headless, shopping experiences and advanced pricing rules.','freemium',600,4.2,true,['ecommerce','open-source','headless','europeo'],'shopware.com'),
  add('cat-13','printful','Printful','Print-on-demand y dropshipping integrado. Conecta con Shopify, Etsy, WooCommerce y vende sin inventario.','Print-on-demand and integrated dropshipping. Connect with Shopify, Etsy, WooCommerce and sell without inventory.','free',0,4.6,false,['ecommerce','pod','dropshipping','print-on-demand'],'printful.com'),
  add('cat-13','shipstation','ShipStation','Plataforma de gestion de envios. Automatiza etiquetas, tracking, devoluciones y multi-carrier.','Shipping management platform. Automates labels, tracking, returns and multi-carrier.','paid',9.99,4.3,false,['envios','logistica','automatizacion','carrier'],'shipstation.com'),
  add('cat-13','aftership','AfterShip','Plataforma de post-compra. Tracking proactivo, devoluciones, proteccion de envios y fidelizacion.','Post-purchase platform. Proactive tracking, returns, shipping protection and loyalty.','freemium',11,4.6,false,['post-compra','tracking','devoluciones','fidelizacion'],'aftership.com'),
  add('cat-13','sendcloud','SendCloud','Plataforma de envios europea. Automatiza envios, tracking y devoluciones con 80+ carriers.','European shipping platform. Automates shipping, tracking and returns with 80+ carriers.','freemium',71,4.4,false,['envios','europeo','tracking','devoluciones'],'sendcloud.com'),
  add('cat-13','yotpo','Yotpo','Plataforma de ecommerce marketing. Reviews, loyalty, SMS, suscripciones y UGC visual.','Ecommerce marketing platform. Reviews, loyalty, SMS, subscriptions and visual UGC.','freemium',15,4.5,false,['ecommerce','reviews','loyalty','marketing'],'yotpo.com'),
  add('cat-13','trustpilot','Trustpilot','Plataforma de reviews líder. Gestiona opiniones, mejora reputacion y construye confianza de marca.','Leading review platform. Manage opinions, improve reputation and build brand trust.','freemium',249,4.2,false,['reviews','reputacion','confianza','opiniones'],'trustpilot.com'),
  add('cat-13','judgeme','Judge.me','App de reviews para ecommerce. Reseñas con fotos, Q&A, wishlist, email reminders y widgets.','Review app for ecommerce. Photo reviews, Q&A, wishlist, email reminders and widgets.','freemium',15,4.9,false,['reviews','ecommerce','widgets','shopify'],'judge.me'),
  add('cat-13','loox','Loox','App de reviews con fotos para Shopify. Social proof visual, referidos, upsells y widgets elegantes.','Photo review app for Shopify. Visual social proof, referrals, upsells and elegant widgets.','paid',9.99,4.9,false,['reviews','shopify','social-proof','fotos'],'loox.io'),
  add('cat-13','shopify-plus','Shopify Plus','Shopify para empresas enterprise. Checkout personalizado, wholesale, multi-store y automatizaciones avanzadas.','Enterprise Shopify. Custom checkout, wholesale, multi-store and advanced automations.','paid',2300,4.3,false,['ecommerce','enterprise','shopify','headless'],'shopify.com/plus'),
  add('cat-13','spreecommerce','Spree Commerce','Framework de ecommerce open source en Ruby. Headless, API-first, multi-vendor y marketplace.','Open source ecommerce framework in Ruby. Headless, API-first, multi-vendor and marketplace.','free',0,4.0,true,['ecommerce','open-source','ruby','headless'],'spreecommerce.org'),
  add('cat-13','open-cart','OpenCart','CMS de ecommerce open source simple y ligero. Modulos, temas, multi-idioma y multi-tienda.','Simple lightweight open source ecommerce CMS. Modules, themes, multi-language and multi-store.','free',0,3.9,true,['ecommerce','open-source','simple','php'],'opencart.com'),
  add('cat-13','vendure','Vendure','Framework de ecommerce headless open source en TypeScript. GraphQL, multi-canal y marketplace ready.','Open source headless ecommerce framework in TypeScript. GraphQL, multi-channel and marketplace ready.','free',0,4.5,true,['ecommerce','open-source','typescript','graphql'],'vendure.io'),
  add('cat-13','shopline','SHOPLINE','Plataforma de ecommerce asiatica. Tienda online, social commerce y live shopping integrados.','Asian ecommerce platform. Online store, social commerce and integrated live shopping.','paid',19,4.3,false,['ecommerce','asia','social-commerce','live-shopping'],'shopline.com'),
  add('cat-13','doofinder','Doofinder','Motor de busqueda inteligente para ecommerce. AI search, recomendaciones y personalizacion en tiempo real.','Smart search engine for ecommerce. AI search, recommendations and real-time personalization.','paid',35,4.6,false,['busqueda','ecommerce','ai','personalizacion'],'doofinder.com'),
  add('cat-13','recharge','Recharge','Plataforma de suscripciones para ecommerce. Gestiona subscripciones recurrentes, bundles y retencion.','Subscription platform for ecommerce. Manage recurring subscriptions, bundles and retention.','paid',99,4.3,false,['suscripciones','ecommerce','recurrente','retencion'],'rechargepayments.com'),
  add('cat-13','bold-commerce','Bold Commerce','Suite de apps para ecommerce. Subscripciones, upsells, precios dinamicos, checkout extensible y loyalty.','Ecommerce app suite. Subscriptions, upsells, dynamic pricing, extensible checkout and loyalty.','paid',49.99,4.2,false,['ecommerce','apps','suscripciones','upsells'],'boldcommerce.com'),
  add('cat-13','swell','Swell','Plataforma de ecommerce headless moderna. APIs, suscripciones, B2B, marketplace y CMS integrado.','Modern headless ecommerce platform. APIs, subscriptions, B2B, marketplace and integrated CMS.','paid',299,4.5,false,['ecommerce','headless','api','b2b'],'swell.is'),
  add('cat-13','elasticpath','Elastic Path','Plataforma de ecommerce composable enterprise. Catalog, pricing, cart y checkout como microservicios.','Composable enterprise ecommerce platform. Catalog, pricing, cart and checkout as microservices.','paid',5000,4.0,false,['ecommerce','composable','enterprise','microservicios'],'elasticpath.com'),

  // ===== MARKETING cat-15 (28 tools) =====
  add('cat-15','mangools','Mangools','Suite SEO sencilla: KWFinder, SERPChecker, LinkMiner, SiteProfiler. Asequible e intuitiva para principiantes.','Simple SEO suite: KWFinder, SERPChecker, LinkMiner, SiteProfiler. Affordable and intuitive for beginners.','paid',29,4.7,false,['seo','keywords','backlinks','asequible'],'mangools.com'),
  add('cat-15','moz','Moz','Plataforma SEO clasica con metrica Domain Authority. Keyword research, rank tracking, site audits y link building.','Classic SEO platform with Domain Authority metric. Keyword research, rank tracking, site audits and link building.','paid',79,4.1,false,['seo','domain-authority','audit','tracking'],'moz.com'),
  add('cat-15','ubersuggest','Ubersuggest','Herramienta SEO de Neil Patel. Keywords, backlinks, site audit y content ideas a precio asequible.','Neil Patel SEO tool. Keywords, backlinks, site audit and content ideas at affordable price.','freemium',20,4.4,false,['seo','keywords','asequible','contenido'],'neilpatel.com/ubersuggest'),
  add('cat-15','se-ranking','SE Ranking','Suite SEO completa y asequible. Rank tracking, keywords, audit, backlinks, marketing plan y white label.','Complete affordable SEO suite. Rank tracking, keywords, audit, backlinks, marketing plan and white label.','paid',23.4,4.7,false,['seo','asequible','white-label','audit'],'seranking.com'),
  add('cat-15','serpstat','Serpstat','Plataforma SEO y PPC todo en uno. Keywords, competitors, backlinks, site audit y content marketing.','All-in-one SEO and PPC platform. Keywords, competitors, backlinks, site audit and content marketing.','paid',69,4.5,false,['seo','ppc','competidores','backlinks'],'serpstat.com'),
  add('cat-15','screamingfrog','Screaming Frog','Crawler SEO de escritorio lider. Audita sitios, encuentra errores tecnicos, analiza redirects y genera XML sitemaps.','Leading desktop SEO crawler. Audits sites, finds technical errors, analyzes redirects and generates XML sitemaps.','freemium',199,4.8,false,['seo','crawler','auditoria','tecnico'],'screamingfrog.co.uk/seo-spider'),
  add('cat-15','sitebulb','Sitebulb','Auditor SEO de escritorio con informes visuales. Crawling, graficos, score de calidad y priorizacion de fixes.','Desktop SEO auditor with visual reports. Crawling, charts, quality scoring and fix prioritization.','paid',13.5,4.8,false,['seo','auditoria','visual','crawler'],'sitebulb.com'),
  add('cat-15','yoast','Yoast SEO','Plugin SEO lider para WordPress. Analisis de legibilidad, snippet preview, schema y XML sitemaps.','Leading SEO plugin for WordPress. Readability analysis, snippet preview, schema and XML sitemaps.','freemium',99,4.6,false,['seo','wordpress','plugin','content'],'yoast.com'),
  add('cat-15','rankmath','Rank Math','Plugin SEO para WordPress con plan gratuito potente. Schema, redirecciones, analytics, 404 monitor y AI.','SEO plugin for WordPress with powerful free plan. Schema, redirects, analytics, 404 monitor and AI.','freemium',5.75,4.9,false,['seo','wordpress','plugin','ai'],'rankmath.com'),
  add('cat-15','seo-press','SEOPress','Plugin SEO ligero para WordPress. XML sitemaps, schema, breadcrumbs, redirecciones y Google Analytics integrado.','Lightweight SEO plugin for WordPress. XML sitemaps, schema, breadcrumbs, redirects and integrated GA.','freemium',49,4.8,false,['seo','wordpress','plugin','ligero'],'seopress.org'),
  add('cat-15','hootsuite','Hootsuite','Gestion de redes sociales todo en uno. Programacion, monitorizacion, analitica, engagement y colaboracion.','All-in-one social media management. Scheduling, monitoring, analytics, engagement and collaboration.','paid',99,4.2,false,['redes-sociales','programacion','analitica','monitorizacion'],'hootsuite.com'),
  add('cat-15','buffer','Buffer','Gestion de redes sociales simple y asequible. Programa posts, analiza rendimiento y construye engagement.','Simple affordable social media management. Schedule posts, analyze performance and build engagement.','freemium',6,4.4,false,['redes-sociales','programacion','simple','asequible'],'buffer.com'),
  add('cat-15','later','Later','Planificador visual de redes sociales. Calendar drag-drop, link in bio, analytics y contenido generado por IA.','Visual social media scheduler. Calendar drag-drop, link in bio, analytics and AI-generated content.','freemium',16.67,4.4,false,['redes-sociales','visual','ia','instagram'],'later.com'),
  add('cat-15','sproutsocial','Sprout Social','Plataforma de gestion de redes sociales enterprise. Smart inbox, reporting, social listening y advocacy.','Enterprise social media management. Smart inbox, reporting, social listening and advocacy.','paid',249,4.3,false,['redes-sociales','enterprise','social-listening','reporting'],'sproutsocial.com'),
  add('cat-15','hubspot-marketing','HubSpot Marketing','Marketing automation integrado con CRM. Email, landing pages, ads, SEO, social media y analytics.','Marketing automation integrated with CRM. Email, landing pages, ads, SEO, social media and analytics.','freemium',15,4.4,false,['marketing','automation','crm','email'],'hubspot.com/products/marketing'),
  add('cat-15','marketo','Adobe Marketo','Marketing automation enterprise. Lead management, email, eventos, attribution y revenue analytics.','Enterprise marketing automation. Lead management, email, events, attribution and revenue analytics.','paid',1000,4.1,false,['marketing','enterprise','automation','adobe'],'marketo.com'),
  add('cat-15','pardot','Salesforce Pardot','Marketing automation B2B de Salesforce. Lead scoring, nurturing, email, ROI reporting y CRM sync.','Salesforce B2B marketing automation. Lead scoring, nurturing, email, ROI reporting and CRM sync.','paid',1250,4.0,false,['marketing','b2b','salesforce','automation'],'pardot.com'),
  add('cat-15','mailchimp-crm','Mailchimp CRM','CRM de marketing integrado con email. Segmentacion, customer journeys, website builder y analytics.','Marketing CRM integrated with email. Segmentation, customer journeys, website builder and analytics.','freemium',13,4.3,false,['marketing','crm','email','automation'],'mailchimp.com'),
  add('cat-15','referralcandy','ReferralCandy','Plataforma de marketing de referidos para ecommerce. Programas de recompensa, referidos automatizados y analytics.','Referral marketing platform for ecommerce. Reward programs, automated referrals and analytics.','paid',47,4.6,false,['referidos','ecommerce','recompensas','viral'],'referralcandy.com'),
  add('cat-15','friendbuy','Friendbuy','Plataforma de referidos y fidelizacion. Referral programs, loyalty y customer advocacy.','Referral and loyalty platform. Referral programs, loyalty and customer advocacy.','paid',599,4.5,false,['referidos','loyalty','fidelizacion','recompensas'],'friendbuy.com'),
  add('cat-15','talkable','Talkable','Plataforma de referidos enterprise. A/B testing, fraud detection, integrations y analytics avanzados.','Enterprise referral platform. A/B testing, fraud detection, integrations and advanced analytics.','paid',1000,4.4,false,['referidos','enterprise','ab-testing','fraud'],'talkable.com'),
  add('cat-15','optinmonster','OptinMonster','Creador de popups y lead generation. Exit intent, gamification, A/B testing y segmentacion avanzada.','Popup and lead generation builder. Exit intent, gamification, A/B testing and advanced segmentation.','paid',9,4.5,false,['popups','leads','conversion','gamification'],'optinmonster.com'),
  add('cat-15','sumo','Sumo','Herramientas gratuitas de crecimiento. Email capture, share buttons, heatmaps y welcome mats.','Free growth tools. Email capture, share buttons, heatmaps and welcome mats.','freemium',39,4.2,false,['crecimiento','email-capture','gratis','popups'],'sumo.com'),
  add('cat-15','privy','Privy','Plataforma de conversion para ecommerce. Popups, flyouts, spin to win, cart saver y email automation.','Conversion platform for ecommerce. Popups, flyouts, spin to win, cart saver and email automation.','freemium',30,4.6,false,['conversion','ecommerce','popups','email'],'privy.com'),
  add('cat-15','unbounce','Unbounce','Creador de landing pages y popups con AI. Drag-drop, A/B testing, smart traffic y mas de 100 templates.','AI landing page and popup builder. Drag-drop, A/B testing, smart traffic and 100+ templates.','paid',74,4.4,false,['landing-pages','conversion','ai','ab-testing'],'unbounce.com'),
  add('cat-15','instapage','Instapage','Plataforma de landing pages enterprise. Personalizacion, AdMap, heatmaps, colaboracion y testing.','Enterprise landing page platform. Personalization, AdMap, heatmaps, collaboration and testing.','paid',199,4.3,false,['landing-pages','enterprise','personalizacion','testing'],'instapage.com'),
  add('cat-15','leadpages','LeadPages','Creador de landing pages y sites para pequenos negocios. Templates, popups, alert bars y pagos integrados.','Landing page and site builder for small businesses. Templates, popups, alert bars and integrated payments.','paid',37,4.3,false,['landing-pages','pymes','templates','popups'],'leadpages.com'),
  add('cat-15','clickfunnels','ClickFunnels','Plataforma de funnels de venta todo en uno. Landing pages, checkout, upsells, email y membership sites.','All-in-one sales funnel platform. Landing pages, checkout, upsells, email and membership sites.','paid',97,4.2,false,['funnels','ventas','landing-pages','todo-en-uno'],'clickfunnels.com'),
]

// Final batch for remaining categories
const more3 = [
  // ===== GESTION PROYECTOS cat-1 (24 tools) =====
  add('cat-1','wrike','Wrike','Gestion de proyectos empresarial con Gantt, dashboards, recursos y automatizaciones. Versatil y potente.','Enterprise project management with Gantt, dashboards, resources and automations. Versatile and powerful.','freemium',9.8,4.2,false,['proyectos','gantt','enterprise','recursos'],'wrike.com'),
  add('cat-1','basecamp','Basecamp','Gestion de proyectos simple y centrada en equipos. Message board, to-dos, docs, schedule y campfire.','Simple team-centered project management. Message board, to-dos, docs, schedule and campfire.','paid',15,4.2,false,['proyectos','simple','equipos','colaboracion'],'basecamp.com'),
  add('cat-1','smartsheet','Smartsheet','Plataforma de trabajo dinamico estilo spreadsheet. Proyectos, procesos, portfolios y automation.','Dynamic spreadsheet-style work platform. Projects, processes, portfolios and automation.','paid',7,4.4,false,['proyectos','spreadsheet','procesos','automatizacion'],'smartsheet.com'),
  add('cat-1','teamwork','Teamwork','Gestion de proyectos para agencias. Presupuestos, recursos, time tracking, facturacion y cliente portal.','Project management for agencies. Budgets, resources, time tracking, billing and client portal.','freemium',5.99,4.4,false,['proyectos','agencias','presupuestos','time-tracking'],'teamwork.com'),
  add('cat-1','mavenlink-kantata','Kantata','Gestion de proyectos profesionales y PSA. Recursos, presupuestos, time tracking y business intelligence.','Professional project management and PSA. Resources, budgets, time tracking and business intelligence.','paid',55,4.1,false,['proyectos','psa','recursos','presupuestos'],'kantata.com'),
  add('cat-1','height','Height','Gestion de proyectos autónoma con IA. Listas, kanban, calendar, Gantt y sprints automaticos.','Autonomous AI project management. Lists, kanban, calendar, Gantt and automatic sprints.','freemium',6.99,4.8,false,['proyectos','ai','autonomo','sprints'],'height.app'),
  add('cat-1','shortcut','Shortcut','Gestion de proyectos para equipos de software. Stories, sprints, iterations, planning y roadmaps.','Project management for software teams. Stories, sprints, iterations, planning and roadmaps.','freemium',7,4.6,false,['proyectos','software','stories','sprints'],'shortcut.com'),
  add('cat-1','taiga','Taiga','Gestion de proyectos agil open source. Scrum, Kanban, issues, wiki y epic boards.','Open source agile project management. Scrum, Kanban, issues, wiki and epic boards.','freemium',5,4.5,true,['proyectos','open-source','agil','scrum'],'taiga.io'),
  add('cat-1','planka','Planka','Tablero Kanban open source tipo Trello. Simple, auto-hospedado, arrastrar y soltar, markdown.','Open source Trello-like Kanban board. Simple, self-hosted, drag and drop, markdown.','free',0,4.5,true,['kanban','open-source','trello-alternativa','self-hosted'],'planka.cloud'),
  add('cat-1','wekan','Wekan','Kanban open source auto-hospedado tipo Trello. Tableros, listas, tarjetas, swimlanes y checklist.','Open source self-hosted Trello-like Kanban. Boards, lists, cards, swimlanes and checklists.','free',0,4.2,true,['kanban','open-source','self-hosted','trello-alternativa'],'wekan.github.io'),
  add('cat-1','focalboard','Focalboard','Kanban open source de Mattermost. Tableros, vistas calendar, gallery, templates y auto-hospedable.','Open source Kanban by Mattermost. Boards, calendar, gallery views, templates and self-hostable.','free',0,4.4,true,['kanban','open-source','mattermost','self-hosted'],'focalboard.com'),
  add('cat-1','todoist','Todoist','Gestion de tareas personales y de equipo. Proyectos, etiquetas, prioridades, recordatorios y productividad.','Personal and team task management. Projects, labels, priorities, reminders and productivity.','freemium',4,4.6,false,['tareas','productividad','equipos','personal'],'todoist.com'),
  add('cat-1','ticktick','TickTick','App de tareas con calendario y pomodoro integrados. Listas, etiquetas, habitos, Eisenhower matrix.','Task app with integrated calendar and pomodoro. Lists, tags, habits, Eisenhower matrix.','freemium',2.79,4.7,false,['tareas','calendario','pomodoro','habitos'],'ticktick.com'),
  add('cat-1','any-do','Any.do','App de tareas con calendario y AI. Listas, recordatorios, planificador diario y WhatsApp reminders.','Task app with calendar and AI. Lists, reminders, daily planner and WhatsApp reminders.','freemium',6,4.4,false,['tareas','calendario','ai','planificador'],'any.do'),
  add('cat-1','things','Things','App de tareas para Apple diseno premium. Proyectos, areas, etiquetas, fechas y sincronizacion iCloud.','Premium Apple task app. Projects, areas, tags, dates and iCloud sync.','paid',49.99,4.6,false,['tareas','apple','diseno','premium'],'culturedcode.com'),
  add('cat-1','fibery','Fibery','Espacio de trabajo conectado con bases de datos, docs y whiteboards. Mapea procesos y conecta equipos.','Connected workspace with databases, docs and whiteboards. Map processes and connect teams.','paid',12,4.6,false,['proyectos','bases-datos','whiteboards','conectado'],'fibery.io'),
  add('cat-1','coda','Coda','Documentos interactivos con tablas, botones y automatizaciones. Combina docs, sheets y apps en uno.','Interactive docs with tables, buttons and automations. Combines docs, sheets and apps in one.','freemium',10,4.6,false,['docs','bases-datos','automatizacion','interactivo'],'coda.io'),
  add('cat-1','airtable','Airtable','Base de datos visual tipo spreadsheet. Vistas, interfaces, automatizaciones, apps y sincronizacion.','Visual spreadsheet-like database. Views, interfaces, automations, apps and sync.','freemium',20,4.6,false,['bases-datos','spreadsheet','visual','nocode'],'airtable.com'),
  add('cat-1','baserow','Baserow','Base de datos open source tipo Airtable. Self-hosted, visual, sin codigo y con API REST.','Open source Airtable-like database. Self-hosted, visual, no-code with REST API.','freemium',5,4.7,true,['bases-datos','open-source','airtable-alternativa','nocode'],'baserow.io'),
  add('cat-1','nifty','Nifty','Gestion de proyectos con chat, docs y roadmaps. Milestones, time tracking, automatizaciones y portales de cliente.','Project management with chat, docs and roadmaps. Milestones, time tracking, automations and client portals.','freemium',5,4.5,false,['proyectos','chat','docs','roadmaps'],'niftypm.com'),
  add('cat-1','hive','Hive','Plataforma de productividad con AI. Proyectos, time tracking, chat, analytics y automatizaciones.','Productivity platform with AI. Projects, time tracking, chat, analytics and automations.','paid',12,4.5,false,['proyectos','ai','productividad','colaboracion'],'hive.com'),
  add('cat-1','motion','Motion','App de calendario y tareas con AI. Planifica automaticamente tu dia, prioriza y protege tiempo de enfoque.','AI calendar and task app. Auto-plans your day, prioritizes and protects focus time.','paid',19,4.5,false,['calendario','ai','tareas','planificacion'],'usemotion.com'),
  add('cat-1','sunsama','Sunsama','Planificador diario consciente. Une calendario, tareas, Trello, Asana, Notion, Jira en una vista diaria.','Mindful daily planner. Unites calendar, tasks, Trello, Asana, Notion, Jira in one daily view.','paid',16,4.6,false,['planificador','calendario','mindful','integraciones'],'sunsama.com'),
  add('cat-1','akiflow','Akiflow','Calendario y tareas con time blocking. Une Gmail, Slack, Notion, Trello y enfoca tu dia.','Calendar and tasks with time blocking. Unites Gmail, Slack, Notion, Trello and focuses your day.','paid',19,4.7,false,['calendario','time-blocking','productividad','integraciones'],'akiflow.com'),

  // ===== DISENO cat-2 (27 tools) =====
  add('cat-2','sketch','Sketch','Herramienta de diseño UI/UX para macOS. Componentes, Symbols, prototipado nativo y plugins.','UI/UX design tool for macOS. Components, Symbols, native prototyping and plugins.','paid',10,4.4,false,['ui','ux','mac','prototipado'],'sketch.com'),
  add('cat-2','adobe-xd','Adobe XD','Herramienta de diseño y prototipado de Adobe. Diseño vectorial, animaciones y coediting.','Adobe design and prototyping tool. Vector design, animations and coediting.','freemium',9.99,4.0,false,['ui','ux','adobe','prototipado'],'adobe.com/products/xd'),
  add('cat-2','framer','Framer','Diseno web y prototipado con React. Publica sitios reales con CMS, SEO, efectos y animaciones.','Web design and prototyping with React. Publish real sites with CMS, SEO, effects and animations.','freemium',5,4.6,false,['ui','web','react','cms'],'framer.com'),
  add('cat-2','adobe-express','Adobe Express','Alternativa gratuita de Adobe a Canva. Plantillas, IA generativa, edición rapida de fotos y videos.','Free Adobe alternative to Canva. Templates, generative AI, quick photo and video editing.','freemium',9.99,4.5,false,['diseno','gratis','templates','adobe'],'adobe.com/express'),
  add('cat-2','vista-create','VistaCreate','Alternativa a Canva con 150K+ templates. Edicion de fotos y videos, kits de marca y animaciones.','Canva alternative with 150K+ templates. Photo and video editing, brand kits and animations.','freemium',10,4.6,false,['diseno','templates','canvas-alternativa','brand-kit'],'create.vista.com'),
  add('cat-2','piktochart','Piktochart','Creador de infografías, presentaciones y reportes visuales. Plantillas profesionales con IA.','Infographic, presentation and visual report creator. Professional AI-powered templates.','freemium',14,4.6,false,['infografias','presentaciones','visual','templates'],'piktochart.com'),
  add('cat-2','venngage','Venngage','Creador de infografías con IA. Plantillas, iconos, datos en vivo, accesibilidad y colaboracion.','AI infographic creator. Templates, icons, live data, accessibility and collaboration.','freemium',19,4.5,false,['infografias','ia','templates','datos'],'venngage.com'),
  add('cat-2','affinity','Affinity','Suite de diseño profesional asequible. Affinity Photo, Designer y Publisher. Alternativa a Adobe.','Affordable professional design suite. Affinity Photo, Designer and Publisher. Adobe alternative.','paid',69.99,4.6,false,['diseno','fotos','editorial','asequible'],'affinity.serif.com'),
  add('cat-2','photopea','Photopea','Editor de fotos online gratuito tipo Photoshop. PSD, XCF, Sketch, RAW, capas, filtros y exportacion.','Free online Photoshop-like photo editor. PSD, XCF, Sketch, RAW, layers, filters and export.','free',0,4.6,false,['fotos','online','gratis','photoshop-alternativa'],'photopea.com'),
  add('cat-2','lunacy','Lunacy','Software de diseño gratuito con IA. Editor de .sketch, auto-layout, UI kits y generacion de texto/imagen con IA.','Free AI-powered design software. .sketch editor, auto-layout, UI kits and AI text/image generation.','free',0,4.6,false,['ui','gratis','ia','sketch'],'icons8.com/lunacy'),
  add('cat-2','gimp','GIMP','Editor de imagenes open source. Capas, filtros, plugins, retoque fotografico y creacion grafica avanzada.','Open source image editor. Layers, filters, plugins, photo retouching and advanced graphic creation.','free',0,4.2,true,['fotos','open-source','gratis','retoque'],'gimp.org'),
  add('cat-2','inkscape','Inkscape','Editor de graficos vectoriales open source. SVG nativo, capas, texto, trazados y extensiones.','Open source vector graphics editor. Native SVG, layers, text, paths and extensions.','free',0,4.3,true,['vectorial','open-source','svg','dibujo'],'inkscape.org'),
  add('cat-2','krita','Krita','Software de pintura digital open source. Pinceles, capas, animacion 2D y herramientas profesionales.','Open source digital painting software. Brushes, layers, 2D animation and professional tools.','free',0,4.5,true,['pintura','open-source','animacion','digital'],'krita.org'),
  add('cat-2','procreate','Procreate','App de dibujo digital lider en iPad. 200+ pinceles, capas, animacion y grabacion de procesos.','Leading digital drawing app for iPad. 200+ brushes, layers, animation and process recording.','paid',12.99,4.8,false,['dibujo','ipad','pinceles','animacion'],'procreate.com'),
  add('cat-2','blender','Blender','Suite 3D open source completa. Modelado, escultura, animacion, renderizado, VFX y video editing.','Complete open source 3D suite. Modeling, sculpting, animation, rendering, VFX and video editing.','free',0,4.6,true,['3d','open-source','animacion','modelado'],'blender.org'),
  add('cat-2','spline','Spline','Herramienta de diseno 3D colaborativa en navegador. Modelado, animacion, interactividad y exportacion web.','Collaborative browser 3D design tool. Modeling, animation, interactivity and web export.','freemium',9,4.7,false,['3d','navegador','colaboracion','web'],'spline.design'),
  add('cat-2','figjam','FigJam','Pizarra colaborativa de Figma. Brainstorming, diagramas, workshops y sticky notes en tiempo real.','Figma collaborative whiteboard. Brainstorming, diagrams, workshops and sticky notes in real time.','freemium',3,4.5,false,['pizarra','colaboracion','brainstorming','diagramas'],'figma.com/figjam'),
  add('cat-2','mural','Mural','Pizarra digital colaborativa enterprise. Workshops, design thinking, agile y metodo visual.','Enterprise collaborative digital whiteboard. Workshops, design thinking, agile and visual methods.','freemium',9.99,4.5,false,['pizarra','colaboracion','workshops','enterprise'],'mural.co'),
  add('cat-2','lucidchart','Lucidchart','Herramienta de diagramas colaborativa. ERD, UML, flujos, organigramas y mapas mentales.','Collaborative diagramming tool. ERD, UML, flows, org charts and mind maps.','freemium',7.95,4.5,false,['diagramas','colaboracion','uml','flujos'],'lucidchart.com'),
  add('cat-2','drawio','draw.io','Editor de diagramas gratuito open source. UML, flujos, redes, organigramas y mapas mentales.','Free open source diagram editor. UML, flows, networks, org charts and mind maps.','free',0,4.6,true,['diagramas','open-source','gratis','uml'],'drawio.com'),
  add('cat-2','whimsical','Whimsical','Suite visual colaborativa. Diagramas, wireframes, documentos y mapas mentales en una herramienta.','Collaborative visual suite. Diagrams, wireframes, docs and mind maps in one tool.','freemium',10,4.7,false,['diagramas','wireframes','colaboracion','visual'],'whimsical.com'),
  add('cat-2','excalidraw','Excalidraw','Pizarra virtual open source con estilo dibujo a mano. Colaborativa, cifrada y embebible.','Open source hand-drawn style virtual whiteboard. Collaborative, encrypted and embeddable.','free',0,4.7,true,['pizarra','open-source','dibujo','colaboracion'],'excalidraw.com'),
  add('cat-2','tldraw','tldraw','Pizarra blanca open source infinita. Dibujo, formas, texto y colaboracion en tiempo real minimalista.','Open source infinite whiteboard. Drawing, shapes, text and real-time collaboration, minimal.','free',0,4.7,true,['pizarra','open-source','colaboracion','minimal'],'tldraw.com'),
  add('cat-2','uxpin','UXPin','Herramienta de prototipado con codigo real. Design systems, estados interactivos y merge con React.','Prototyping tool with real code. Design systems, interactive states and merge with React.','paid',19,4.4,false,['ui','prototipado','design-systems','react'],'uxpin.com'),
  add('cat-2','proto-io','Proto.io','Plataforma de prototipado mobile y web. Transiciones, animaciones, interacciones y user testing.','Mobile and web prototyping platform. Transitions, animations, interactions and user testing.','paid',24,4.4,false,['prototipado','mobile','animaciones','testing'],'proto.io'),
  add('cat-2','origami','Origami Studio','Herramienta de prototipado gratuita de Facebook. Interacciones complejas, animaciones y design systems.','Free Facebook prototyping tool. Complex interactions, animations and design systems.','free',0,4.3,false,['prototipado','facebook','gratis','interacciones'],'origami.design'),
  add('cat-2','zeplin','Zeplin','Handoff de diseño a desarrollo. Especificaciones, assets, snippets de codigo y organizacion de proyectos.','Design-to-dev handoff. Specifications, assets, code snippets and project organization.','freemium',8,4.5,false,['handoff','desarrollo','ui','assets'],'zeplin.io'),
]

const more4 = [
  // ===== COMUNICACION cat-3 (27 tools) =====
  add('cat-3','google-chat','Google Chat','Mensajeria de equipo integrada con Google Workspace. Salas, hilos, bots y busqueda con IA.','Team messaging integrated with Google Workspace. Rooms, threads, bots and AI-powered search.','freemium',6,4.3,false,['chat','google','equipos','workspace'],'chat.google.com'),
  add('cat-3','rocket-chat','Rocket.Chat','Plataforma de comunicacion open source. Mensajeria, videollamadas, omnichannel y compliance enterprise.','Open source communication platform. Messaging, video calls, omnichannel and enterprise compliance.','freemium',3,4.2,true,['chat','open-source','omnicanal','self-hosted'],'rocket.chat'),
  add('cat-3','telegram','Telegram','App de mensajeria con canales, grupos y bots. Cifrado, archivos grandes, stickers y API abierta.','Messaging app with channels, groups and bots. Encryption, large files, stickers and open API.','free',0,4.4,false,['chat','cifrado','canales','bots'],'telegram.org'),
  add('cat-3','whatsapp-business','WhatsApp Business','WhatsApp para empresas. Catalogo, mensajes rapidos, etiquetas, API y chatbot integrado.','WhatsApp for businesses. Catalog, quick replies, labels, API and integrated chatbot.','freemium',0,4.4,false,['chat','whatsapp','negocios','api'],'whatsapp.com/business'),
  add('cat-3','zulip','Zulip','Chat de equipo open source con hilos organizados por tema. Conversaciones estructuradas sin caos.','Open source team chat with topic-organized threads. Structured conversations without chaos.','free',0,4.5,true,['chat','open-source','hilos','organizado'],'zulip.com'),
  add('cat-3','element','Element','Cliente de Matrix open source. Mensajeria cifrada, federada, puentes con Slack, Teams, Discord.','Open source Matrix client. Encrypted, federated messaging, bridges with Slack, Teams, Discord.','freemium',5,4.3,true,['chat','matrix','cifrado','federado'],'element.io'),
  add('cat-3','signal','Signal','App de mensajeria con privacidad maxima. Cifrado E2E, llamadas, historias y sin recoleccion de datos.','Messaging app with maximum privacy. E2E encryption, calls, stories and no data collection.','free',0,4.6,false,['chat','privacidad','cifrado','seguro'],'signal.org'),
  add('cat-3','wire','Wire','Plataforma de comunicacion empresarial segura. E2E encryption, conferencias, compliance y self-hosted.','Secure enterprise communication platform. E2E encryption, conferencing, compliance and self-hosted.','paid',5.85,4.2,false,['chat','seguridad','empresarial','cifrado'],'wire.com'),
  add('cat-3','guilded','Guilded','Alternativa a Discord para gaming y comunidades. Chat, voz, calendario, foros, docs y subgrupos.','Discord alternative for gaming and communities. Chat, voice, calendar, forums, docs and subgroups.','free',0,4.4,false,['chat','gaming','comunidades','voz'],'guilded.gg'),
  add('cat-3','groupme','GroupMe','App de mensajeria grupal de Microsoft. Chats, memes, eventos, encuestas y galerias compartidas.','Microsoft group messaging app. Chats, memes, events, polls and shared galleries.','free',0,4.3,false,['chat','microsoft','grupos','simple'],'groupme.com'),
  add('cat-3','flock','Flock','Plataforma de colaboracion y messaging. Chat, videollamadas, to-dos, notas y encuestas.','Collaboration and messaging platform. Chat, video calls, to-dos, notes and polls.','freemium',4.5,4.1,false,['chat','colaboracion','equipos','tareas'],'flock.com'),
  add('cat-3','twist','Twist','Comunicacion asincrona por hilos. Reduce notificaciones, organiza conversaciones y mejora el foco.','Async thread-based communication. Reduces notifications, organizes conversations and improves focus.','freemium',5,4.4,false,['chat','asincrono','hilos','foco'],'twist.com'),
  add('cat-3','threads','Threads','Comunicacion asincrona con IA. Hilos, resumenes automaticos, decisiones y search inteligente.','Async communication with AI. Threads, auto summaries, decisions and smart search.','freemium',5,4.5,false,['chat','asincrono','ai','resumenes'],'threads.com'),
  add('cat-3','spike','Spike','Email conversacional con chat integrado. Convierte Gmail/Outlook en messenger con notas y tareas.','Conversational email with integrated chat. Turns Gmail/Outlook into a messenger with notes and tasks.','freemium',5,4.4,false,['email','chat','conversacional','productividad'],'spikenow.com'),
  add('cat-3','around','Around','Videollamadas flotantes minimalistas. UI discreta, AI meeting notes, colaboracion y sin fatiga de Zoom.','Minimalist floating video calls. Discreet UI, AI meeting notes, collaboration and no Zoom fatigue.','freemium',7,4.4,false,['videollamadas','minimal','ai','colaboracion'],'around.co'),
  add('cat-3','whereby','Whereby','Videollamadas en navegador sin descargas. Salas permanentes, branding, API y integraciones.','Browser video calls without downloads. Permanent rooms, branding, API and integrations.','freemium',6.99,4.6,false,['videollamadas','navegador','simple','api'],'whereby.com'),
  add('cat-3','jitsi','Jitsi Meet','Videoconferencias open source y gratuitas. Sin limites, cifrado, self-hosted y sin registro.','Open source free video conferencing. No limits, encrypted, self-hosted and no registration.','free',0,4.4,true,['videollamadas','open-source','gratis','cifrado'],'jitsi.org'),
  add('cat-3','gotomeeting','GoTo Meeting','Videoconferencias profesionales con 25 años de historia. HD video, transcripcion, sala permanente y VoIP.','Professional video conferencing with 25 year history. HD video, transcription, permanent room and VoIP.','paid',12,4.2,false,['videollamadas','profesional','webinars','transcripcion'],'goto.com/meeting'),
  add('cat-3','webex','Webex','Videoconferencias enterprise de Cisco. Meeting, calling, webinar, eventos, AI y dispositivos integrados.','Enterprise video conferencing by Cisco. Meeting, calling, webinar, events, AI and integrated devices.','freemium',14.5,4.2,false,['videollamadas','cisco','enterprise','webinars'],'webex.com'),
  add('cat-3','calendly','Calendly','Programacion de reuniones automatizada. Comparte tu disponibilidad, evita el ping-pong de emails.','Automated meeting scheduling. Share your availability, avoid email ping-pong.','freemium',8,4.7,false,['calendario','reuniones','programacion','automatizacion'],'calendly.com'),
  add('cat-3','savvycal','SavvyCal','Programador de reuniones con diseno premium. Ranked availability, overlays y personalizacion avanzada.','Premium meeting scheduler. Ranked availability, calendar overlays and advanced customization.','paid',12,4.8,false,['calendario','reuniones','premium','disponibilidad'],'savvycal.com'),
  add('cat-3','cal-com','Cal.com','Plataforma de programacion open source. Infraestructura de scheduling auto-hospedada y personalizable.','Open source scheduling platform. Self-hosted customizable scheduling infrastructure.','freemium',12,4.6,true,['calendario','open-source','self-hosted','scheduling'],'cal.com'),
  add('cat-3','doodle','Doodle','Herramienta de encuestas para coordinar reuniones. Sondea disponibilidad y encuentra el mejor momento.','Polling tool to coordinate meetings. Survey availability and find the best time.','freemium',6.95,4.2,false,['calendario','encuestas','reuniones','coordinacion'],'doodle.com'),
  add('cat-3','slite','Slite','Base de conocimiento y docs para equipos. Wiki, notas, decision log y verificacion de documentos con IA.','Knowledge base and docs for teams. Wiki, notes, decision log and AI document verification.','freemium',8,4.5,false,['docs','wiki','conocimiento','equipos'],'slite.com'),
  add('cat-3','slab','Slab','Base de conocimiento moderna e intuitiva. Editores, topicos, verificacion y busqueda unificada.','Modern intuitive knowledge base. Editors, topics, verification and unified search.','freemium',6.67,4.6,false,['docs','wiki','conocimiento','busqueda'],'slab.com'),
  add('cat-3','gitbook','GitBook','Plataforma de documentacion con Git integrado. Docs, APIs, changelogs y knowledge bases.','Documentation platform with integrated Git. Docs, APIs, changelogs and knowledge bases.','freemium',0,4.6,false,['docs','documentacion','git','api'],'gitbook.com'),
  add('cat-3','readme','ReadMe','Plataforma de documentacion de APIs interactiva. Playground, changelog, guides y developer hub.','Interactive API documentation platform. Playground, changelog, guides and developer hub.','freemium',99,4.5,false,['docs','api','documentacion','developers'],'readme.com'),

  // ===== CRM cat-4 (27 tools) =====  
  add('cat-4','salesforce','Salesforce','El CRM enterprise mas grande del mundo. Ventas, servicio, marketing, IA Einstein y AppExchange.','The world\'s largest enterprise CRM. Sales, service, marketing, Einstein AI and AppExchange.','paid',25,4.2,false,['crm','enterprise','salesforce','ia'],'salesforce.com'),
  add('cat-4','zoho-crm-full','Zoho CRM Plus','Suite CRM completa de Zoho. Ventas, marketing, servicio, analytics, IA Zia y 50+ apps integradas.','Complete Zoho CRM suite. Sales, marketing, service, analytics, Zia AI and 50+ integrated apps.','paid',57,4.1,false,['crm','suite','zoho','ia'],'zoho.com/crm'),
  add('cat-4','salesflare','Salesflare','CRM inteligente que se rellena solo. Automatiza entrada de datos, rastrea emails y reuniones.','Intelligent self-filling CRM. Automates data entry, tracks emails and meetings.','paid',29,4.7,false,['crm','automatico','ia','ventas'],'salesflare.com'),
  add('cat-4','copper','Copper','CRM nativo de Google Workspace. Integrado con Gmail, Calendar, Drive y automatizacion de datos.','Native Google Workspace CRM. Integrated with Gmail, Calendar, Drive and data automation.','paid',25,4.4,false,['crm','google','gmail','workspace'],'copper.com'),
  add('cat-4','freshsales','Freshsales','CRM de Freshworks con IA. Pipeline visual, lead scoring, email integrado y telefono.','Freshworks CRM with AI. Visual pipeline, lead scoring, integrated email and phone.','freemium',9,4.5,false,['crm','freshworks','ia','pipeline'],'freshworks.com/crm'),
  add('cat-4','capsule','Capsule CRM','CRM simple y elegante. Pipeline visual, contactos, tareas, email e integraciones clave.','Simple elegant CRM. Visual pipeline, contacts, tasks, email and key integrations.','freemium',18,4.4,false,['crm','simple','elegante','pipeline'],'capsulecrm.com'),
  add('cat-4','nimble','Nimble','CRM social que unifica contactos y comunicaciones. Redes sociales, email, pipeline y segmentacion.','Social CRM unifying contacts and communications. Social media, email, pipeline and segmentation.','paid',24.9,4.2,false,['crm','social','contactos','redes-sociales'],'nimble.com'),
  add('cat-4','close','Close','CRM de ventas con llamadas integradas. Power dialer, secuencias de email, pipeline y reporting.','Sales CRM with integrated calling. Power dialer, email sequences, pipeline and reporting.','paid',49,4.6,false,['crm','ventas','llamadas','dialer'],'close.com'),
  add('cat-4','outreach','Outreach','Plataforma de ejecucion de ventas con IA. Secuencias, pipeline, coaching, forecasting y revenue intelligence.','AI sales execution platform. Sequences, pipeline, coaching, forecasting and revenue intelligence.','paid',100,4.3,false,['ventas','ai','secuencias','forecasting'],'outreach.io'),
  add('cat-4','salesloft','SalesLoft','Plataforma de revenue workflow. Cadences, pipeline, coaching, forecasting y revenue intelligence.','Revenue workflow platform. Cadences, pipeline, coaching, forecasting and revenue intelligence.','paid',100,4.3,false,['ventas','workflow','cadences','revenue'],'salesloft.com'),
  add('cat-4','apollo','Apollo.io','Plataforma de ventas con BBDD de leads. 275M+ contactos, secuencias, IA, scoring y dialer.','Sales platform with leads database. 275M+ contacts, sequences, AI, scoring and dialer.','freemium',49,4.5,false,['ventas','leads','secuencias','ia'],'apollo.io'),
  add('cat-4','lemwarm','Lemwarm','Calentador de emails para cold outreach. Mejora la deliverability calentando tu dominio automaticamente.','Email warmup for cold outreach. Improves deliverability by warming your domain automatically.','paid',29,4.6,false,['email','outreach','deliverability','dominio'],'lemwarm.com'),
  add('cat-4','woodpecker','Woodpecker','Cold email y follow-up automation. Campañas personalizadas, IA, deliverability y deteccion de respuestas.','Cold email and follow-up automation. Personalized campaigns, AI, deliverability and reply detection.','paid',29,4.6,false,['email','cold-outreach','automatizacion','ia'],'woodpecker.co'),
  add('cat-4','instantly','Instantly','Plataforma de cold email con warmup ilimitado. Campañas, rotacion de inbox y deliverability avanzada.','Cold email platform with unlimited warmup. Campaigns, inbox rotation and advanced deliverability.','paid',30,4.6,false,['email','cold-outreach','warmup','deliverability'],'instantly.ai'),
  add('cat-4','hubspot-sales','HubSpot Sales','CRM de ventas con productividad integrada. Email tracking, meetings, templates y pipeline automation.','Sales CRM with integrated productivity. Email tracking, meetings, templates and pipeline automation.','freemium',15,4.4,false,['crm','ventas','hubspot','productividad'],'hubspot.com/products/sales'),
  add('cat-4','streak','Streak','CRM integrado en Gmail. Pipeline de ventas, email tracking, mail merge y snippets dentro de tu inbox.','CRM integrated in Gmail. Sales pipeline, email tracking, mail merge and snippets inside your inbox.','freemium',15,4.4,false,['crm','gmail','pipeline','inbox'],'streak.com'),
  add('cat-4','folk','Folk','CRM moderno y minimalista. Listas inteligentes, extension Chrome, sincronizacion LinkedIn y colaboracion.','Modern minimalist CRM. Smart lists, Chrome extension, LinkedIn sync and collaboration.','freemium',20,4.7,false,['crm','moderno','linkedin','minimal'],'folk.app'),
  add('cat-4','attio','Attio','CRM flexible con base de datos personalizable. Modela tus propios objetos, relaciones y flujos de trabajo.','Flexible CRM with customizable database. Model your own objects, relationships and workflows.','freemium',29,4.7,false,['crm','flexible','bases-datos','personalizable'],'attio.com'),
  add('cat-4','nocrm','noCRM.io','CRM para gestion de leads sin complejidad. Pipeline visual, tareas, recordatorios y seguimiento de leads.','Lead management CRM without complexity. Visual pipeline, tasks, reminders and lead follow-up.','paid',12,4.6,false,['crm','leads','simple','pipeline'],'nocrm.io'),
  add('cat-4','onepagecrm','OnePageCRM','CRM de una sola pagina. Pipeline de accion, siguiente paso siempre visible y enfoque en ventas.','Single-page CRM. Action pipeline, next step always visible and sales focus.','paid',15,4.6,false,['crm','simple','accion','ventas'],'onepagecrm.com'),
  add('cat-4','reallysimple','Really Simple Systems','CRM simple y asequible. Contactos, pipeline, marketing email, tickets y GDPR compliant.','Simple affordable CRM. Contacts, pipeline, marketing email, tickets and GDPR compliant.','freemium',14,4.4,false,['crm','simple','asequible','gdpr'],'reallysimplesystems.com'),
  add('cat-4','monday-crm','Monday CRM','CRM sobre la plataforma Monday. Pipeline, contactos, email, automatizaciones y dashboards visuales.','CRM on the Monday platform. Pipeline, contacts, email, automations and visual dashboards.','paid',12,4.5,false,['crm','monday','visual','automatizacion'],'monday.com/crm'),
  add('cat-4','insightly','Insightly','CRM con project management integrado. Pipeline de ventas, proyectos, marketing automation e integraciones.','CRM with integrated project management. Sales pipeline, projects, marketing automation and integrations.','paid',29,4.0,false,['crm','proyectos','marketing','integraciones'],'insightly.com'),
  add('cat-4','agile-crm','Agile CRM','CRM todo en uno para pymes. Ventas, marketing, servicio, telefono y automatizaciones asequibles.','All-in-one CRM for SMBs. Sales, marketing, service, phone and affordable automations.','freemium',8.99,4.1,false,['crm','pymes','todo-en-uno','asequible'],'agilecrm.com'),
  add('cat-4','lessannoyingcrm','Less Annoying CRM','CRM simple con precio unico. Sin modulos, sin complejidad, solo gestion de contactos, pipeline y calendario.','Simple flat-priced CRM. No modules, no complexity, just contact management, pipeline and calendar.','paid',15,4.8,false,['crm','simple','precio-unico','pymes'],'lessannoyingcrm.com'),
  add('cat-4','bitrix24','Bitrix24','Suite de colaboracion empresarial. CRM, tareas, chat, videollamadas, docs y sitios web. Plan gratuito amplio.','Enterprise collaboration suite. CRM, tasks, chat, video calls, docs and websites. Broad free plan.','freemium',49,4.1,false,['crm','colaboracion','suite','todo-en-uno'],'bitrix24.com'),
  add('cat-4','keap','Keap','CRM y automatizacion de marketing para pymes. Campañas, pipeline, pagos, citas y ecommerce.','CRM and marketing automation for SMBs. Campaigns, pipeline, payments, appointments and ecommerce.','paid',129,4.1,false,['crm','marketing','pymes','automatizacion'],'keap.com'),

  // ===== NO-CODE cat-10 (27 tools) =====
  add('cat-10','bubble','Bubble','Plataforma nocode lider para crear apps web completas. Editor visual, base de datos, workflows y plugins.','Leading nocode platform for complete web apps. Visual editor, database, workflows and plugins.','freemium',25,4.4,false,['nocode','apps','web','visual'],'bubble.io'),
  add('cat-10','ifttt','IFTTT','Automatizacion simple entre apps y dispositivos IoT. Applets pre-hechos para tareas cotidianas y hogar conectado.','Simple automation between apps and IoT devices. Pre-made applets for daily tasks and smart home.','freemium',3.33,4.0,false,['automatizacion','iot','simple','applets'],'ifttt.com'),
  add('cat-10','tray','Tray.ai','Plataforma de automatizacion enterprise low-code. iPaaS con AI, APIs y conectores para procesos complejos.','Enterprise low-code automation platform. iPaaS with AI, APIs and connectors for complex processes.','paid',2500,4.4,false,['automatizacion','enterprise','ipaas','ai'],'tray.ai'),
  add('cat-10','zoho-flow','Zoho Flow','Automatizacion entre las apps de Zoho y 800+ apps externas. Workflows visuales sin codigo.','Automation between Zoho apps and 800+ external apps. Visual workflows without code.','paid',12,4.4,false,['automatizacion','zoho','workflows','integraciones'],'zoho.com/flow'),
  add('cat-10','integromat','Make','Automatizacion visual con escenarios complejos. Editor drag-drop, rutas, iteradores y transformaciones de datos.','Visual automation with complex scenarios. Drag-drop editor, routes, iterators and data transformations.','freemium',9,4.7,false,['automatizacion','visual','escenarios','integraciones'],'make.com'),
  add('cat-10','glide','Glide','App builder nocode desde Google Sheets. Crea apps PWA nativas con datos en tiempo real.','Nocode app builder from Google Sheets. Create native PWA apps with real-time data.','freemium',25,4.7,false,['nocode','apps','sheets','pwa'],'glideapps.com'),
  add('cat-10','softr','Softr','Creador de apps y portales desde Airtable/Sheets. Portales de cliente, marketplaces, CRMs y dashboards.','App and portal builder from Airtable/Sheets. Client portals, marketplaces, CRMs and dashboards.','freemium',49,4.7,false,['nocode','airtable','portales','apps'],'softr.io'),
  add('cat-10','stacker','Stacker','Creador de apps y portales desde Airtable. Sin codigo, drag-drop, autenticacion y diseno responsive.','App and portal builder from Airtable. No-code, drag-drop, authentication and responsive design.','paid',250,4.6,false,['nocode','airtable','portales','responsive'],'stacker.app'),
  add('cat-10','retool','Retool','B builder de herramientas internas low-code. Conecta BBDD y APIs, construye UIs con componentes drag-drop.','Low-code internal tool builder. Connect databases and APIs, build UIs with drag-drop components.','freemium',10,4.6,false,['low-code','herramientas-internas','bbdd','api'],'retool.com'),
  add('cat-10','budibase','Budibase','Plataforma open source de low-code. Construye apps internas, automatizaciones y portales de cliente.','Open source low-code platform. Build internal apps, automations and client portals.','freemium',50,4.6,true,['low-code','open-source','apps-internas','automatizacion'],'budibase.com'),
  add('cat-10','appsmith','Appsmith','Plataforma open source low-code para apps internas. Conecta APIs y BBDD con widgets pre-build.','Open source low-code platform for internal apps. Connect APIs and databases with pre-built widgets.','freemium',0,4.5,true,['low-code','open-source','apps-internas','api'],'appsmith.com'),
  add('cat-10','tooljet','ToolJet','Plataforma open source low-code con componentes drag-drop. Apps internas, dashboards y conectores multi-origen.','Open source low-code platform with drag-drop components. Internal apps, dashboards and multi-source connectors.','freemium',0,4.5,true,['low-code','open-source','drag-drop','dashboards'],'tooljet.com'),
  add('cat-10','typeform','Typeform','Creador de formularios conversacionales. Encuestas, quizzes y forms interactivos con diseño premium.','Conversational form builder. Surveys, quizzes and interactive forms with premium design.','freemium',25,4.6,false,['formularios','encuestas','conversacional','diseno'],'typeform.com'),
  add('cat-10','tally','Tally','Creador de formularios gratuito e ilimitado. Forms tipo Typeform sin limites, gratis para siempre.','Free unlimited form builder. Typeform-like forms without limits, free forever.','free',0,4.7,false,['formularios','gratis','ilimitado','simple'],'tally.so'),
  add('cat-10','jotform','JotForm','Creador de formularios con 10,000+ templates. Pagos, aprobaciones, PDFs automaticos e integraciones.','Form builder with 10,000+ templates. Payments, approvals, auto PDFs and integrations.','freemium',34,4.5,false,['formularios','templates','pagos','integraciones'],'jotform.com'),
  add('cat-10','google-forms','Google Forms','Creador de formularios gratuito de Google. Simple, colaborativo, integrado con Sheets y respuestas en tiempo real.','Free Google form builder. Simple, collaborative, integrated with Sheets and real-time responses.','free',0,4.5,false,['formularios','google','gratis','simple'],'google.com','https://google.com/forms/about'),
  add('cat-10','surveymonkey','SurveyMonkey','Plataforma de encuestas lider. Encuestas, market research, employee engagement y CX.','Leading survey platform. Surveys, market research, employee engagement and CX.','freemium',25,4.3,false,['encuestas','research','feedback','cx'],'surveymonkey.com'),
  add('cat-10','adalo','Adalo','App builder nocode para mobile y web. Editor drag-drop, BBDD, acciones y publicacion en stores.','Nocode app builder for mobile and web. Drag-drop editor, database, actions and store publishing.','freemium',36,4.4,false,['nocode','mobile','apps','drag-drop'],'adalo.com'),
  add('cat-10','bravo-studio','Bravo Studio','App builder nocode que conecta Figma con datos reales. Disena en Figma, publica apps nativas.','Nocode app builder connecting Figma with real data. Design in Figma, publish native apps.','freemium',19,4.5,false,['nocode','figma','mobile','apps'],'bravostudio.app'),
  add('cat-10','flutterflow','FlutterFlow','App builder nocode con Flutter de Google. Editor visual, Firebase, acciones y codigo exportable.','Nocode app builder with Google Flutter. Visual editor, Firebase, actions and exportable code.','freemium',30,4.6,false,['nocode','flutter','mobile','google'],'flutterflow.io'),
  add('cat-10','zapier-interfaces','Zapier Interfaces','Creador de paginas y apps de Zapier. Crea CRMs, portales y dashboards sobre tus automatizaciones.','Zapier page and app builder. Create CRMs, portals and dashboards on top of your automations.','paid',20,4.3,false,['nocode','zapier','interfaces','automatizacion'],'zapier.com/interfaces'),
  add('cat-10','airtable-interfaces','Airtable Interfaces','Creador de apps visuales sobre Airtable. Paneles, formularios, vistas de registro y dashboards interactivos.','Visual app builder over Airtable. Panels, forms, record views and interactive dashboards.','freemium',20,4.5,false,['nocode','airtable','interfaces','dashboards'],'airtable.com/interfaces'),
  add('cat-10','voiceflow','Voiceflow','Creador de agentes conversacionales con IA. Disena, prototipa y lanza chatbots de voz y texto.','AI conversational agent builder. Design, prototype and launch voice and text chatbots.','freemium',0,4.5,false,['nocode','chatbots','ia','conversacional'],'voiceflow.com'),
  add('cat-10','landbot','Landbot','Creador de chatbots sin codigo. Landing pages, WhatsApp, Messenger y websites conversacionales.','Nocode chatbot builder. Landing pages, WhatsApp, Messenger and conversational websites.','freemium',30,4.6,false,['nocode','chatbots','whatsapp','conversacional'],'landbot.io'),
  add('cat-10','manychat','ManyChat','Plataforma de marketing conversational. Automatiza Instagram, WhatsApp y Messenger con chatbots.','Conversational marketing platform. Automate Instagram, WhatsApp and Messenger with chatbots.','freemium',15,4.6,false,['nocode','chatbots','instagram','marketing'],'manychat.com'),
  add('cat-10','zapier-chatbots','Zapier Chatbots','Chatbots de Zapier con IA. Responde preguntas con tus datos, KB y automatizaciones sin programar.','Zapier AI chatbots. Answer questions with your data, KB and automations without coding.','paid',20,4.4,false,['nocode','chatbots','ia','zapier'],'zapier.com/chatbots'),
  add('cat-10','notion-integrations','Notion Automations','Automatizaciones nativas de Notion. BBDD, botones, webhooks, formulas y conexiones con 5000+ apps via Zapier.','Native Notion automations. Databases, buttons, webhooks, formulas and 5000+ app connections via Zapier.','freemium',10,4.7,false,['nocode','notion','automatizacion','bbdd'],'notion.so'),

  // ===== PRODUCTIVIDAD cat-12 (27 tools) =====
  add('cat-12','evernote','Evernote','App de notas clasica con captura web. Notebooks, tags, escaneo, busqueda OCR y sincronizacion multi-dispositivo.','Classic note app with web capture. Notebooks, tags, scanning, OCR search and multi-device sync.','freemium',10.83,4.3,false,['notas','productividad','captura','sincronizacion'],'evernote.com'),
  add('cat-12','bear','Bear','App de notas elegante para Apple con Markdown. Etiquetas, temas, exportacion y cifrado. Diseno premium.','Elegant Apple note app with Markdown. Tags, themes, export and encryption. Premium design.','freemium',1.49,4.7,false,['notas','apple','markdown','elegante'],'bear.app'),
  add('cat-12','craft','Craft','App de documentos y notas con diseno premium. Bloques, pizarras, colaboracion y publicacion web.','Premium doc and note app. Blocks, whiteboards, collaboration and web publishing.','freemium',5,4.7,false,['notas','documentos','premium','colaboracion'],'craft.do'),
  add('cat-12','simplenote','Simplenote','App de notas minimalista y gratuita de Automattic. Markdown, tags, versiones y sincronizacion rapida.','Minimalist free note app by Automattic. Markdown, tags, versions and fast sync.','free',0,4.4,false,['notas','minimalista','gratis','markdown'],'simplenote.com'),
  add('cat-12','standard-notes','Standard Notes','App de notas con cifrado de extremo a extremo. Privacidad total, open source, markdown y extensiones.','End-to-end encrypted note app. Total privacy, open source, markdown and extensions.','freemium',7.5,4.5,true,['notas','cifrado','privacidad','open-source'],'standardnotes.com'),
  add('cat-12','joplin','Joplin','App de notas open source con cifrado E2E. Markdown, notebooks, Web Clipper, sincronizacion cloud y plugins.','Open source note app with E2E encryption. Markdown, notebooks, Web Clipper, cloud sync and plugins.','free',0,4.5,true,['notas','open-source','cifrado','markdown'],'joplinapp.org'),
  add('cat-12','logseq','Logseq','Plataforma de conocimiento open source con outline y grafos. Journal, markdown, queries y plugins.','Open source knowledge platform with outlines and graphs. Journal, markdown, queries and plugins.','free',0,4.6,true,['notas','open-source','grafos','journal'],'logseq.com'),
  add('cat-12','roam-research','Roam Research','Herramienta de pensamiento en red con bi-directional links. Outline, grafos, queries y pensamiento conectado.','Networked thinking tool with bi-directional links. Outline, graphs, queries and connected thinking.','paid',15,4.2,false,['notas','pensamiento','grafos','conexiones'],'roamresearch.com'),
  add('cat-12','capacities','Capacities','Estudio de conocimiento con tipos de objetos. Notas, personas, proyectos, libros y grafos conectados.','Knowledge studio with object types. Notes, people, projects, books and connected graphs.','freemium',10,4.6,false,['notas','conocimiento','objetos','grafos'],'capacities.io'),
  add('cat-12','tana','Tana','Herramienta de productividad con IA y grafos. Supertags, queries, comandos y procesamiento de lenguaje natural.','AI and graph productivity tool. Supertags, queries, commands and natural language processing.','freemium',10,4.6,false,['productividad','ai','grafos','nlp'],'tana.inc'),
  add('cat-12','mem','Mem','App de notas con IA que se organiza sola. AI-powered search, auto-tagging, collections y calendario.','Self-organizing AI note app. AI-powered search, auto-tagging, collections and calendar.','freemium',8.33,4.5,false,['notas','ai','auto-organizacion','busqueda'],'mem.ai'),
  add('cat-12','reflect','Reflect','App de notas con IA y spaced repetition. Transcribe reunion, conecta ideas y repasa con repeticion espaciada.','AI note app with spaced repetition. Transcribe meetings, connect ideas and review with spaced repetition.','paid',10,4.5,false,['notas','ai','spaced-repetition','aprendizaje'],'reflect.app'),
  add('cat-12','notion-calendar','Notion Calendar','Calendario de Notion con scheduling inteligente. Conecta con Google Calendar, muestra docs de Notion y programa reuniones.','Notion calendar with smart scheduling. Connect with Google Calendar, show Notion docs and schedule meetings.','free',0,4.7,false,['calendario','notion','scheduling','reuniones'],'notion.so/calendar'),
  add('cat-12','toggl','Toggl Track','Control de tiempo simple y potente. One-click timer, informes, proyectos, equipos y sincronizacion con PM tools.','Simple powerful time tracking. One-click timer, reports, projects, teams and PM tool sync.','freemium',9,4.5,false,['time-tracking','informes','proyectos','simple'],'toggl.com'),
  add('cat-12','clockify','Clockify','Control de tiempo gratuito e ilimitado. Timer, timesheet, informes, facturacion y seguimiento de proyectos.','Free unlimited time tracking. Timer, timesheet, reports, billing and project tracking.','free',0,4.6,false,['time-tracking','gratis','ilimitado','facturacion'],'clockify.me'),
  add('cat-12','harvest','Harvest','Control de tiempo con facturacion integrada. Time tracking, invoices, gastos, presupuestos y informes.','Time tracking with integrated invoicing. Time tracking, invoices, expenses, budgets and reports.','freemium',10.8,4.5,false,['time-tracking','facturacion','gastos','presupuestos'],'getharvest.com'),
  add('cat-12','timely','Timely','Control de tiempo automatico con IA. Registra lo que haces sin timers manuales, usando Memory AI.','Automatic AI time tracking. Records what you do without manual timers, using Memory AI.','paid',9,4.5,false,['time-tracking','ai','automatico','memory'],'timelyapp.com'),
  add('cat-12','rescuetime','RescueTime','Analitica de productividad personal. Tracking automatico, focus sessions, goals y bloqueo de distracciones.','Personal productivity analytics. Auto tracking, focus sessions, goals and distraction blocking.','freemium',6.5,4.3,false,['productividad','tracking','foco','analitica'],'rescuetime.com'),
  add('cat-12','grammarly','Grammarly','Asistente de escritura con IA. Corrige gramatica, tono, claridad y plagio en tiempo real.','AI writing assistant. Corrects grammar, tone, clarity and plagiarism in real time.','freemium',12,4.7,false,['escritura','ai','gramatica','correccion'],'grammarly.com'),
  add('cat-12','hemingway','Hemingway Editor','Editor que mejora la claridad de escritura. Resalta frases complejas, voz pasiva y adverbios.','Editor that improves writing clarity. Highlights complex sentences, passive voice and adverbs.','paid',19.99,4.4,false,['escritura','claridad','edicion','simple'],'hemingwayapp.com'),
  add('cat-12','readwise','Readwise','Revisa y recuerda tus highlights. Sincroniza Kindle, Pocket, Instapaper, Twitter y Notion con spaced repetition.','Review and remember your highlights. Syncs Kindle, Pocket, Instapaper, Twitter and Notion with spaced repetition.','paid',7.99,4.7,false,['lectura','highlights','repaso','conocimiento'],'readwise.io'),
  add('cat-12','pocket','Pocket','Guarda articulos para leer despues. Modo lectura, tags, texto a voz y descubrimiento de contenido.','Save articles to read later. Reading mode, tags, text-to-speech and content discovery.','freemium',4.99,4.4,false,['lectura','guardar','offline','descubrimiento'],'getpocket.com'),
  add('cat-12','instapaper','Instapaper','App clasica de leer despues. Guarda articulos, modo lectura, speed reading y highlights exportables.','Classic read-later app. Save articles, reading mode, speed reading and exportable highlights.','freemium',2.99,4.4,false,['lectura','articulos','highlights','offline'],'instapaper.com'),
  add('cat-12','todoist-advanced','Todoist Pro','Version pro de Todoist con productividad avanzada. Recordatorios, filtros, etiquetas, temas y hasta 300 proyectos.','Todoist Pro with advanced productivity. Reminders, filters, labels, themes and up to 300 projects.','paid',4,4.6,false,['tareas','productividad','pro','recordatorios'],'todoist.com'),
  add('cat-12','any-do-teams','Any.do Teams','Workplace de Any.do con gestion de equipos. Tareas compartidas, calendario, chat y automatizaciones.','Any.do Teams workplace. Shared tasks, calendar, chat and automations.','paid',6,4.4,false,['tareas','equipos','calendario','automatizacion'],'any.do'),
  add('cat-12','twos','Twos','App de listas y recordatorios simple. Things to remember, calendar, journal y colaboracion minimalista.','Simple list and reminder app. Things to remember, calendar, journal and minimalist collaboration.','free',0,4.7,false,['listas','recordatorios','simple','journal'],'twosapp.com'),
  add('cat-12','taskade','Taskade','Espacio de trabajo colaborativo con AI. Tareas, docs, mind maps, video chat y agentes de IA.','Collaborative workspace with AI. Tasks, docs, mind maps, video chat and AI agents.','freemium',8,4.6,false,['tareas','ai','colaboracion','mind-maps'],'taskade.com'),
]

const all = [...newTools, ...more, ...more2, ...more3, ...more4]

const seed = readFileSync(SEED_PATH, 'utf-8')

const toolRegex = /\n  \{\s*\n    id: 'tool-[\s\S]*?\n  \},?/g
const matches = seed.match(toolRegex) || []
const seen = new Set()
const existing = []
for (const t of matches) {
  const m = t.match(/id: '(tool-\d+)'/)
  if (m && !seen.has(m[1])) { seen.add(m[1]); existing.push(t.trim()) }
}

const genIdx = seed.indexOf('export const generatedContent:')
const header = seed.slice(0, genIdx > 0 ? genIdx : seed.length - 1)
const footer = seed.slice(genIdx > 0 ? genIdx : seed.length)

const ts = all.map(t => `  {
    id: '${t.id}', slug: '${t.slug}', name: '${t.name}',
    logo_url: '${t.logo_url}',
    description_es: '${t.description_es}',
    description_en: '${t.description_en}',
    category_id: '${t.category_id}', price_model: '${t.price_model}', price_starting: ${t.price_starting},
    website_url: '${t.website_url}', affiliate_url: null,
    rating_g2: ${t.rating_g2}, rating_capterra: null, is_open_source: ${t.is_open_source}, is_verified: false, listing_tier: 'free',
    tags: [${t.tags.map(x => `'${x}'`).join(', ')}],
  }`)

const toolsDecl = `export const tools: (Tool & { alternatives?: { alternative_slug: string; rank: number }[] })[] = [`
const newContent = seed.slice(0, seed.indexOf('export const categories:')) +
  seed.slice(seed.indexOf('export const categories:'), seed.indexOf('export const tools:')).trim() + '\n\n' +
  toolsDecl + '\n' +
  existing.join(',\n') + ',\n' +
  ts.join(',\n') + '\n]\n\n' +
  footer

writeFileSync(SEED_PATH, newContent)
console.log(`✅ Added ${all.length} tools (existing: ${existing.length}, total: ${existing.length + all.length})`)
